#include "UIFlowLVGL/UIFlowUSBMenu/UIFlowUSBMenu.h"
#include "UIFlowLVGL/UIFlowLVGL.h"

#include "Resource/Plugin/lvgl_plugin.h"
/**********************
 *       WIDGETS
 **********************/

/**********************
 *  STATIC VARIABLES
 **********************/
lv_obj_t* container_usbmenu_scr_uiflowusbmenu;
lv_obj_t* button_1_scr_uiflowusbmenu;
lv_obj_t* label_usbt_scr_uiflowusbmenu;
lv_obj_t* image_1_scr_uiflowusbmenu;
lv_obj_t* button_msdc_scr_uiflowusbmenu;
lv_obj_t* label_msdc_scr_uiflowusbmenu;
lv_obj_t* image_2_scr_uiflowusbmenu;
lv_obj_t* button_pcc_scr_uiflowusbmenu;
lv_obj_t* label_pcc_scr_uiflowusbmenu;
lv_obj_t* image_3_scr_uiflowusbmenu;

lv_obj_t* UIFlowUSBMenu_create(){
	lv_obj_t *parent = lv_plugin_scr_create();
	lv_obj_set_event_cb(parent, UIFlowUSBMenuEventCallback);

	lv_color_t color = {0};
	STYLE_COLOR_PROP(0x00, 0x55, 0x1f, 0x57);
	_lv_obj_set_style_local_color(parent,0,LV_STYLE_BG_COLOR, color);

	if(color.full== LV_COLOR_TRANSP.full){
		_lv_obj_set_style_local_opa(parent,0,LV_STYLE_BG_OPA,0);
	}


	static lv_style_t container_usbmenu_s0;
	lv_style_init(&container_usbmenu_s0);
	lv_style_set_pad_top(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	lv_style_set_pad_bottom(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	lv_style_set_pad_left(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	lv_style_set_pad_right(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	lv_style_set_pad_inner(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_DEFAULT, color);
	lv_style_set_bg_opa(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_opa(&container_usbmenu_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_usbmenu_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_usbmenu_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_usbmenu_s0, LV_STATE_DISABLED, color);
	lv_obj_t *container_usbmenu = lv_cont_create(parent, NULL);
	lv_obj_set_hidden(container_usbmenu, false);
	lv_obj_set_click(container_usbmenu, true);
	lv_obj_set_drag(container_usbmenu, false);
	lv_obj_set_pos(container_usbmenu, 7, 56);
	lv_obj_set_size(container_usbmenu, 307, 163);
	lv_cont_set_layout(container_usbmenu, LV_LAYOUT_COLUMN_MID);
	lv_obj_add_style(container_usbmenu, 0, &container_usbmenu_s0);

	container_usbmenu_scr_uiflowusbmenu = container_usbmenu;


	static lv_style_t button_1_s0;
	lv_style_init(&button_1_s0);
	lv_style_set_radius(&button_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_1_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_1 = lv_btn_create(container_usbmenu, NULL);
	lv_obj_set_hidden(button_1, false);
	lv_obj_set_click(button_1, true);
	lv_obj_set_drag(button_1, false);
	lv_obj_set_pos(button_1, 26, 0);
	lv_obj_set_size(button_1, 255, 45);
	lv_btn_set_checkable(button_1, false);
	lv_btn_set_layout(button_1, LV_LAYOUT_ROW_MID);
	lv_btn_set_fit(button_1, LV_FIT_NONE);
	lv_obj_add_style(button_1, 0, &button_1_s0);

	button_1_scr_uiflowusbmenu = button_1;


	static lv_style_t label_usbt_s0;
	lv_style_init(&label_usbt_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_usbt_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_usbt_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_usbt = lv_label_create(button_1, NULL);
	lv_obj_set_hidden(label_usbt, false);
	lv_obj_set_click(label_usbt, false);
	lv_obj_set_drag(label_usbt, false);
	lv_plugin_label_allocate_ext_attr(label_usbt);
	lv_plugin_label_set_text(label_usbt, LV_PLUGIN_STRING_ID_STRID_USB);
	lv_label_set_text(label_usbt,"USB");
	lv_plugin_label_allocate_ext_attr(label_usbt);
	lv_plugin_label_set_font_type(label_usbt, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_usbt, 33, 13);
	lv_obj_set_size(label_usbt, 32, 19);
	lv_obj_add_style(label_usbt, 0, &label_usbt_s0);

	label_usbt_scr_uiflowusbmenu = label_usbt;


	static lv_style_t image_1_s0;
	lv_style_init(&image_1_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_1 = lv_img_create(button_1, NULL);
	lv_obj_set_hidden(image_1, false);
	lv_obj_set_click(image_1, false);
	lv_obj_set_drag(image_1, false);
	lv_obj_set_pos(image_1, 81, 8);
	lv_obj_set_size(image_1, 28, 28);
	lv_img_set_src(image_1, &icon_usb_on);
	lv_obj_add_style(image_1, 0, &image_1_s0);

	image_1_scr_uiflowusbmenu = image_1;


	static lv_style_t button_msdc_s0;
	lv_style_init(&button_msdc_s0);
	lv_style_set_radius(&button_msdc_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_msdc_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_msdc_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x80, 0x50, 0x50, 0x50) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x80, 0x50, 0x50, 0x50) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_msdc_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_msdc = lv_btn_create(container_usbmenu, NULL);
	lv_obj_set_hidden(button_msdc, false);
	lv_obj_set_click(button_msdc, true);
	lv_obj_set_drag(button_msdc, false);
	lv_obj_set_pos(button_msdc, 26, 45);
	lv_obj_set_size(button_msdc, 255, 45);
	lv_btn_set_checkable(button_msdc, false);
	lv_btn_set_layout(button_msdc, LV_LAYOUT_ROW_TOP);
	lv_btn_set_fit(button_msdc, LV_FIT_NONE);
	lv_obj_add_style(button_msdc, 0, &button_msdc_s0);

	button_msdc_scr_uiflowusbmenu = button_msdc;
	lv_obj_set_event_cb(button_msdc_scr_uiflowusbmenu, btn_msdc_event_callback);


	static lv_style_t label_msdc_s0;
	lv_style_init(&label_msdc_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_msdc_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc5, 0xff, 0xb4, 0x00) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x9c, 0x88, 0x88, 0x88) ; lv_style_set_text_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_msdc_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_msdc = lv_label_create(button_msdc, NULL);
	lv_obj_set_hidden(label_msdc, false);
	lv_obj_set_click(label_msdc, false);
	lv_obj_set_drag(label_msdc, false);
	lv_plugin_label_allocate_ext_attr(label_msdc);
	lv_plugin_label_set_text(label_msdc, LV_PLUGIN_STRING_ID_STRID_MSDC);
	lv_label_set_text(label_msdc,"Mass Storage");
	lv_plugin_label_allocate_ext_attr(label_msdc);
	lv_plugin_label_set_font_type(label_msdc, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_msdc, 33, 12);
	lv_obj_set_size(label_msdc, 109, 19);
	lv_obj_add_style(label_msdc, 0, &label_msdc_s0);

	label_msdc_scr_uiflowusbmenu = label_msdc;


	static lv_style_t image_2_s0;
	lv_style_init(&image_2_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x9c, 0x88, 0x88, 0x88) ; lv_style_set_image_recolor(&image_2_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_2 = lv_img_create(button_msdc, NULL);
	lv_obj_set_hidden(image_2, false);
	lv_obj_set_click(image_2, false);
	lv_obj_set_drag(image_2, false);
	lv_obj_set_pos(image_2, 158, 12);
	lv_obj_set_size(image_2, 28, 28);
	lv_img_set_src(image_2, &icon_usb_msdc);
	lv_obj_add_style(image_2, 0, &image_2_s0);

	image_2_scr_uiflowusbmenu = image_2;


	static lv_style_t button_pcc_s0;
	lv_style_init(&button_pcc_s0);
	lv_style_set_radius(&button_pcc_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_pcc_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_pcc_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x80, 0x50, 0x50, 0x50) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_pcc_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_pcc = lv_btn_create(container_usbmenu, NULL);
	lv_obj_set_hidden(button_pcc, false);
	lv_obj_set_click(button_pcc, true);
	lv_obj_set_drag(button_pcc, false);
	lv_obj_set_pos(button_pcc, 26, 90);
	lv_obj_set_size(button_pcc, 255, 45);
	lv_btn_set_checkable(button_pcc, false);
	lv_btn_set_layout(button_pcc, LV_LAYOUT_ROW_TOP);
	lv_btn_set_fit(button_pcc, LV_FIT_NONE);
	lv_obj_add_style(button_pcc, 0, &button_pcc_s0);

	button_pcc_scr_uiflowusbmenu = button_pcc;
	lv_obj_set_event_cb(button_pcc_scr_uiflowusbmenu, btn_pcc_event_callback);


	static lv_style_t label_pcc_s0;
	lv_style_init(&label_pcc_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_pcc_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc5, 0xff, 0xb4, 0x00) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xf0, 0xea, 0xea, 0xea) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x9c, 0x88, 0x88, 0x88) ; lv_style_set_text_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_pcc_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_pcc = lv_label_create(button_pcc, NULL);
	lv_obj_set_hidden(label_pcc, false);
	lv_obj_set_click(label_pcc, false);
	lv_obj_set_drag(label_pcc, false);
	lv_plugin_label_allocate_ext_attr(label_pcc);
	lv_plugin_label_set_text(label_pcc, LV_PLUGIN_STRING_ID_STRID_PCC);
	lv_label_set_text(label_pcc,"PC Camera");
	lv_plugin_label_allocate_ext_attr(label_pcc);
	lv_plugin_label_set_font_type(label_pcc, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_pcc, 33, 12);
	lv_obj_set_size(label_pcc, 87, 19);
	lv_obj_add_style(label_pcc, 0, &label_pcc_s0);

	label_pcc_scr_uiflowusbmenu = label_pcc;


	static lv_style_t image_3_s0;
	lv_style_init(&image_3_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x9c, 0x88, 0x88, 0x88) ; lv_style_set_image_recolor(&image_3_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_3 = lv_img_create(button_pcc, NULL);
	lv_obj_set_hidden(image_3, false);
	lv_obj_set_click(image_3, false);
	lv_obj_set_drag(image_3, false);
	lv_obj_set_pos(image_3, 136, 12);
	lv_obj_set_size(image_3, 28, 28);
	lv_img_set_src(image_3, &icon_usb_uvc);
	lv_obj_add_style(image_3, 0, &image_3_s0);

	image_3_scr_uiflowusbmenu = image_3;


	return parent;
}
