#include "kwrap/type.h"
#include "kwrap/platform.h"
#include "kflow_audiocapture/wavstudio_tsk.h"
#include "wavstudio_id.h"


extern THREAD_DECLARE(WavStudio_PlayTsk, arglist);
extern THREAD_DECLARE(WavStudio_RecordTsk, arglist);
extern THREAD_DECLARE(WavStudio_RecordWriteTsk, arglist);
extern THREAD_DECLARE(WavStudio_RecordUpdateTsk, arglist);
extern THREAD_DECLARE(WavStudio_PlayTsk2, arglist);


THREAD_HANDLE WAVSTUD_PLAYTSK_ID = 0;
ID FLG_ID_WAVSTUD_PLAY = 0;
THREAD_HANDLE WAVSTUD_RECORDTSK_ID = 0;
ID FLG_ID_WAVSTUD_RECORD = 0;
THREAD_HANDLE WAVSTUD_RECORDWRITETSK_ID = 0;
ID FLG_ID_WAVSTUD_RECORDWRITE = 0;
THREAD_HANDLE WAVSTUD_RECORDUPDATETSK_ID = 0;
ID FLG_ID_WAVSTUD_RECORDUPDATE = 0;

THREAD_HANDLE WAVSTUD_PLAYTSK2_ID = 0;
ID FLG_ID_WAVSTUD_PLAY2 = 0;

#if defined __UITRON || defined __ECOS
SEM_HANDLE SEM_ID_WAVSTUD_PLAY_QUE = 0;
SEM_HANDLE SEM_ID_WAVSTUD_RECORD_QUE = 0;
SEM_HANDLE SEM_ID_WAVSTUD_LOCK = 0;
#else
SEM_HANDLE SEM_ID_WAVSTUD_PLAY_QUE = {0};
SEM_HANDLE SEM_ID_WAVSTUD_RECORD_QUE = {0};
SEM_HANDLE SEM_ID_WAVSTUD_LOCK = {0};
SEM_HANDLE SEM_ID_WAVSTUD_PLAY2_QUE = {0};
#endif

void wavstudio_install_id(void)
{

	OS_CONFIG_FLAG(FLG_ID_WAVSTUD_PLAY);
	OS_CONFIG_FLAG(FLG_ID_WAVSTUD_RECORD);
	OS_CONFIG_FLAG(FLG_ID_WAVSTUD_RECORDWRITE);
	OS_CONFIG_FLAG(FLG_ID_WAVSTUD_RECORDUPDATE);

	OS_CONFIG_FLAG(FLG_ID_WAVSTUD_PLAY2);

	#if defined __UITRON || defined __ECOS
	OS_CONFIG_TASK(WAVSTUD_PLAYTSK_ID,   PRI_WAVSTUD_PLAYTSK,     STKSIZE_WAVSTUD_PLAYTSK,      WavStudio_PlayTsk);
	OS_CONFIG_TASK(WAVSTUD_RECORDTSK_ID,   PRI_WAVSTUD_RECORDTSK,     STKSIZE_WAVSTUD_RECORDTSK,      WavStudio_RecordTsk);
	OS_CONFIG_TASK(WAVSTUD_RECORDWRITETSK_ID,   PRI_WAVSTUD_RECORDWRITETSK,     STKSIZE_WAVSTUD_RECORDWRITETSK,      WavStudio_RecordWriteTsk);
	OS_CONFIG_TASK(WAVSTUD_RECORDUPDATETSK_ID,   PRI_WAVSTUD_RECORDUPDATETSK,     STKSIZE_WAVSTUD_RECORDUPDATETSK,      WavStudio_RecordUpdateTsk);

	OS_CONFIG_SEMPHORE(SEM_ID_WAVSTUD_PLAY_QUE, 0, 1, 1);
	OS_CONFIG_SEMPHORE(SEM_ID_WAVSTUD_RECORD_QUE, 0, 1, 1);
	OS_CONFIG_SEMPHORE(SEM_ID_WAVSTUD_LOCK, 0, 1, 1);

	OS_CONFIG_SEMPHORE(SEM_ID_WAVSTUD_PLAY2_QUE, 0, 1, 1);
	#else
	SEM_CREATE(SEM_ID_WAVSTUD_PLAY_QUE,1);
	SEM_CREATE(SEM_ID_WAVSTUD_RECORD_QUE,1);
	SEM_CREATE(SEM_ID_WAVSTUD_LOCK,1);
	SEM_CREATE(SEM_ID_WAVSTUD_PLAY2_QUE,1);
	#endif

}

void wavstudio_uninstall_id(void)
{
	rel_flg(FLG_ID_WAVSTUD_PLAY);
	rel_flg(FLG_ID_WAVSTUD_RECORD);
	rel_flg(FLG_ID_WAVSTUD_RECORDWRITE);
	rel_flg(FLG_ID_WAVSTUD_RECORDUPDATE);
	rel_flg(FLG_ID_WAVSTUD_PLAY2);

	SEM_DESTROY(SEM_ID_WAVSTUD_PLAY_QUE);
	SEM_DESTROY(SEM_ID_WAVSTUD_RECORD_QUE);
	SEM_DESTROY(SEM_ID_WAVSTUD_LOCK);
	SEM_DESTROY(SEM_ID_WAVSTUD_PLAY2_QUE);
}


BOOL wavstudio_chk_mod_installed(void)
{
	if (WAVSTUD_PLAYTSK_ID && WAVSTUD_RECORDTSK_ID && WAVSTUD_PLAYTSK2_ID) {
		return TRUE;
	} else {
		return FALSE;
	}
}
