#ifndef _UIAPP_BLUEZ_H_
#define _UIAPP_BLUEZ_H_

#include "PrjInc.h"
#include "UIApp/UIAppCommon.h"

#include "UIApp/AppLib.h"

#if(IPCAM_FUNC !=ENABLE)
#include "UIWnd/UIFlow.h"
#endif

#define Ux_BlueZ_SendEvent(...)		Ux_SendEvent(&CustomBlueZObjCtrl, __VA_ARGS__)

typedef enum {
	NVTEVT_BLUEZ_EVT_START      = APPUSER_BLUEZ_BASE, ///< Min value = 0x14002000
	NVTEVT_EXE_BLUEZ_OPEN,
	NVTEVT_EXE_BLUEZ_CLOSE,
	NVTEVT_EXE_BLUEZ_POWERED,
	NVTEVT_EXE_BLUEZ_SCAN,
	NVTEVT_EXE_BLUEZ_CONNECT,
	NVTEVT_EXE_BLUEZ_TRUST,
	NVTEVT_EXE_BLUEZ_PAIR,
	NVTEVT_EXE_BLUEZ_GATT_CHAR_NOTIFY,
	BLUEZ_CB_CONNECT,
	BLUEZ_CB_DISCONNECT,
	BLUEZ_CB_PAIRED,
	BLUEZ_CB_UNPAIRED,
	BLUEZ_CB_GATT_CHAR_NOTIFY,
	NVTEVT_BLUEZ_EVT_END        = APPUSER_BLUEZ_BASE + 0x1000 - 1, ///< Max value = 0x14002fff
} CUSTOM_BLUEZ_EVENT;

#endif //_UIAPP_BLUEZ_H_
