#!/bin/sh

device_node_create()
{
	mknod /dev/$1 c `cat /sys/class/$1/$1/dev | sed "s/:/\ /g"`
}

# Setup mdev
echo "fs" > /proc/nvt_info/bootts
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

echo "fs" > /proc/nvt_info/bootts
