#ifndef UIFLOWWRNMSGAPI_H
#define UIFLOWWRNMSGAPI_H

#include "UIFlowLVGL/UIFlowWrnMsg/UIFlowWrnMsg.h"
#include "UIFlowLVGL/UIFlowLVGL.h"
#include "Resource/Plugin/lvgl_plugin.h"

// Warning message issue
typedef enum {
	FLOWWRNMSG_ISSUE_BATTERY_LOW    = LV_PLUGIN_STRING_ID_STRID_BATTERY_LOW,
	FLOWWRNMSG_ISSUE_NO_CARD = LV_PLUGIN_STRING_ID_STRID_NO_CARD,
	FLOWWRNMSG_ISSUE_CARD_FULL = LV_PLUGIN_STRING_ID_STRID_CARD_FULL,
	FLOWWRNMSG_ISSUE_MEM_FULL = LV_PLUGIN_STRING_ID_STRID_MEMORY_FULL,
	FLOWWRNMSG_ISSUE_CARD_ERR = LV_PLUGIN_STRING_ID_STRID_CARDERROR,
	FLOWWRNMSG_ISSUE_MEM_ERR = LV_PLUGIN_STRING_ID_STRID_MEMORYERROR,
	FLOWWRNMSG_ISSUE_CARD_LOCKED = LV_PLUGIN_STRING_ID_STRID_CARD_LOCKED,
	FLOWWRNMSG_ISSUE_FILE_PROTECTED = LV_PLUGIN_STRING_ID_STRID_FILE_PROTECT,
	FLOWWRNMSG_ISSUE_NO_IMAGE = LV_PLUGIN_STRING_ID_STRID_NO_FILE,
	FLOWWRNMSG_ISSUE_NOT_JPEG = LV_PLUGIN_STRING_ID_STRID_NOT_JPEG,
	FLOWWRNMSG_ISSUE_PICTURE_ERR = LV_PLUGIN_STRING_ID_STRID_FILE_ERROR,
	FLOWWRNMSG_ISSUE_CANT_CROP = LV_PLUGIN_STRING_ID_STRID_FILE_ERROR,
	FLOWWRNMSG_ISSUE_PLEASE_INSERT_SD = LV_PLUGIN_STRING_ID_STRID_PLEASE_INSERT_SD,
	FLOWWRNMSG_ISSUE_CLUSTER_WRONG = LV_PLUGIN_STRING_ID_STRID_CLUSTER_WRONG,
	FLOWWRNMSG_ISSUE_SD_CLASS4 = LV_PLUGIN_STRING_ID_STRID_SD_CLASS4,
	FLOWWRNMSG_ISSUE_SD_CLASS6 = LV_PLUGIN_STRING_ID_STRID_SD_CLASS6,
	//#NT#2016/03/07#KCHong -begin
	//#NT#Low power timelapse function
//#if (TIMELAPSE_LPR_FUNCTION == ENABLE)
	FLOWWRNMSG_ISSUE_PLEASE_WAIT = LV_PLUGIN_STRING_ID_STRID_PLEASE_WAIT,
//#endif
	//#NT#2016/03/07#KCHong -end
	FLOWWRNMSG_ISSUE_MAX
} FLOWWRNMSG_ISSUE;

void  UIFlowWrnMsgAPI_Open_StringID(lv_plugin_res_id id, uint16_t auto_close_time_ms);


#endif /*UIFLOWWRNMSGAPI_H*/
