//#include "SysKer.h"
#include "EthCam/EthsockCliIpcAPI.h"
#include "EthsockCliIpcID.h"
#include "EthsockCliIpcTsk.h"
#include "EthsockCliIpcInt.h"

#define PRI_ETHSOCKCLIIPC_0                4 //10
#define STKSIZE_ETHSOCKCLIIPC_0            4096

#define PRI_ETHSOCKCLIIPC_1                 4 //10
#define STKSIZE_ETHSOCKCLIIPC_1            4096

#define PRI_ETHSOCKCLIIPC_2                 6//10
#define STKSIZE_ETHSOCKCLIIPC_2            4096

ID ETHSOCKCLIIPC_FLG_ID_0[MAX_ETH_PATH_NUM] = {0};
ID ETHSOCKCLIIPC_SEM_ID_0[MAX_ETH_PATH_NUM] = {0};
THREAD_HANDLE ETHSOCKCLIIPC_TSK_ID_0[MAX_ETH_PATH_NUM] = {0};

ID ETHSOCKCLIIPC_FLG_ID_1[MAX_ETH_PATH_NUM] = {0};
ID ETHSOCKCLIIPC_SEM_ID_1[MAX_ETH_PATH_NUM] = {0};
THREAD_HANDLE ETHSOCKCLIIPC_TSK_ID_1[MAX_ETH_PATH_NUM] = {0};

ID ETHSOCKCLIIPC_FLG_ID_2[MAX_ETH_PATH_NUM] = {0};
ID ETHSOCKCLIIPC_SEM_ID_2[MAX_ETH_PATH_NUM] = {0};
THREAD_HANDLE ETHSOCKCLIIPC_TSK_ID_2[MAX_ETH_PATH_NUM] = {0};

void EthsockCliIpc_InstallID(UINT32 path_cnt)
{
	UINT32 i;
	for(i=0;i<path_cnt;i++){
		OS_CONFIG_FLAG(ETHSOCKCLIIPC_FLG_ID_0[i]);
		OS_CONFIG_SEMPHORE(ETHSOCKCLIIPC_SEM_ID_0[i], 0, 1, 1);

#if (MAX_ETHSOCKETCLI_NUM >= 2)

		OS_CONFIG_FLAG(ETHSOCKCLIIPC_FLG_ID_1[i]);
		OS_CONFIG_SEMPHORE(ETHSOCKCLIIPC_SEM_ID_1[i], 0, 1, 1);

		OS_CONFIG_FLAG(ETHSOCKCLIIPC_FLG_ID_2[i]);
		OS_CONFIG_SEMPHORE(ETHSOCKCLIIPC_SEM_ID_2[i], 0, 1, 1);
#endif

		if(i==0){
#if 1
			ETHSOCKCLIIPC_TSK_ID_0[i]=vos_task_create(EthsockCliIpc_Tsk_Path0_0,  0, "EthsockCliIpcTsk_P0_0",   PRI_ETHSOCKCLIIPC_0,	STKSIZE_ETHSOCKCLIIPC_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			ETHSOCKCLIIPC_TSK_ID_1[i]=vos_task_create(EthsockCliIpc_Tsk_Path0_1,  0, "EthsockCliIpcTsk_P0_1",   PRI_ETHSOCKCLIIPC_1,	STKSIZE_ETHSOCKCLIIPC_1);
			ETHSOCKCLIIPC_TSK_ID_2[i]=vos_task_create(EthsockCliIpc_Tsk_Path0_2,  0, "EthsockCliIpcTsk_P0_2",   PRI_ETHSOCKCLIIPC_2,	STKSIZE_ETHSOCKCLIIPC_2);
#endif
		}else{

			ETHSOCKCLIIPC_TSK_ID_0[i]=vos_task_create(EthsockCliIpc_Tsk_Path1_0,  0, "EthsockCliIpcTsk_P1_0",   PRI_ETHSOCKCLIIPC_0,	STKSIZE_ETHSOCKCLIIPC_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			ETHSOCKCLIIPC_TSK_ID_1[i]=vos_task_create(EthsockCliIpc_Tsk_Path1_1,  0, "EthsockCliIpcTsk_P1_1",   PRI_ETHSOCKCLIIPC_1,	STKSIZE_ETHSOCKCLIIPC_1);
			ETHSOCKCLIIPC_TSK_ID_2[i]=vos_task_create(EthsockCliIpc_Tsk_Path1_2,  0, "EthsockCliIpcTsk_P1_2",   PRI_ETHSOCKCLIIPC_2,	STKSIZE_ETHSOCKCLIIPC_2);
#endif
#else
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_0[i], PRI_ETHSOCKCLIIPC_0,  STKSIZE_ETHSOCKCLIIPC_0 , EthsockCliIpc_Tsk_Path0_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_1[i], PRI_ETHSOCKCLIIPC_1,  STKSIZE_ETHSOCKCLIIPC_1,  EthsockCliIpc_Tsk_Path0_1);
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_2[i], PRI_ETHSOCKCLIIPC_2,  STKSIZE_ETHSOCKCLIIPC_2,  EthsockCliIpc_Tsk_Path0_2);
#endif
		}else{
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_0[i], PRI_ETHSOCKCLIIPC_0,  STKSIZE_ETHSOCKCLIIPC_0 , EthsockCliIpc_Tsk_Path1_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_1[i], PRI_ETHSOCKCLIIPC_1,  STKSIZE_ETHSOCKCLIIPC_1,  EthsockCliIpc_Tsk_Path1_1);
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_2[i], PRI_ETHSOCKCLIIPC_2,  STKSIZE_ETHSOCKCLIIPC_2,  EthsockCliIpc_Tsk_Path1_2);
#endif
#endif
		}
	}
}
void EthsockCliIpc_UnInstallID(UINT32 path_cnt)
{
	UINT32 i;
	for(i=0;i<path_cnt;i++){
		rel_flg(ETHSOCKCLIIPC_FLG_ID_0[i]);
		SEM_DESTROY(ETHSOCKCLIIPC_SEM_ID_0[i]);

#if (MAX_ETHSOCKETCLI_NUM >= 2)

		rel_flg(ETHSOCKCLIIPC_FLG_ID_1[i]);
		SEM_DESTROY(ETHSOCKCLIIPC_SEM_ID_1[i]);

		rel_flg(ETHSOCKCLIIPC_FLG_ID_2[i]);
		SEM_DESTROY(ETHSOCKCLIIPC_SEM_ID_2[i]);
#endif

		if(i==0){
#if 1
			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_0[i]);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_1[i]);
			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_2[i]);
#endif
		}else{

			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_0[i]);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_1[i]);
			vos_task_destroy(ETHSOCKCLIIPC_TSK_ID_2[i]);
#endif
#else
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_0[i], PRI_ETHSOCKCLIIPC_0,  STKSIZE_ETHSOCKCLIIPC_0 , EthsockCliIpc_Tsk_Path0_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_1[i], PRI_ETHSOCKCLIIPC_1,  STKSIZE_ETHSOCKCLIIPC_1,  EthsockCliIpc_Tsk_Path0_1);
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_2[i], PRI_ETHSOCKCLIIPC_2,  STKSIZE_ETHSOCKCLIIPC_2,  EthsockCliIpc_Tsk_Path0_2);
#endif
		}else{
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_0[i], PRI_ETHSOCKCLIIPC_0,  STKSIZE_ETHSOCKCLIIPC_0 , EthsockCliIpc_Tsk_Path1_0);
#if (MAX_ETHSOCKETCLI_NUM >= 2)
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_1[i], PRI_ETHSOCKCLIIPC_1,  STKSIZE_ETHSOCKCLIIPC_1,  EthsockCliIpc_Tsk_Path1_1);
			OS_CONFIG_TASK(ETHSOCKCLIIPC_TSK_ID_2[i], PRI_ETHSOCKCLIIPC_2,  STKSIZE_ETHSOCKCLIIPC_2,  EthsockCliIpc_Tsk_Path1_2);
#endif
#endif
		}
	}}
