#ifndef __MENUID_H
#define __MENUID_H

#include "UIWnd/UIFlow.h"

// Menu Item ID
enum _MENU_ID {
	IDM_NULL,

	// Menu common page
	IDM_COMMON_MODE,
	IDM_COMMON_MENU,
	IDM_COMMON_LOCAL,
	IDM_COMMON_LIVESTREAM,
	IDM_COMMON_CLOUD,
	IDM_COMMON_SETUP,
	IDM_COMMON_EXT_SETUP,

	// menu mode page
	IDM_MODE_MOVIE,
	IDM_MODE_PHOTO,
	IDM_MODE_PLAYBACK,
	// Photo Page
	IDM_SELFTIMER,
	IDM_PHOTO_SIZE,
	IDM_CONTINUE_SHOT,
	IDM_QUALITY,
	IDM_SHARPNESS,
	IDM_WB,
	IDM_ANTISHAKE,
	IDM_QUICK_REVIEW,
	IDM_DATE_STAMP,
	IDM_ISO,
	IDM_EV,
	IDM_FD,
	IDM_FLASH,
	IDM_RSC,
	IDM_HDR,
	IDM_WDR,
	IDM_METERING,
	IDM_SCENE,
	IDM_DUAL_CAM,

	// Movie Page
	IDM_MOVIE_SIZE,
	IDM_MOVIE_CYCLIC_REC,
	IDM_MOVIE_WDR,
	IDM_MOVIE_HDR,
	IDM_MOVIE_EV,
	IDM_MOVIE_MOTION_DET,
	IDM_MOVIE_AUDIO,
	IDM_MOVIE_DATEIMPRINT,
	IDM_MOVIE_RSC,
	IDM_MOVIE_RSC_EFFECT,
	IDM_MOVIE_GSENSOR,
	IDM_MOVIE_TIMELAPSE_REC,
	IDM_MOVIE_IR_CUT,
	IDM_MOVIE_SENSOR_ROTATE,
	IDM_MOVIE_PTZ,
	IDM_MOVIE_URGENT_PROTECT_AUTO,
	IDM_MOVIE_URGENT_PROTECT_MANUAL,
	IDM_MOVIE_PIM,
	IDM_MOVIE_FCW,
	IDM_MOVIE_LDWS,
	IDM_MOVIE_DDD,
	IDM_MOVIE_ADAS_CAL,
	IDM_MOVIE_QUALITY,
	IDM_MOVIE_WB,
	IDM_MOVIE_COLOR,
	IDM_MOVIE_DUAL_CAM,
	IDM_MOVIE_CODEC,

	// Playback Page
	IDM_PROTECT,
	IDM_VOLUME,

	// Setup Page
	IDM_DATE_TIME,
	IDM_AUTO_POWER_OFF,
	IDM_BEEP,
	IDM_SILENT,
	IDM_LANGUAGE,
	IDM_TV_MODE,
	IDM_FREQUENCY,
	IDM_FORMAT,
	IDM_DEFAULT,
	IDM_OPENING_LOGO,
	IDM_SCREEN_SAVE,
	IDM_FW_UPDATE,
	IDM_DELETE_ALL,
	IDM_PROTECT_ALL,
	IDM_UNPROTECT_ALL,
	IDM_WIFI,
	IDM_VERSION,
	IDM_DELETE_THIS,

	// Extra Setup Page
	IDM_MCTF,
	IDM_EDGE,
	IDM_NR,
	IDM_IPP_ISO,

};

// Menu String ID
enum _MENU_IDS {
	// Photo Page

	IDS_SELFTIMER           = LV_PLUGIN_STRING_ID_STRID_SELFTIMER,
	IDS_PHOTO_SIZE          = LV_PLUGIN_STRING_ID_STRID_RESOLUTION,
	IDS_CONTINUE_SHOT       = LV_PLUGIN_STRING_ID_STRID_CAP_BURST,
	IDS_QUALITY             = LV_PLUGIN_STRING_ID_STRID_QUALITY,
	IDS_SHARPNESS           = LV_PLUGIN_STRING_ID_STRID_SHARPNESS,
	IDS_WB                  = LV_PLUGIN_STRING_ID_STRID_WB,
	IDS_ANTISHAKE          = LV_PLUGIN_STRING_ID_STRID_ANTI_SHAKING,
	IDS_QUICK_REVIEW        = LV_PLUGIN_STRING_ID_STRID_QUICK_VIEW,
	IDS_DATE_STAMP          = LV_PLUGIN_STRING_ID_STRID_DATE_STAMP,
	IDS_ISO                 = LV_PLUGIN_STRING_ID_STRID_ISO,
	IDS_EV                  = LV_PLUGIN_STRING_ID_STRID_EXPOSURE,
	IDS_FD                  = LV_PLUGIN_STRING_ID_STRID_FACE_DET,
	IDS_FLASH               = LV_PLUGIN_STRING_ID_STRID_FLASHMODE,
	IDS_RSC                 = LV_PLUGIN_STRING_ID_STRID_RSC,
	IDS_HDR                 = LV_PLUGIN_STRING_ID_STRID_HDR,
	IDS_WDR                 = LV_PLUGIN_STRING_ID_STRID_WDR,
	IDS_METERING            = LV_PLUGIN_STRING_ID_STRID_METERING,
	IDS_SCENE               = LV_PLUGIN_STRING_ID_STRID_SCENE,
	IDS_DUAL_CAM            = LV_PLUGIN_STRING_ID_STRID_DUAL_CAM,
	IDS_PHOTO               = LV_PLUGIN_STRING_ID_STRID_STILL,

	// Photo Capture Options
	IDS_SELFTIMER_OFF       = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_SELFTIMER_2SEC      = LV_PLUGIN_STRING_ID_STRID_CAP_TIMER2S,
	IDS_SELFTIMER_5SEC      = LV_PLUGIN_STRING_ID_STRID_CAP_TIMER5S,
	IDS_SELFTIMER_10SEC     = LV_PLUGIN_STRING_ID_STRID_CAP_TIMER10S,

	// Photo Size Options
#if PHOTO_PREVIEW_SLICE_ENC_FUNC
	IDS_PHOTO_SIZE_40M      = LV_PLUGIN_STRING_ID_STRID_40M,
#endif
	IDS_PHOTO_SIZE_15M      = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_PHOTO_SIZE_14M      = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_PHOTO_SIZE_12M      = LV_PLUGIN_STRING_ID_STRID_12MWXH,
	IDS_PHOTO_SIZE_10M      = LV_PLUGIN_STRING_ID_STRID_10MWXH,
	IDS_PHOTO_SIZE_8M       = LV_PLUGIN_STRING_ID_STRID_8MWXH,
	IDS_PHOTO_SIZE_7M       = LV_PLUGIN_STRING_ID_STRID_7MWXH,
	IDS_PHOTO_SIZE_7MHD     = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_PHOTO_SIZE_5M       = LV_PLUGIN_STRING_ID_STRID_5MWXH_USR,
	IDS_PHOTO_SIZE_4M       = LV_PLUGIN_STRING_ID_STRID_4MWXH,
	IDS_PHOTO_SIZE_3M       = LV_PLUGIN_STRING_ID_STRID_3MWXH,
	IDS_PHOTO_SIZE_2M       = LV_PLUGIN_STRING_ID_STRID_2MWXH,
	IDS_PHOTO_SIZE_2MHD     = LV_PLUGIN_STRING_ID_STRID_2MHDWXH,
	IDS_PHOTO_SIZE_1M       = LV_PLUGIN_STRING_ID_STRID_1MWXH,
	IDS_PHOTO_SIZE_VGA      = LV_PLUGIN_STRING_ID_STRID_VGAWXH,

	//Continue shot
	IDS_CONTINUE_SHOT_OFF   = LV_PLUGIN_STRING_ID_STRID_CAP_SINGLE,
	IDS_CONTINUE_SHOT_3     = LV_PLUGIN_STRING_ID_STRID_CAP_BURST_3,
	IDS_CONTINUE_SHOT_ON    = LV_PLUGIN_STRING_ID_STRID_CAP_BURST,
	IDS_CONTINUE_SHOT_SIDE    = LV_PLUGIN_STRING_ID_STRID_CAP_SIDE,
	IDS_CONTINUE_SHOT_30    = LV_PLUGIN_STRING_ID_STRID_CAP_BURST_30,

	// Metering Options
	IDS_AVERAGE             = LV_PLUGIN_STRING_ID_STRID_METER_AVG,
	IDS_CENTER              = LV_PLUGIN_STRING_ID_STRID_METER_CENTER,
	IDS_SPOT                = LV_PLUGIN_STRING_ID_STRID_METER_SPOT,

	//ISO
	IDS_ISO_AUTO            = LV_PLUGIN_STRING_ID_STRID_AUTO,
	IDS_ISO_100             = LV_PLUGIN_STRING_ID_STRID_ISO100,
	IDS_ISO_200             = LV_PLUGIN_STRING_ID_STRID_ISO200,
	IDS_ISO_400             = LV_PLUGIN_STRING_ID_STRID_ISO400,
	IDS_ISO_800             = LV_PLUGIN_STRING_ID_STRID_ISO800,
	IDS_ISO_1600            = LV_PLUGIN_STRING_ID_STRID_ISO1600,

	// Sharpness Options
	IDS_SHARP_STRONG        = LV_PLUGIN_STRING_ID_STRID_STRONG,
	IDS_SHARP_NORMAL        = LV_PLUGIN_STRING_ID_STRID_NORMAL,
	IDS_SHARP_SOFT          = LV_PLUGIN_STRING_ID_STRID_SOFT,

	// WB Options
	IDS_WB_AUTO             = LV_PLUGIN_STRING_ID_STRID_AUTO,
	IDS_WB_DAYLIGHT         = LV_PLUGIN_STRING_ID_STRID_WB_DAY,
	IDS_WB_CLOUDY           = LV_PLUGIN_STRING_ID_STRID_WB_CLOUDY,
	IDS_WB_TUNGSTEN         = LV_PLUGIN_STRING_ID_STRID_WB_TUNGSTEN,
	IDS_WB_FLUORESCENT      = LV_PLUGIN_STRING_ID_STRID_WB_FLUORESCENT,

	// EV Options
	IDS_EV_P20              = LV_PLUGIN_STRING_ID_STRID_EV_P2P0,
	IDS_EV_P16              = LV_PLUGIN_STRING_ID_STRID_EV_P1P6,
	IDS_EV_P13              = LV_PLUGIN_STRING_ID_STRID_EV_P1P3,
	IDS_EV_P10              = LV_PLUGIN_STRING_ID_STRID_EV_P1P0,
	IDS_EV_P06              = LV_PLUGIN_STRING_ID_STRID_EV_P0P6,
	IDS_EV_P03              = LV_PLUGIN_STRING_ID_STRID_EV_P0P3,
	IDS_EV_00               = LV_PLUGIN_STRING_ID_STRID_EV_P0P0,
	IDS_EV_N03              = LV_PLUGIN_STRING_ID_STRID_EV_M0P3,
	IDS_EV_N06              = LV_PLUGIN_STRING_ID_STRID_EV_M0P6,
	IDS_EV_N10              = LV_PLUGIN_STRING_ID_STRID_EV_M1P0,
	IDS_EV_N13              = LV_PLUGIN_STRING_ID_STRID_EV_M1P3,
	IDS_EV_N16              = LV_PLUGIN_STRING_ID_STRID_EV_M1P6,
	IDS_EV_N20              = LV_PLUGIN_STRING_ID_STRID_EV_M2P0,

	// Face Detection Options
	IDS_FD_OFF              = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_FD_ON               = LV_PLUGIN_STRING_ID_STRID_ON,

	// Anti-shaking Options
	IDS_ANTISHAKE_OFF       = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_ANTISHAKE_ON        = LV_PLUGIN_STRING_ID_STRID_ON,

	// Quick View Time Options
	IDS_QV_OFF              = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_QV_2SEC             = LV_PLUGIN_STRING_ID_STRID_2SEC,
	IDS_QV_5SEC             = LV_PLUGIN_STRING_ID_STRID_5SEC,

	// Date Stamp Options
	IDS_DATE_STAMP_OFF      = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_DATE_STAMP_DATE     = LV_PLUGIN_STRING_ID_STRID_DATE,
	IDS_DATE_STAMP_DATE_TIME = LV_PLUGIN_STRING_ID_STRID_DATE_TIME,

	// Flash Options
	IDS_FLASH_AUTO          = LV_PLUGIN_STRING_ID_STRID_FLASHAUTO,
	IDS_FLASH_ON            = LV_PLUGIN_STRING_ID_STRID_ON,
	IDS_FLASH_OFF           = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_FLASH_RED_EYE       = LV_PLUGIN_STRING_ID_STRID_REDEYE,

	// RSC Options
	IDS_RSC_ON              = LV_PLUGIN_STRING_ID_STRID_ON,
	IDS_RSC_OFF             = LV_PLUGIN_STRING_ID_STRID_OFF,

	// HDR Options
	IDS_HDR_ON              = LV_PLUGIN_STRING_ID_STRID_ON,
	IDS_HDR_OFF             = LV_PLUGIN_STRING_ID_STRID_OFF,

	// WDR Options
	IDS_WDR_ON              = LV_PLUGIN_STRING_ID_STRID_ON,
	IDS_WDR_OFF             = LV_PLUGIN_STRING_ID_STRID_OFF,

	// SCENE Options
	IDS_SCENE_AUTO          = LV_PLUGIN_STRING_ID_STRID_AUTO,
	IDS_SCENE_PORTRAIT      = LV_PLUGIN_STRING_ID_STRID_PORTRAIT,
	IDS_SCENE_LANDSCAPE     = LV_PLUGIN_STRING_ID_STRID_LANDSCAPE,

	// DUAL CAM Options
	IDS_DUAL_CAM_FRONT      = LV_PLUGIN_STRING_ID_STRID_FRONT,
	IDS_DUAL_CAM_BEHIND     = LV_PLUGIN_STRING_ID_STRID_BEHIND,
	IDS_DUAL_CAM_BOTH       = LV_PLUGIN_STRING_ID_STRID_BOTH,
	IDS_DUAL_CAM_BOTH2      = LV_PLUGIN_STRING_ID_STRID_BOTH2,

	// Movie Page
	IDS_MOVIE_SIZE          = LV_PLUGIN_STRING_ID_STRID_RESOLUTION,
	IDS_MOVIE_EV            = LV_PLUGIN_STRING_ID_STRID_EXPOSURE,
	IDS_MOVIE_CYCLIC_REC    = LV_PLUGIN_STRING_ID_STRID_CYCLIC_REC,
	IDS_MOVIE_HDR           = LV_PLUGIN_STRING_ID_STRID_HDR,
	IDS_MOVIE_WDR           = LV_PLUGIN_STRING_ID_STRID_WDR,
	IDS_MOVIE_MOTION_DET    = LV_PLUGIN_STRING_ID_STRID_MOTION_DET,
	IDS_MOVIE_AUDIO         = LV_PLUGIN_STRING_ID_STRID_RECORD_AUDIO,
	IDS_MOVIE_DATEIMPRINT   = LV_PLUGIN_STRING_ID_STRID_DATE_STAMP,
	IDS_MOVIE_RSC           = LV_PLUGIN_STRING_ID_STRID_RSC,
	IDS_MOVIE_RSC_EFFECT    = LV_PLUGIN_STRING_ID_STRID_RSC,
	IDS_MOVIE_GSENSOR       = LV_PLUGIN_STRING_ID_STRID_G_SENSOR,
	IDS_MOVIE_TIMELAPSE_REC = LV_PLUGIN_STRING_ID_STRID_TIMELAPSE_REC,
	IDS_MOVIE_IR_CUT        = LV_PLUGIN_STRING_ID_STRID_IRCUT,
	IDS_MOVIE_SENSOR_ROTATE = LV_PLUGIN_STRING_ID_STRID_SENSOR_ROTATE,
	IDS_MOVIE_PTZ           = LV_PLUGIN_STRING_ID_STRID_PTZ,
	IDS_MOVIE_URGENT_PROTECT_AUTO   = LV_PLUGIN_STRING_ID_STRID_URGENT_PROTECT_AUTO,
	IDS_MOVIE_URGENT_PROTECT_MANUAL = LV_PLUGIN_STRING_ID_STRID_URGENT_PROTECT_MANUAL,
	IDS_MOVIE_PIM           = LV_PLUGIN_STRING_ID_STRID_PIM,
	IDS_MOVIE_FCW           = LV_PLUGIN_STRING_ID_STRID_FCW,
	IDS_MOVIE_LDWS          = LV_PLUGIN_STRING_ID_STRID_LDWS,
	IDS_MOVIE_DDD           = LV_PLUGIN_STRING_ID_STRID_DDD,
	IDS_MOVIE_ADAS_CAL      = LV_PLUGIN_STRING_ID_STRID_ADAS,
	IDS_MOVIE_QUALITY       = LV_PLUGIN_STRING_ID_STRID_QUALITY,
	IDS_MOVIE_WB            = LV_PLUGIN_STRING_ID_STRID_WB,
	IDS_MOVIE_COLOR         = LV_PLUGIN_STRING_ID_STRID_COLOR,
	IDS_MOVIE               = LV_PLUGIN_STRING_ID_STRID_MOVIE,
	IDS_MOVIE_DUAL_CAM      = LV_PLUGIN_STRING_ID_STRID_DUAL_CAM,
	IDS_MOVIE_CODEC         = LV_PLUGIN_STRING_ID_STRID_CODEC,

	// Movie Size Options
	IDS_MOVIE_SIZE_2880x2160P50  = LV_PLUGIN_STRING_ID_STRID_2880X2160P50, // 2160P  50fps 2880x2160 (DAR)
	IDS_MOVIE_SIZE_3840x2160P30  = LV_PLUGIN_STRING_ID_STRID_3840X2160P30, // 2160P  30fps 3840x2160
	IDS_MOVIE_SIZE_2880x2160P24  = LV_PLUGIN_STRING_ID_STRID_2880X2160P24, // 2160P  24fps 2880x2160 (DAR)
	//IDS_MOVIE_SIZE_2704x2032P60  = LV_PLUGIN_STRING_ID_STRID_2704X2032P60, // 2.7K   60fps 2704x2032
	//IDS_MOVIE_SIZE_2560x1440P60  = LV_PLUGIN_STRING_ID_STRID_2560X1440P80, // 1440P  80fps 2560x1440
	//IDS_MOVIE_SIZE_2560x1440P60  = LV_PLUGIN_STRING_ID_STRID_2560X1440P60, // 1440P  60fps 2560x1440
	IDS_MOVIE_SIZE_2560x1440P30  = LV_PLUGIN_STRING_ID_STRID_2560X1440P30, // 1440P  30fps 2560x1440
#if 0
	IDS_MOVIE_SIZE_2304x1296P30  = LV_PLUGIN_STRING_ID_STRID_2304X1296P30, // 1296P  30fps 2304x1296
	IDS_MOVIE_SIZE_1080P96       = LV_PLUGIN_STRING_ID_STRID_1080P96,      // 1080P  96fps 1920x1080
	IDS_MOVIE_SIZE_1080P_DUAL    = LV_PLUGIN_STRING_ID_STRID_1080P_DUAL,   // 1080PD 30fps 1920x1080
	IDS_MOVIE_SIZE_720P120       = LV_PLUGIN_STRING_ID_STRID_720P120WXH,   // 720P  120fps 1280x720
#endif
	//MOVIE_SIZE_TAG
	IDS_MOVIE_SIZE_FRONT_2880x2160P50   = LV_PLUGIN_STRING_ID_STRID_FRONT_2880X2160P50, //UHD P50 (DAR)
	IDS_MOVIE_SIZE_FRONT_3840x2160P30   = LV_PLUGIN_STRING_ID_STRID_FRONT_3840X2160P30, //UHD P30
	IDS_MOVIE_SIZE_FRONT_2880x2160P24   = LV_PLUGIN_STRING_ID_STRID_FRONT_2880X2160P24, //UHD P24 (DAR)
	IDS_MOVIE_SIZE_FRONT_2704x2032P60   = LV_PLUGIN_STRING_ID_STRID_FRONT_2704X2032P60, //2.7K P60
	IDS_MOVIE_SIZE_FRONT_2560x1440P80   = LV_PLUGIN_STRING_ID_STRID_FRONT_2560X1440P80, //QHD P60
	IDS_MOVIE_SIZE_FRONT_2560x1440P60   = LV_PLUGIN_STRING_ID_STRID_FRONT_2560X1440P60, //QHD P60
	IDS_MOVIE_SIZE_FRONT_2560x1440P30   = LV_PLUGIN_STRING_ID_STRID_FRONT_2560X1440P30, //QHD P30
	IDS_MOVIE_SIZE_FRONT_2304x1296P30   = LV_PLUGIN_STRING_ID_STRID_FRONT_2304X1296P30, //3MHD P30
	IDS_MOVIE_SIZE_FRONT_1920x1080P120  = LV_PLUGIN_STRING_ID_STRID_FRONT_1920X1080P120, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P96   = LV_PLUGIN_STRING_ID_STRID_FRONT_1920X1080P96, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P60   = LV_PLUGIN_STRING_ID_STRID_FRONT_1920X1080P60, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P30   = LV_PLUGIN_STRING_ID_STRID_FRONT_1920X1080P30, //FHD
	IDS_MOVIE_SIZE_FRONT_1280x720P240   = LV_PLUGIN_STRING_ID_STRID_FRONT_1280X720P240, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P120   = LV_PLUGIN_STRING_ID_STRID_FRONT_1280X720P120, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P60    = LV_PLUGIN_STRING_ID_STRID_FRONT_1280X720P60, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P30    = LV_PLUGIN_STRING_ID_STRID_FRONT_1280X720P30,  //HD
	IDS_MOVIE_SIZE_FRONT_848x480P30     = LV_PLUGIN_STRING_ID_STRID_FRONT_848X480P30,   //WVGA
	IDS_MOVIE_SIZE_FRONT_640x480P240    = LV_PLUGIN_STRING_ID_STRID_FRONT_640X480P240,   //VGA
	IDS_MOVIE_SIZE_FRONT_640x480P30     = LV_PLUGIN_STRING_ID_STRID_FRONT_640X480P30,   //VGA
	IDS_MOVIE_SIZE_FRONT_320x240P30     = LV_PLUGIN_STRING_ID_STRID_FRONT_320X240P30,   //QVGA
	IDS_MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30   = LV_PLUGIN_STRING_ID_STRID_DUAL_3840X2160P30_1920X1080P30,
	IDS_MOVIE_SIZE_DUAL_2560x1440P30_1280x720P30   = LV_PLUGIN_STRING_ID_STRID_DUAL_2560X1440P30_1280X720P30, //QHD HD
	IDS_MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30   = LV_PLUGIN_STRING_ID_STRID_DUAL_2560X1440P30_1920X1080P30, //QHD FHD
	IDS_MOVIE_SIZE_DUAL_2304x1296P30_1280x720P30   = LV_PLUGIN_STRING_ID_STRID_DUAL_2304X1296P30_1280X720P30, //3MHD HD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30  = LV_PLUGIN_STRING_ID_STRID_DUAL_1080P30_1080P30, //FHD FHD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_1280x720P30  = LV_PLUGIN_STRING_ID_STRID_DUAL_1920X1080P30_1280X720P30, //FHD HD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_848x480P30  = LV_PLUGIN_STRING_ID_STRID_DUAL_1920X1080P30_848X480P30, //FHD WVGA
	IDS_MOVIE_SIZE_TRI_1920x1080P30= LV_PLUGIN_STRING_ID_STRID_TRI_1920X1080P30, // 3 x FHD
	IDS_MOVIE_SIZE_TRI_2560x1440P30_1920x1080P30_1920x1080P30 = LV_PLUGIN_STRING_ID_STRID_TRI_2560X1440P30_1920X1080P30_1920X1080P30, //QHD + 3 x FHD
	IDS_MOVIE_SIZE_QUAD_1920x1080P30 = LV_PLUGIN_STRING_ID_STRID_QUAD_1920X1080P30,   // 4 x FHD
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_1920x1080P30 = LV_PLUGIN_STRING_ID_STRID_CLONE_1920X1080P30_1920X1080P30,  //FHD FHD
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30  = LV_PLUGIN_STRING_ID_STRID_CLONE_1920X1080P30_1280X720P30,   //FHD HD
	IDS_MOVIE_SIZE_CLONE_2560x1440P30_848x480P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_2560X1440P30_848X480P30,  //QHD WVGA
	IDS_MOVIE_SIZE_CLONE_2304x1296P30_848x480P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_2304X1296P30_848X480P30,  //3MHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P60_848x480P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_1920X1080P60_848X480P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P60_640x360P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_1920X1080P60_640X360P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_848x480P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_1920X1080P30_848X480P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_2048x2048P30_480x480P30   = LV_PLUGIN_STRING_ID_STRID_CLONE_2048X2048P30_480X480P30,


#if 0
	IDS_MOVIE_SIZE_1080FHD  = LV_PLUGIN_STRING_ID_STRID_1080FHDWXH,
	IDS_MOVIE_SIZE_1080P_DUAL = LV_PLUGIN_STRING_ID_STRID_1080P_DUAL,
	IDS_MOVIE_SIZE_720P120 = LV_PLUGIN_STRING_ID_STRID_720P120WXH,
	IDS_MOVIE_SIZE_1080P    = LV_PLUGIN_STRING_ID_STRID_1080PWXH,
	IDS_MOVIE_SIZE_1440P    = LV_PLUGIN_STRING_ID_STRID_1080PWXH,
	IDS_MOVIE_SIZE_720P     = LV_PLUGIN_STRING_ID_STRID_720PWXH,
	IDS_MOVIE_SIZE_WVGA     = LV_PLUGIN_STRING_ID_STRID_WVGAWXH,
	IDS_MOVIE_SIZE_VGA      = LV_PLUGIN_STRING_ID_STRID_VGAWXH,
	IDS_MOVIE_SIZE_QVGA     = LV_PLUGIN_STRING_ID_STRID_QVGAWXH,
#endif

	// EV Options
	IDS_MOVIE_EV_P20        = LV_PLUGIN_STRING_ID_STRID_EV_P2P0,
	IDS_MOVIE_EV_P16        = LV_PLUGIN_STRING_ID_STRID_EV_P1P6,
	IDS_MOVIE_EV_P13        = LV_PLUGIN_STRING_ID_STRID_EV_P1P3,
	IDS_MOVIE_EV_P10        = LV_PLUGIN_STRING_ID_STRID_EV_P1P0,
	IDS_MOVIE_EV_P06        = LV_PLUGIN_STRING_ID_STRID_EV_P0P6,
	IDS_MOVIE_EV_P03        = LV_PLUGIN_STRING_ID_STRID_EV_P0P3,
	IDS_MOVIE_EV_00         = LV_PLUGIN_STRING_ID_STRID_EV_P0P0,
	IDS_MOVIE_EV_N03        = LV_PLUGIN_STRING_ID_STRID_EV_M0P3,
	IDS_MOVIE_EV_N06        = LV_PLUGIN_STRING_ID_STRID_EV_M0P6,
	IDS_MOVIE_EV_N10        = LV_PLUGIN_STRING_ID_STRID_EV_M1P0,
	IDS_MOVIE_EV_N13        = LV_PLUGIN_STRING_ID_STRID_EV_M1P3,
	IDS_MOVIE_EV_N16        = LV_PLUGIN_STRING_ID_STRID_EV_M1P6,
	IDS_MOVIE_EV_N20        = LV_PLUGIN_STRING_ID_STRID_EV_M2P0,


	// Movie loop rec Options
	IDS_MOVIE_CYCLIC_REC_OFF    = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_CYCLIC_REC_1MIN   = LV_PLUGIN_STRING_ID_STRID_1MIN,
	IDS_MOVIE_CYCLIC_REC_3MIN   = LV_PLUGIN_STRING_ID_STRID_3MIN,
	IDS_MOVIE_CYCLIC_REC_5MIN   = LV_PLUGIN_STRING_ID_STRID_5MIN,
	IDS_MOVIE_CYCLIC_REC_10MIN  = LV_PLUGIN_STRING_ID_STRID_10MIN,

	// Movie motion detect Options
	IDS_MOVIE_MOTION_DET_OFF  = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_MOTION_DET_ON   = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie HDR options
	IDS_MOVIE_HDR_OFF  = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_HDR_ON   = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie WDR options
	IDS_MOVIE_WDR_OFF  = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_WDR_ON   = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie audio Options
	IDS_MOVIE_AUDIO_OFF     = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_AUDIO_ON      = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie dateImprint Options
	IDS_MOVIE_DATEIMPRINT_OFF = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_DATEIMPRINT_ON  = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie RSC Options
	IDS_MOVIE_RSC_OFF         = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_RSC_ON          = LV_PLUGIN_STRING_ID_STRID_ON,
	
    IDS_MOVIE_RSC_LOW         = LV_PLUGIN_STRING_ID_STRID_LOW,
    IDS_MOVIE_RSC_MED      = LV_PLUGIN_STRING_ID_STRID_MED,
    IDS_MOVIE_RSC_HIGH        = LV_PLUGIN_STRING_ID_STRID_HIGH,
    IDS_MOVIE_RSC_SUPER_HIGH        = LV_PLUGIN_STRING_ID_STRID_HIGH,

	// Movie G Sensor Options
	IDS_MOVIE_GSENSOR_OFF     = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_GSENSOR_LOW     = LV_PLUGIN_STRING_ID_STRID_LOW,
	IDS_MOVIE_GSENSOR_MED     = LV_PLUGIN_STRING_ID_STRID_MED,
	IDS_MOVIE_GSENSOR_HIGH    = LV_PLUGIN_STRING_ID_STRID_HIGH,

	// Movie Timelapse record Options
	IDS_MOVIE_TIMELAPSE_REC_OFF     = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_TIMELAPSE_REC_1SEC    = LV_PLUGIN_STRING_ID_STRID_1SEC,
	IDS_MOVIE_TIMELAPSE_REC_5SEC    = LV_PLUGIN_STRING_ID_STRID_5SEC,
	IDS_MOVIE_TIMELAPSE_REC_10SEC   = LV_PLUGIN_STRING_ID_STRID_10SEC,
	IDS_MOVIE_TIMELAPSE_REC_30SEC   = LV_PLUGIN_STRING_ID_STRID_30SEC,
	IDS_MOVIE_TIMELAPSE_REC_1MIN    = LV_PLUGIN_STRING_ID_STRID_1MIN,
	IDS_MOVIE_TIMELAPSE_REC_5MIN    = LV_PLUGIN_STRING_ID_STRID_5MIN,
	IDS_MOVIE_TIMELAPSE_REC_10MIN   = LV_PLUGIN_STRING_ID_STRID_10MIN,
	IDS_MOVIE_TIMELAPSE_REC_30MIN   = LV_PLUGIN_STRING_ID_STRID_30MIN,
	IDS_MOVIE_TIMELAPSE_REC_1HOUR   = LV_PLUGIN_STRING_ID_STRID_1HOUR,
	IDS_MOVIE_TIMELAPSE_REC_2HOUR   = LV_PLUGIN_STRING_ID_STRID_2HOUR,
	IDS_MOVIE_TIMELAPSE_REC_3HOUR   = LV_PLUGIN_STRING_ID_STRID_3HOUR,
	IDS_MOVIE_TIMELAPSE_REC_1DAY    = LV_PLUGIN_STRING_ID_STRID_1DAY,

	// Movie IR Cut Options
	IDS_MOVIE_IR_CUT_OFF         = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_IR_CUT_ON          = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie Sensor Rotate Options
	IDS_MOVIE_SENSOR_ROTATE_OFF  = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_SENSOR_ROTATE_ON   = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie PTZ Options
	IDS_MOVIE_PTZ_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_PTZ_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie auto urgent protect Options
	IDS_MOVIE_URGENT_PROTECT_AUTO_OFF   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_URGENT_PROTECT_AUTO_ON    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie manual urgent protect Options
	IDS_MOVIE_URGENT_PROTECT_MANUAL_OFF   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_URGENT_PROTECT_MANUAL_ON    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie PIM Options
	IDS_MOVIE_PIM_OFF                   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_PIM_ON                    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie FCW Options
	IDS_MOVIE_FCW_OFF                   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_FCW_ON                    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie LDWS Options
	IDS_MOVIE_LDWS_OFF                   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_LDWS_ON                    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie DDD Options
	IDS_MOVIE_DDD_OFF                   = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_DDD_ON                    = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie ADAS CAL Options
	IDS_MOVIE_ADAS_CAL_OFF              = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MOVIE_ADAS_CAL_ON               = LV_PLUGIN_STRING_ID_STRID_ON,

	// Movie DUAL CAM Options
	IDS_MOVIE_DUAL_CAM_FRONT            = LV_PLUGIN_STRING_ID_STRID_FRONT,
	IDS_MOVIE_DUAL_CAM_BEHIND           = LV_PLUGIN_STRING_ID_STRID_BEHIND,
	IDS_MOVIE_DUAL_CAM_BOTH             = LV_PLUGIN_STRING_ID_STRID_BOTH,
	IDS_MOVIE_DUAL_CAM_BOTH2            = LV_PLUGIN_STRING_ID_STRID_BOTH2,

	// Movie codec Options
	IDS_MOVIE_MJPG                      = LV_PLUGIN_STRING_ID_STRID_MJPG,
	IDS_MOVIE_H264                      = LV_PLUGIN_STRING_ID_STRID_H264,
	IDS_MOVIE_H265                      = LV_PLUGIN_STRING_ID_STRID_H265,

	// Movie Quality Options
	IDS_QUALITY_FINE        = LV_PLUGIN_STRING_ID_STRID_FINE,
	IDS_QUALITY_NORMAL      = LV_PLUGIN_STRING_ID_STRID_NORMAL,
	IDS_QUALITY_ECONOMY     = LV_PLUGIN_STRING_ID_STRID_ECONOMY,

	// Playback Page
	IDS_PROTECT             = LV_PLUGIN_STRING_ID_STRID_PROTECT,
	IDS_VOLUME              = LV_PLUGIN_STRING_ID_STRID_VOLUME,
	IDS_PLAYBACK            = LV_PLUGIN_STRING_ID_STRID_PLAYBACK,

	// Volume Options
	IDS_VOL0                 = LV_PLUGIN_STRING_ID_STRID_0,
	IDS_VOL1                 = LV_PLUGIN_STRING_ID_STRID_1,
	IDS_VOL2                 = LV_PLUGIN_STRING_ID_STRID_2,
	IDS_VOL3                 = LV_PLUGIN_STRING_ID_STRID_3,
	IDS_VOL4                 = LV_PLUGIN_STRING_ID_STRID_4,
	IDS_VOL5                 = LV_PLUGIN_STRING_ID_STRID_5,
	IDS_VOL6                 = LV_PLUGIN_STRING_ID_STRID_6,
	IDS_VOL7                 = LV_PLUGIN_STRING_ID_STRID_7,
	IDS_VOL8                 = LV_PLUGIN_STRING_ID_STRID_8,
	IDS_VOL9                 = LV_PLUGIN_STRING_ID_STRID_9,
	IDS_VOL10                = LV_PLUGIN_STRING_ID_STRID_10,

	// Common Page
	IDS_COMMON              = LV_PLUGIN_STRING_ID_STRID_MODE,
	IDS_COMMON_MODE         = LV_PLUGIN_STRING_ID_STRID_MODE,
	IDS_COMMON_MENU         = LV_PLUGIN_STRING_ID_STRID_SETUP,
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	IDS_COMMON_LOCAL        = LV_PLUGIN_STRING_ID_STRID_WIFI,
	IDS_COMMON_LIVESTREAM   = LV_PLUGIN_STRING_ID_STRID_WIFI,
#else
	IDS_COMMON_LOCAL        = LV_PLUGIN_STRING_ID_STRID_WIFI_ETH,
#endif
	IDS_COMMON_CLOUD        = LV_PLUGIN_STRING_ID_STRID_CLOUD,
	IDS_COMMON_SETUP        = LV_PLUGIN_STRING_ID_STRID_SETUP,
	IDS_COMMON_EXT_SETUP    = LV_PLUGIN_STRING_ID_STRID_SETUP,

	IDS_COMMON_LOCAL_OFF    = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_COMMON_LOCAL_ON     = LV_PLUGIN_STRING_ID_STRID_ON,

	IDS_COMMON_CLOUD_OFF    = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_COMMON_CLOUD_ON     = LV_PLUGIN_STRING_ID_STRID_ON,

	IDS_MODE                = LV_PLUGIN_STRING_ID_STRID_MODE,
	IDS_MODE_MOVIE          = LV_PLUGIN_STRING_ID_STRID_MOVIE,
	IDS_MODE_PHOTO          = LV_PLUGIN_STRING_ID_STRID_PHOTO_PAPER,
	IDS_MODE_PLAYBACK       = LV_PLUGIN_STRING_ID_STRID_PLAYBACK,

	// Setup Page
	IDS_DATE_TIME           = LV_PLUGIN_STRING_ID_STRID_DATE_TIME,
	IDS_AUTO_POWER_OFF      = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF,
	IDS_BEEP                = LV_PLUGIN_STRING_ID_STRID_BEEPER,
	IDS_SILENT              = LV_PLUGIN_STRING_ID_STRID_BEEPER,
	IDS_LANGUAGE            = LV_PLUGIN_STRING_ID_STRID_LANGUAGE,
	IDS_TV_MODE             = LV_PLUGIN_STRING_ID_STRID_TV_MODE,
	IDS_FREQUENCY           = LV_PLUGIN_STRING_ID_STRID_FREQUENCY,
	IDS_FORMAT              = LV_PLUGIN_STRING_ID_STRID_FORMAT,
	IDS_DEFAULT             = LV_PLUGIN_STRING_ID_STRID_DEFAULT_SETTING,
	IDS_OPENING_LOGO        = LV_PLUGIN_STRING_ID_STRID_LOGO_DISPLAY,
	IDS_VERSION             = LV_PLUGIN_STRING_ID_STRID_VERSION,
	IDS_WIFI                = LV_PLUGIN_STRING_ID_STRID_WIFI,
	IDS_SCREEN_SAVE         = LV_PLUGIN_STRING_ID_STRID_SCREEN_SAVE,
	IDS_FW_UPDATE           = LV_PLUGIN_STRING_ID_STRID_FW_UPDATE,
	IDS_DELETE_ALL          = LV_PLUGIN_STRING_ID_STRID_DELETEALL,
	IDS_PROTECT_ALL         = LV_PLUGIN_STRING_ID_STRID_LOCKALL,
	IDS_UNPROTECT_ALL       = LV_PLUGIN_STRING_ID_STRID_UNLOCKALL,
	IDS_SETUP               = LV_PLUGIN_STRING_ID_STRID_SETUP,

	// Power Saving Options
	IDS_OFF                 = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_1MIN                = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_1MIN,
	IDS_2MIN                = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_2MIN,
	IDS_3MIN                = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_3MIN,
	IDS_5MIN                = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_5MIN,
	IDS_10MIN               = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_10MIN,

	// Beep Options
	IDS_SILENT_ON            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_SILENT_OFF           = LV_PLUGIN_STRING_ID_STRID_ON,

	IDS_BEEP_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_BEEP_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// Language Options
	IDS_LANG_EN             = LV_PLUGIN_STRING_ID_STRID_LANG_EN,
	IDS_LANG_DE             = LV_PLUGIN_STRING_ID_STRID_LANG_DE,
	IDS_LANG_FR             = LV_PLUGIN_STRING_ID_STRID_LANG_FR,
	IDS_LANG_ES             = LV_PLUGIN_STRING_ID_STRID_LANG_ES,
	IDS_LANG_IT             = LV_PLUGIN_STRING_ID_STRID_LANG_IT,
	IDS_LANG_PO             = LV_PLUGIN_STRING_ID_STRID_LANG_PO,
	IDS_LANG_SC             = LV_PLUGIN_STRING_ID_STRID_LANG_SC,
	IDS_LANG_TC             = LV_PLUGIN_STRING_ID_STRID_LANG_TC,
	IDS_LANG_JP             = LV_PLUGIN_STRING_ID_STRID_LANG_JP,
	IDS_LANG_RU             = LV_PLUGIN_STRING_ID_STRID_LANG_RU,
	IDS_LANG_DU             = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_LANG_TU             = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_LANG_PB             = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_LANG_YI             = LV_PLUGIN_STRING_ID_STRID_NULL_,
	IDS_LANG_PL             = LV_PLUGIN_STRING_ID_STRID_NULL_,


	// TV Mode Options
	IDS_TV_NTSC             = LV_PLUGIN_STRING_ID_STRID_TV_NTSC,
	IDS_TV_PAL              = LV_PLUGIN_STRING_ID_STRID_TV_PAL,

	// Frequency Options
	IDS_50HZ                = LV_PLUGIN_STRING_ID_STRID_50HZ,
	IDS_60HZ                = LV_PLUGIN_STRING_ID_STRID_60HZ,

	// Wi-Fi Options
	IDS_WIFI_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_WIFI_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// Opening Logo Display Options
	IDS_LOGO_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_LOGO_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// Screen Save Option
	IDS_AUTO_OFF_OFF        = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_AUTO_OFF_1MIN       = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_1MIN,
	IDS_AUTO_OFF_3MIN       = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_3MIN,
	IDS_AUTO_OFF_5MIN       = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_5MIN,
	IDS_AUTO_OFF_10MIN      = LV_PLUGIN_STRING_ID_STRID_AUTO_OFF_10MIN,

	// Extra Setup Page
	IDS_MCTF                = LV_PLUGIN_STRING_ID_STRID_MCTF,
	IDS_EDGE                = LV_PLUGIN_STRING_ID_STRID_EDGE,
	IDS_NR                  = LV_PLUGIN_STRING_ID_STRID_NR,
	IDS_IPP_ISO             = LV_PLUGIN_STRING_ID_STRID_ISO,
	IDS_EXT_SETUP           = LV_PLUGIN_STRING_ID_STRID_SETUP,

	// MCTF Options
	IDS_MCTF_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_MCTF_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// EDGE Options
	IDS_EDGE_OFF            = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_EDGE_ON             = LV_PLUGIN_STRING_ID_STRID_ON,

	// NR Options
	IDS_NR_OFF              = LV_PLUGIN_STRING_ID_STRID_OFF,
	IDS_NR_ON               = LV_PLUGIN_STRING_ID_STRID_ON,

	// IPP ISO Options
	IDS_IPP_ISO_AUTO        = LV_PLUGIN_STRING_ID_STRID_AUTO,
	IDS_IPP_ISO_50          = LV_PLUGIN_STRING_ID_STRID_ISO50,
	IDS_IPP_ISO_200         = LV_PLUGIN_STRING_ID_STRID_ISO200,
	IDS_IPP_ISO_800         = LV_PLUGIN_STRING_ID_STRID_ISO800,
	IDS_IPP_ISO_3200        = LV_PLUGIN_STRING_ID_STRID_ISO3200,
//	IDS_IPP_ISO_6400        = LV_PLUGIN_STRING_ID_STRID_ISO6400,
//	IDS_IPP_ISO_12800       = LV_PLUGIN_STRING_ID_STRID_ISO12800,

};

// Menu Icon ID
enum _MENU_IDI {
	// Photo Page
	IDI_SELFTIMER          = LV_PLUGIN_IMG_ID_ICON_SELFTIMER_M,
	IDI_PHOTO_SIZE         = LV_PLUGIN_IMG_ID_ICON_RESOLUTION_M,
	IDI_CONTINUE_SHOT      = LV_PLUGIN_IMG_ID_ICON_BUST_M,
	IDI_QUALITY            = LV_PLUGIN_IMG_ID_ICON_QUALITY_M,
	IDI_SHARPNESS          = LV_PLUGIN_IMG_ID_ICON_SHARPNESS_M,
	IDI_WB                 = LV_PLUGIN_IMG_ID_ICON_WB_M,
	IDI_ANTISHAKE          = LV_PLUGIN_IMG_ID_ICON_SHAKE_ON_M,
	IDI_QUICK_REVIEW       = LV_PLUGIN_IMG_ID_ICON_QUICK_REVIEW_M,
	IDI_DATE_STAMP         = LV_PLUGIN_IMG_ID_ICON_DATE_PRINT_M,
	IDI_ISO                = LV_PLUGIN_IMG_ID_ICON_ISO_M,
	IDI_EV                 = LV_PLUGIN_IMG_ID_ICON_EV_M,
	IDI_FD                 = LV_PLUGIN_IMG_ID_ICON_FACE_ON_M,
	IDI_FLASH              = LV_PLUGIN_IMG_ID_ICON_FLASH_ON_M,
	IDI_RSC                = LV_PLUGIN_IMG_ID_ICON_RSC_ON_M,
	IDI_HDR                = LV_PLUGIN_IMG_ID_ICON_HDR_M,
	IDI_WDR                = LV_PLUGIN_IMG_ID_ICON_MENU_WDR_M,
	IDI_METERING           = LV_PLUGIN_IMG_ID_ICON_METERING_M,
	IDI_SCENE              = LV_PLUGIN_IMG_ID_ICON_SCENE_MODE_M,
	IDI_DUAL_CAM           = LV_PLUGIN_IMG_ID_ICON_DUALCAM_BOTH_M,
	IDI_PHOTO              = 0,       // Photo menu enable icon
	IDIX_PHOTO             = 0,      // Photo menu disable icon

	// Movie size options
	IDI_MOVIE_SIZE_1080FHD  = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_1080P    = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_1440P    = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_720P     = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_WVGA     = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_VGA      = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_MOVIE_SIZE_QVGA     = LV_PLUGIN_IMG_ID_ICON_OK,

	// Photo Size Options
#if PHOTO_PREVIEW_SLICE_ENC_FUNC
	IDI_PHOTO_SIZE_40M      = LV_PLUGIN_IMG_ID_ICON_OK,
#endif
	IDI_PHOTO_SIZE_15M      = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_14M      = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_12M      = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_10M      = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_8M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_7M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_7MHD     = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_5M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_4M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_3M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_2M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_1M       = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_2MHD     = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_PHOTO_SIZE_VGA      = LV_PLUGIN_IMG_ID_ICON_OK,

	// Movie Page
	IDI_MOVIE_SIZE          = LV_PLUGIN_IMG_ID_ICON_RESOLUTION_M,
	IDI_MOVIE_EV            = LV_PLUGIN_IMG_ID_ICON_EV_M,
	IDI_MOVIE_CYCLIC_REC    = LV_PLUGIN_IMG_ID_ICON_CYCLIC_REC_M,
	IDI_MOVIE_HDR           = LV_PLUGIN_IMG_ID_ICON_HDR_M,
	IDI_MOVIE_WDR           = LV_PLUGIN_IMG_ID_ICON_MENU_WDR_M,
	IDI_MOVIE_MOTION_DET    = LV_PLUGIN_IMG_ID_ICON_MOTION_DET_ON_M,
	IDI_MOVIE_AUDIO         = LV_PLUGIN_IMG_ID_ICON_SOUND_REC_ON_M,
	IDI_MOVIE_DATEIMPRINT   = LV_PLUGIN_IMG_ID_ICON_DATE_PRINT_M,
	IDI_MOVIE_RSC           = LV_PLUGIN_IMG_ID_ICON_RSC_ON_M,
	IDI_MOVIE_RSC_EFFECT    = LV_PLUGIN_IMG_ID_ICON_RSC_ON_M,
	IDI_MOVIE_TIMELAPSE_REC = LV_PLUGIN_IMG_ID_ICON_TIME_LAPSE_ON_M,
	IDI_MOVIE_GSENSOR       = LV_PLUGIN_IMG_ID_ICON_G_SENSOR_M,
	IDI_MOVIE_IR_CUT        = LV_PLUGIN_IMG_ID_ICON_IRCUT_ON_M,
	IDI_MOVIE_PTZ           = LV_PLUGIN_IMG_ID_ICON_CAM_PTZ_ON_M,
	IDI_MOVIE_SENSOR_ROTATE = LV_PLUGIN_IMG_ID_ICON_VIDEO_FLIP_ON_M,
	IDI_MOVIE_DUAL_REC      = LV_PLUGIN_IMG_ID_ICON_DUALCAM_BOTH_M,
	IDI_MOVIE_URGENT_PROTECT_AUTO    = LV_PLUGIN_IMG_ID_ICON_URGENT_PROTECT_AUTO_M,
	IDI_MOVIE_URGENT_PROTECT_MANUAL  = LV_PLUGIN_IMG_ID_ICON_URGENT_PROTECT_MANUAL_M,
	IDI_MOVIE_PIM           = LV_PLUGIN_IMG_ID_ICON_PIM_ON_M,
	IDI_MOVIE_FCW           = LV_PLUGIN_IMG_ID_ICON_FCW_ON_M,
	IDI_MOVIE_LDWS          = LV_PLUGIN_IMG_ID_ICON_LDWS_ON_M,
	IDI_MOVIE_DDD           = LV_PLUGIN_IMG_ID_ICON_DDD_ON_M,
	IDI_MOVIE_ADAS_CAL      = LV_PLUGIN_IMG_ID_ICON_ADAS_CAL_M,
	IDI_MOVIE_QUALITY       = LV_PLUGIN_IMG_ID_ICON_QUALITY,
	IDI_MOVIE_WB            = LV_PLUGIN_IMG_ID_ICON_WB_AUTO,
	IDI_MOVIE               = LV_PLUGIN_RES_ID_NONE,       // Movie menu enable icon
	IDIX_MOVIE              = LV_PLUGIN_RES_ID_NONE,      // Movie menu disable icon
	IDI_MOVIE_DUAL_CAM      = LV_PLUGIN_IMG_ID_ICON_DUALCAM_BOTH_M,
	IDI_MOVIE_CODEC         = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,

	// Playback Page
	IDI_PROTECT             = LV_PLUGIN_IMG_ID_ICON_PROTECT_M,
	IDI_VOLUME              = LV_PLUGIN_IMG_ID_ICON_VOICE_M,
	IDI_PLAYBACK            = LV_PLUGIN_RES_ID_NONE,    // Playback menu enable icon
	IDIX_PLAYBACK           = LV_PLUGIN_RES_ID_NONE,   // Playback menu disable icon

	// Common Page
	IDI_COMMON              = LV_PLUGIN_IMG_ID_ICON_MENU_MODECHANG_M,
	IDI_COMMON_MODE         = LV_PLUGIN_IMG_ID_ICON_MENU_MODECHANG_M,                // no menu icon
	IDI_COMMON_MENU         = LV_PLUGIN_IMG_ID_ICON_MODE_VIDEO_M,
	IDI_COMMON_LOCAL        = LV_PLUGIN_IMG_ID_ICON_WIFI_OFF_M,
	IDI_COMMON_LIVESTREAM   = LV_PLUGIN_IMG_ID_ICON_WIFI_ON,
	IDI_COMMON_CLOUD        = LV_PLUGIN_IMG_ID_ICON_CLOUD_OFF_M,
	IDI_COMMON_SETUP        = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDI_COMMON_EXT_SETUP    = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDIX_COMMON             = LV_PLUGIN_IMG_ID_ICON_MODE_VIDEO,

	// Mode page
	IDI_MODE                = LV_PLUGIN_IMG_ID_ICON_MODE_VIDEO_M,
	IDI_MODE_MOVIE          = LV_PLUGIN_IMG_ID_ICON_MODE_VIDEO_M,
	IDI_MODE_PHOTO          = LV_PLUGIN_IMG_ID_ICON_MODE_CAPTURE_M,
	IDI_MODE_PLAYBACK       = LV_PLUGIN_IMG_ID_ICON_MODE_PLAYBACK_M,
	IDIX_MODE               = LV_PLUGIN_IMG_ID_ICON_MODE_VIDEO,
	// Setup Page
	IDI_DATE_TIME           = LV_PLUGIN_IMG_ID_ICON_DATETIME_SETUP_M,
	IDI_AUTO_POWER_OFF      = LV_PLUGIN_IMG_ID_ICON_POWER_OFF_M,
	IDI_BEEP                = LV_PLUGIN_IMG_ID_ICON_VOICE_M,
	IDI_LANGUAGE            = LV_PLUGIN_IMG_ID_ICON_LANGUAGE_M,
	IDI_FREQUENCY           = LV_PLUGIN_IMG_ID_ICON_HZ_M,
	IDI_TV_MODE             = LV_PLUGIN_IMG_ID_ICON_TV_MODE_M,
	IDI_FORMAT              = LV_PLUGIN_IMG_ID_ICON_FORMAT_M,
	IDI_DEFAULT             = LV_PLUGIN_IMG_ID_ICON_DEFAULT_M,
	IDI_WIFI                = LV_PLUGIN_IMG_ID_ICON_WIFI_ON_M,
	IDI_VERSION             = LV_PLUGIN_IMG_ID_ICON_VERSION_M,
	IDI_SCREEN_SAVE         = LV_PLUGIN_IMG_ID_ICON_SCREENSAVER_M,
	IDI_FW_UPDATE           = LV_PLUGIN_IMG_ID_ICON_FIRMWARE_UPDATE_M,
	IDI_DELETE_ALL          = LV_PLUGIN_IMG_ID_ICON_DELETE_M,
	IDI_PROTECT_ALL         = LV_PLUGIN_IMG_ID_ICON_LOCK_M,
	IDI_UNPROTECT_ALL       = LV_PLUGIN_IMG_ID_ICON_LOCK_UNLOCK_M,
	IDI_SETUP               = LV_PLUGIN_RES_ID_NONE,
	IDIX_SETUP              = LV_PLUGIN_RES_ID_NONE,

	// Extra Setup Page
	IDI_MCTF                = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDI_EDGE                = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDI_NR                  = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDI_IPP_ISO             = LV_PLUGIN_IMG_ID_ICON_MENU_SETUP_ON_M,
	IDI_EXT_SETUP           = LV_PLUGIN_RES_ID_NONE,
	IDIX_EXT_SETUP          = LV_PLUGIN_RES_ID_NONE,

#if 0
	// Language Options
	IDI_LANG_EN             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_FR             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_ES             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_PO             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_DE             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_DU             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_IT             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_RU             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_TU             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_JP             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_TC             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_SC             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_PB             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_YI             = LV_PLUGIN_IMG_ID_ICON_OK,
	IDI_LANG_PL             = LV_PLUGIN_IMG_ID_ICON_OK
#endif
};
// Menu Flag ID
enum _MENU_IDF {
	// Menu common page
	IDF_COMMON_MODE                      = FL_COMMON_MODE,
	IDF_COMMON_MENU                      = FL_COMMON_MENU,
	IDF_COMMON_LOCAL                     = FL_COMMON_LOCAL,
	IDF_COMMON_LIVESTREAM                = FL_COMMON_LIVESTREAM,
	IDF_COMMON_CLOUD                     = FL_COMMON_CLOUD,
	IDF_COMMON_SETUP                     = FL_COMMON_SETUP,
	IDF_COMMON_EXT_SETUP                 = FL_COMMON_EXT_SETUP,
	// Movie Page
	IDF_MOVIE_SIZE                       = FL_MOVIE_SIZE_MENU, //only keep in menu
	IDF_MOVIE_CYCLIC_REC                 = FL_MOVIE_CYCLIC_REC,
	IDF_MOVIE_HDR                        = FL_MOVIE_HDR_MENU,
	IDF_MOVIE_WDR                        = FL_MOVIE_WDR_MENU,
	IDF_MOVIE_MOTION_DET                 = FL_MOVIE_MOTION_DET,
	IDF_MOVIE_AUDIO                      = FL_MOVIE_AUDIO,
	IDF_MOVIE_DATEIMPRINT                = FL_MOVIE_DATEIMPRINT,
	IDF_MOVIE_RSC                        = FL_MovieRSCIndex_MENU,
	IDF_MOVIE_RSC_EFFECT                 = FL_MovieRSCEffect_MENU,
	IDF_MOVIE_GSENSOR                    = FL_GSENSOR,
	//#NT#2016/08/15#KCHong#[0106941] -begin
	//#NT#Fixed FCW/LDWS/Timelapse cannot reset to default
	IDF_MOVIE_TIMELAPSE_REC              = FL_MOVIE_TIMELAPSE_REC_MENU,
	//#NT#2016/08/15#KCHong -end
	IDF_MOVIE_IR_CUT                     = FL_MOVIE_IR_CUT,
	IDF_MOVIE_SENSOR_ROTATE              = FL_MOVIE_SENSOR_ROTATE_MENU,//FL_MOVIE_SENSOR_ROTATE,
	IDF_MOVIE_PTZ                        = FL_MOVIE_PTZ,
	IDF_MOVIE_URGENT_PROTECT_AUTO        = FL_MOVIE_URGENT_PROTECT_AUTO,
	IDF_MOVIE_URGENT_PROTECT_MANUAL      = FL_MOVIE_URGENT_PROTECT_MANUAL,
	IDF_MOVIE_PIM                        = FL_MOVIE_PIM,
	//#NT#2016/08/15#KCHong#[0106941] -begin
	//#NT#Fixed FCW/LDWS/Timelapse cannot reset to default
	IDF_MOVIE_LDWS                       = FL_MOVIE_LDWS_MENU,
	IDF_MOVIE_FCW                        = FL_MOVIE_FCW_MENU,
	//#NT#2016/08/15#KCHong -end
	IDF_MOVIE_DDD                        = FL_MOVIE_DDD,
	IDF_MOVIE_ADAS_CAL                   = FL_MOVIE_ADAS_CAL,
	IDF_MOVIE_DUAL_CAM                   = FL_DUAL_CAM_MENU,
	IDF_MOVIE_CODEC                      = FL_MOVIE_CODEC_MENU,
	// Photo Page
	IDF_SELFTIMER                        = FL_SELFTIMER,
	IDF_PHOTO_SIZE                       = FL_PHOTO_SIZE,
	IDF_CONTINUE_SHOT                    = FL_CONTINUE_SHOT,
	IDF_QUALITY                          = FL_QUALITY,
	IDF_SHARPNESS                        = FL_SHARPNESS,
	IDF_WB                               = FL_WB,
	IDF_ANTISHAKE                        = FL_ANTISHAKE,
	IDF_QUICK_REVIEW                     = FL_QUICK_REVIEW,
	IDF_DATE_STAMP                       = FL_DATE_STAMP,
	IDF_ISO                              = FL_ISO,
	IDF_EV                               = FL_EV,
	IDF_FD                               = FL_FD,
	IDF_FLASH                            = FL_FLASH_MODE,
	//#NT#2016/08/19#Lincy Lin#[0106935] -begin
	//#NT# Support change WDR, SHDR, RSC setting will change mode after exit menu
	IDF_RSC                              = FL_RSC_MENU,
	IDF_HDR                              = FL_SHDR_MENU,
	IDF_WDR                              = FL_WDR_MENU,
	//#NT#2016/08/19#Lincy Lin -end
	IDF_METERING                         = FL_METERING,
	IDF_SCENE                            = FL_SCENE,
	IDF_DUAL_CAM                         = FL_DUAL_CAM_MENU,
	// Playback page
	IDF_VOLUME                           = FL_MovieAudioPlayIndex,
	// Setup Page
	IDF_AUTO_POWER_OFF                   = FL_AUTO_POWER_OFF,
	IDF_BEEP                             = FL_BEEP,
	IDF_LANGUAGE                         = FL_LANGUAGE,
	IDF_FREQUENCY                        = FL_FREQUENCY,
	IDF_TV_MODE                          = FL_TV_MODE,
	IDF_SCREEN_SAVE                      = FL_LCD_OFF,
	// Extra Setup Page
	IDF_MCTF                             = FL_MovieMCTFIndex,
	IDF_EDGE                             = FL_EDGE,
	IDF_NR                               = FL_NR,
	IDF_IPP_ISO                          = FL_IPP_ISO,

};

#endif // __MENUID_H

