#!/bin/sh
KERVER=`cat /proc/version | awk -F'version ' '{print $2}' | awk -F' ' '{print $1}'`

# Setup mdev
echo "fs" > /proc/nvt_info/bootts
#if [ "$EMBMEM" != "EMBMEM_EMMC" ]; then
#These are moved to S10_SysInit2, because it will be affected if this action is later than nvt_vpe or nvt_eis.
#The device node "mmcblk0" can't appear.
#insmod /lib/modules/$KERVER/kernel/drivers/mmc/core/mmc_core.ko
#insmod /lib/modules/$KERVER/kernel/drivers/mmc/core/mmc_block.ko
#insmod /lib/modules/$KERVER/kernel/drivers/mmc/host/mmc_na51055.ko
#fi
#insmod /lib/modules/$KERVER/kernel/fs/fat/fat.ko
#insmod /lib/modules/$KERVER/kernel/fs/fat/vfat.ko
#INDEX=1
#while [ $INDEX -le 10 ]
#do
#	if [ -d "/sys/class/block/mmcblk0" ]; then
#		mknod /dev/mmcblk0 b `cat /sys/class/block/mmcblk0/dev | sed "s/:/\ /g"`		
#		sleep 0.001
#		if [ -d "/sys/class/block/mmcblk0p1" ]; then
#			mknod /dev/mmcblk0p1 b `cat /sys/class/block/mmcblk0p1/dev | sed "s/:/\ /g"`
#			mount -t vfat /dev/mmcblk0p1 /mnt/sd
#		else
#			mount -t vfat /dev/mmcblk0 /mnt/sd
#		fi
#		break
#	fi
#	sleep 0.001
#	INDEX=$(( INDEX+1 ))
#done
echo "fs" > /proc/nvt_info/bootts
