//This source code is generated by UI Designer Studio.
#include "PrjInc.h"  //tmp define for compile,should remove

#include "UIWnd/UIFlow.h"
#include "UIApp/Play/UIPlayComm.h"
#include "MenuCommonConfirmRes.c"
#include "MenuCommonConfirm.h"
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIMenuCommonConfirm
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>
//---------------------MenuCommonConfirmCtrl Debug Definition -----------------------------
#define _MENUCOMMONCONFIRM_ERROR_MSG        1
#define _MENUCOMMONCONFIRM_TRACE_MSG        1

#if (_MENUCOMMONCONFIRM_ERROR_MSG)
#define MenuCommonConfirmErrMsg(...)            printf ("^R MenuCommonConfirm: "__VA_ARGS__)
#else
#define MenuCommonConfirmErrMsg(...)
#endif

#if (_MENUCOMMONCONFIRM_TRACE_MSG)
#define MenuCommonConfirmTraceMsg(...)          printf ("^B MenuCommonConfirm: "__VA_ARGS__)
#else
#define MenuCommonConfirmTraceMsg(...)
#endif

//---------------------MenuCommonConfirmCtrl Global Variables -----------------------------

//---------------------MenuCommonConfirmCtrl Prototype Declaration  -----------------------
static UINT32 gBKGEvt = 0;
static UINT32 gExeEvt = 0;
static UINT32 gItemID = 0;
//---------------------MenuCommonConfirmCtrl Public API  ----------------------------------

//---------------------MenuCommonConfirmCtrl Private API  ---------------------------------
//---------------------MenuCommonConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonConfirm)
CTRL_LIST_ITEM(MenuCommonConfirm_List)
CTRL_LIST_ITEM(MenuCommonConfirm_Title)
CTRL_LIST_ITEM(MenuCommConfirm_Panel)
CTRL_LIST_ITEM(MenuCommonConfirm_BTN_Yes)
CTRL_LIST_ITEM(MenuCommonConfirm_BTN_No)
CTRL_LIST_END

//----------------------MenuCommonConfirmCtrl Event---------------------------
INT32 MenuCommonConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_OnTouchPanelSlideUp(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, MenuCommonConfirm_OnStorageChange)
EVENT_ITEM(NVTEVT_SLIDE_UP,MenuCommonConfirm_OnTouchPanelSlideUp)
EVENT_END

INT32 MenuCommonConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("(paramNum=%d)\r\n",paramNum);
	UINT32 strID = 0;
	gBKGEvt = 0;
	gExeEvt = 0;
	if (paramNum == 1) {
		gItemID = paramArray[0];

		switch (gItemID) {
		case IDM_FORMAT:
			strID = STRID_DELETE_WARNING;
			gBKGEvt = NVTEVT_BKW_FORMAT_CARD;
			break;
		case IDM_DEFAULT:
			strID = STRID_RESET_WARNING;
			gExeEvt = NVTEVT_EXE_SYSRESET_NO_WIN;
			break;
		case IDM_FW_UPDATE:
			strID = STRID_FW_UPDATE;
			gBKGEvt = NVTEVT_BKW_FW_UPDATE;
			break;
		case IDM_DELETE_ALL:
			strID = STRID_ERASE_ALL;
			gBKGEvt = NVTEVT_BKW_DELALL;
			break;
		case IDM_PROTECT_ALL:
			strID = STRID_LOCKALL;
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ALL);
			gBKGEvt = NVTEVT_BKW_SETPROTECT;
			break;
		case IDM_UNPROTECT_ALL:
			strID = STRID_UNLOCKALL;
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ALL);
			gBKGEvt = NVTEVT_BKW_SETPROTECT;
			break;
		case IDM_PROTECT:
			strID = STRID_LOCKONE;
			AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_PROTECT_ONE);
			gBKGEvt = NVTEVT_BKW_SETPROTECT;
			break;
		case IDM_DELETE_THIS:
			strID = STRID_ERASE_THIS;
			break;
		default:
			gBKGEvt = 0;
			MenuCommonConfirmErrMsg("error itemID %d\r\n", gItemID);
		}
        DBG_FUNC("gItemID=%d, gBKGEvt=%d\r\n",gItemID,gBKGEvt);
	}

	if (gItemID == IDM_PROTECT) {
        DBG_FUNC("IDM_PROTECT>>\r\n");
        UxButton_SetItemData(&MenuCommonConfirm_BTN_YesCtrl, 0, BTNITM_ICONID, ICON_LOCK_M);
        UxButton_SetItemData(&MenuCommonConfirm_BTN_NoCtrl, 0, BTNITM_ICONID, ICON_LOCK_UNLOCK_M);
		//UxList_SetItemData(&MenuCommonConfirm_ListCtrl, 0, LSTITM_ICONID, ICON_LOCK_M);
		//UxList_SetItemData(&MenuCommonConfirm_ListCtrl, 1, LSTITM_ICONID, ICON_LOCK_UNLOCK_M);
        DBG_FUNC("IDM_PROTECT<<\r\n");
	} else {
	    DBG_FUNC("IDM_OKNO>>\r\n");
        UxButton_SetItemData(&MenuCommonConfirm_BTN_YesCtrl, 0, BTNITM_ICONID, ICON_OK_M);
        UxButton_SetItemData(&MenuCommonConfirm_BTN_NoCtrl, 0, BTNITM_ICONID, ICON_NO_M);
		//UxList_SetItemData(&MenuCommonConfirm_ListCtrl, 0, LSTITM_ICONID, ICON_OK_M);
		//UxList_SetItemData(&MenuCommonConfirm_ListCtrl, 1, LSTITM_ICONID, ICON_NO_M);
        DBG_FUNC("IDM_OKNO<<\r\n");
	}
	UxStatic_SetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE, strID);
	UxList_SetData(&MenuCommonConfirm_ListCtrl, LST_CURITM, MenuCommonConfirm_List_ICON_OK_M);
	UI_SetDisplayPalette(LAYER_OSD1, 0, 256, gDemoKit_PaletteConfirm_Palette);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    DBG_FUNC_END("\r\n");
    return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("\r\n");
	UI_SetDisplayPalette(LAYER_OSD1, 0, 256, gDemoKit_PaletteOption_Palette);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    DBG_FUNC_BEGIN("\r\n");
    return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("\r\n");
    #if 1
	if (((paramNum == 2) && (paramArray[0] == NVTRET_WAITMOMENT)) || (STRID_ERASE_THIS == UxStatic_GetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE))) {
		Ux_CloseWindow(pCtrl, 0);
	}
    #else
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    #endif
    DBG_FUNC("\r\n");
	return NVTEVT_CONSUME;
}

INT32 MenuCommonConfirm_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
        DBG_FUNC_BEGIN("\r\n");
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
        DBG_FUNC_END("\r\n");
	return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_OnTouchPanelSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(pCtrl,0);
    return NVTEVT_CONSUME;
}
//----------------------MenuCommonConfirm_ListCtrl Event---------------------------
INT32 MenuCommonConfirm_List_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_List_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_List_OnKeySelect(VControl *, UINT32, UINT32 *);
INT32 MenuCommonConfirm_List_OnKeyExit(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm_List)
EVENT_ITEM(NVTEVT_KEY_NEXT, MenuCommonConfirm_List_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_PREV, MenuCommonConfirm_List_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_SELECT, MenuCommonConfirm_List_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, MenuCommonConfirm_List_OnKeyExit)
EVENT_END

INT32 MenuCommonConfirm_List_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("\r\n");
#if 1
	if ((paramNum == 1) && paramArray[0] == NVTEVT_KEY_PRESS) {
		Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);

		if (UxList_GetData(&MenuCommonConfirm_ListCtrl, LST_CURITM) == MenuCommonConfirm_List_ICON_OK_M) {
			Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
		}
	}
#else
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
#endif
    DBG_FUNC_END("\r\n");
    return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_List_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("\r\n");
	if ((paramNum == 1) && paramArray[0] == NVTEVT_KEY_PRESS) {
		Ux_SendEvent(pCtrl, NVTEVT_PREVIOUS_ITEM, 0);

		if (UxList_GetData(&MenuCommonConfirm_ListCtrl, LST_CURITM) == MenuCommonConfirm_List_ICON_NO_M) {
			Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
		}
	}
    DBG_FUNC_END("\r\n");
	return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_List_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_FUNC_BEGIN("\r\n");
	if ((paramNum == 1) && paramArray[0] == NVTEVT_KEY_PRESS) {
		if (UxList_GetData(&MenuCommonConfirm_ListCtrl, LST_CURITM) == MenuCommonConfirm_List_ICON_OK_M) {
			if (STRID_ERASE_THIS == UxStatic_GetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE)) {
                #if(PLAY_MODE)
				UINT32 uiLockStatus;
				PB_GetParam(PBPRMID_FILE_ATTR_LOCK, &uiLockStatus);
				if (uiLockStatus) {
					Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_FILE_PROTECTED, FLOWWRNMSG_TIMER_1SEC);
					return NVTEVT_CONSUME;
				}
				UIPlay_Delete(PB_DELETE_ONE);
				UIPlay_PlaySingle(PB_SINGLE_CURR);
                #endif
				Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
			} else if (gBKGEvt) {
			    DBG_FUNC("gBKGEvt=%d\r\n",gBKGEvt);
				Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
				BKG_PostEvent(gBKGEvt);
			} else {
			    DBG_FUNC("gBKGEvt==>0 and call Ux_SendEvent(gExeEvt=%d)\r\n",gExeEvt);
				Ux_SendEvent(&UISetupObjCtrl, gExeEvt, 0);
				Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
			}
		} else {
			if (gItemID == IDM_PROTECT) {
                DBG_FUNC("gItemID == IDM_PROTECT\r\n");
				AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ONE);
				Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
				BKG_PostEvent(gBKGEvt);
			} else {
			    DBG_FUNC("gItemID != IDM_PROTECT\r\n");
				Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
			}
		}
	}
    DBG_FUNC_END("\r\n");
    return NVTEVT_CONSUME;
}
INT32 MenuCommonConfirm_List_OnKeyExit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0);
	return NVTEVT_CONSUME;
}
//----------------------MenuCommonConfirm_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_Title)
EVENT_END

//---------------------MenuCommConfirm_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommConfirm_Panel)
CTRL_LIST_ITEM(MenuCommonConfirm_Left)
CTRL_LIST_ITEM(MenuCommonConfirm_Right)
CTRL_LIST_ITEM(MenuCommonConfirm_LeftIcon)
CTRL_LIST_ITEM(MenuCommonConfirm_RightIcon)
CTRL_LIST_END

//----------------------MenuCommConfirm_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommConfirm_Panel)
EVENT_END

//----------------------MenuCommonConfirm_LeftCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_Left)
EVENT_END

//----------------------MenuCommonConfirm_RightCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_Right)
EVENT_END

//----------------------MenuCommonConfirm_LeftIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_LeftIcon)
EVENT_END

//----------------------MenuCommonConfirm_RightIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonConfirm_RightIcon)
EVENT_END

//----------------------MenuCommonConfirm_BTN_YesCtrl Event---------------------------
INT32 MenuCommonConfirm_BTN_Yes_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm_BTN_Yes)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonConfirm_BTN_Yes_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonConfirm_BTN_Yes_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (STRID_ERASE_THIS == UxStatic_GetData(&MenuCommonConfirm_TitleCtrl, STATIC_VALUE))
    {
        UINT32 uiLockStatus;
        PB_GetParam(PBPRMID_FILE_ATTR_LOCK, &uiLockStatus);
        if(uiLockStatus)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_FILE_PROTECTED, FLOWWRNMSG_TIMER_1SEC);
            return NVTEVT_CONSUME;
        }
        UIPlay_Delete(PB_DELETE_ONE);
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
    }
    else if(gBKGEvt)
    {
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
        BKG_PostEvent(gBKGEvt);
    }
    else
    {
        Ux_SendEvent(&UISetupObjCtrl,gExeEvt, 0);
        Ux_CloseWindow(&MenuCommonConfirmCtrl, 0);
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonConfirm_BTN_NoCtrl Event---------------------------
INT32 MenuCommonConfirm_BTN_No_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonConfirm_BTN_No)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonConfirm_BTN_No_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonConfirm_BTN_No_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (gItemID == IDM_PROTECT)
    {
        AppBKW_SetData(BKW_PROTECT_TYPE, SETUP_UNPROTECT_ONE);
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
        BKG_PostEvent(gBKGEvt);
    }
    else
    {
        Ux_CloseWindow(&MenuCommonConfirmCtrl,0);
    }
    return NVTEVT_CONSUME;
}
