//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIWnd/UIFlow.h"

extern VControl MenuCommonOptionCtrl;//Panel type 

extern VControl MenuCommonOption_ListCtrl;//List type 

typedef enum
{
MenuCommonOption_List_ICON_MODE_CAPTURE_M,
MenuCommonOption_List_ICON_CLOUD_ON_M,
MenuCommonOption_List_ICON_WIFI_ON_M,
MenuCommonOption_List_ICON_WIFI_OFF_M,
MenuCommonOption_List_MAX
}MenuCommonOption_List_Setting;

extern VControl MenuCommonOption_TitleCtrl;//Menu type 

typedef enum
{
MenuCommonOption_Title_STRID_WIFI,
MenuCommonOption_Title_MAX
}MenuCommonOption_Title_Setting;

extern VControl MenuCommonOption_StatusCtrl;//Menu type 

typedef enum
{
MenuCommonOption_Status_STRID_WIFI_OFF,
MenuCommonOption_Status_MAX
}MenuCommonOption_Status_Setting;

extern VControl MenuCommOption_PanelCtrl;//Panel type 

extern VControl MenuCommonOption_LeftCtrl;//Static type 

extern VControl MenuCommonOption_RightCtrl;//Static type 

extern VControl MenuCommonOption_LeftIconCtrl;//Static type 

extern VControl MenuCommonOption_RightIconCtrl;//Static type 

extern VControl MenuCommonOption_STA_TitleCtrl;//Static type 

extern VControl MenuCommonOption_PNLCtrl;//Panel type 

extern VControl MenuCommonOption_MNU_SelectionCtrl;//Menu type 

typedef enum
{
MenuCommonOption_MNU_Selection_STRID_A0,
MenuCommonOption_MNU_Selection_STRID_A1,
MenuCommonOption_MNU_Selection_STRID_A2,
MenuCommonOption_MNU_Selection_STRID_A3,
MenuCommonOption_MNU_Selection_STRID_A4,
MenuCommonOption_MNU_Selection_STRID_A5,
MenuCommonOption_MNU_Selection_STRID_A6,
MenuCommonOption_MNU_Selection_STRID_A7,
MenuCommonOption_MNU_Selection_STRID_A8,
MenuCommonOption_MNU_Selection_STRID_A9,
MenuCommonOption_MNU_Selection_STRID_B0,
MenuCommonOption_MNU_Selection_STRID_B1,
MenuCommonOption_MNU_Selection_STRID_B2,
MenuCommonOption_MNU_Selection_STRID_B3,
MenuCommonOption_MNU_Selection_STRID_B4,
MenuCommonOption_MNU_Selection_STRID_B5,
MenuCommonOption_MNU_Selection_STRID_B6,
MenuCommonOption_MNU_Selection_STRID_B7,
MenuCommonOption_MNU_Selection_STRID_B8,
MenuCommonOption_MNU_Selection_STRID_B9,
MenuCommonOption_MNU_Selection_MAX
}MenuCommonOption_MNU_Selection_Setting;

extern VControl MenuCommonOption_BTN_OKCtrl;//Button type 

extern VControl MenuCommonOption_BTN_CancelCtrl;//Button type 

//---------------------MenuCommonOptionCtrl User Export---------------------------
#endif
