//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIWnd/UIFlow.h"

extern VControl MenuCommonItemCtrl;//Panel type 

extern VControl MenuCommonItem_ListCtrl;//List type 

typedef enum
{
MenuCommonItem_List_ICON_MODE_CAPTURE_M,
MenuCommonItem_List_ICON_CLOUD_ON_M,
MenuCommonItem_List_ICON_WIFI_ON_M,
MenuCommonItem_List_ICON_WIFI_OFF_M,
MenuCommonItem_List_MAX
}MenuCommonItem_List_Setting;

extern VControl MenuCommonItem_TitleCtrl;//Menu type 

typedef enum
{
MenuCommonItem_Title_STRID_WIFI,
MenuCommonItem_Title_MAX
}MenuCommonItem_Title_Setting;

extern VControl MenuCommonItem_StatusCtrl;//Menu type 

typedef enum
{
MenuCommonItem_Status_STRID_WIFI_OFF,
MenuCommonItem_Status_MAX
}MenuCommonItem_Status_Setting;

extern VControl MenuCommItem_PanelCtrl;//Panel type 

extern VControl MenuCommonItem_LeftCtrl;//Static type 

extern VControl MenuCommonItem_RightCtrl;//Static type 

extern VControl MenuCommonItem_LeftIconCtrl;//Static type 

extern VControl MenuCommonItem_RightIconCtrl;//Static type 

extern VControl MenuCommonItem_ItemSelectCtrl;//Menu type 

typedef enum
{
MenuCommonItem_ItemSelect_STRID_MODE,
MenuCommonItem_ItemSelect_STRID_NULL_,
MenuCommonItem_ItemSelect_MAX
}MenuCommonItem_ItemSelect_Setting;

extern VControl MenuCommonItem_Point0Ctrl;//Panel type 

extern VControl MenuCommonItem_Point1Ctrl;//Panel type 

extern VControl MenuCommonItem_Point2Ctrl;//Panel type 

extern VControl MenuCommonItem_Point3Ctrl;//Panel type 

extern VControl MenuCommonItem_Point4Ctrl;//Panel type 

extern VControl MenuCommonItem_BTN0Ctrl;//Button type 

extern VControl MenuCommonItem_BTN1Ctrl;//Button type 

extern VControl MenuCommonItem_BTN2Ctrl;//Button type 

extern VControl MenuCommonItem_BTN3Ctrl;//Button type 

extern VControl MenuCommonItem_BTN4Ctrl;//Button type 

extern VControl MenuCommonItem_BTN5Ctrl;//Button type 

extern VControl MenuCommonItem_BTN6Ctrl;//Button type 

extern VControl MenuCommonItem_BTN7Ctrl;//Button type 

extern VControl MenuCommonItem_BTN8Ctrl;//Button type 

extern VControl MenuCommonItem_BTN9Ctrl;//Button type 

extern VControl MenuCommonItem_BTN10Ctrl;//Button type 

extern VControl MenuCommonItem_BTN11Ctrl;//Button type 

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
