//This source code is generated by UI Designer Studio.
#include "PrjInc.h"  //tmp define for compile,should remove

#include "UIWnd/UIFlow.h"
#include "MenuCommonItemRes.c"
#include "MenuCommonItem.h"

#include <kwrap/debug.h>
#include "UIApp/Network/UIAppNetwork.h"

//extern UINT32 System_GetEnableSensor(void);

//---------------------MenuCommonItemCtrl Debug Definition -----------------------------
#define _MENUCOMMONITEM_ERROR_MSG        0
#define _MENUCOMMONITEM_TRACE_MSG        0

#if (_MENUCOMMONITEM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonItemErrMsg(...)            debug_msg ("^R MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemErrMsg(...)
#endif

#if (_MENUCOMMONITEM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonItemTraceMsg(...)          debug_msg ("^B MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemTraceMsg(...)
#endif

//---------------------MenuCommonItemCtrl Global Variables -----------------------------
#define PAGE           4
#if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
TM_MENU*    g_pMenu=NULL;


#define ITEMS_PER_PAGE          4
#define MAX_SUPPORTED_PAGE      5                                       // It is according to the page indicator point

#define SEARCH_PREV_PAGE        0
#define SEARCH_NEXT_PAGE        1

#define TITLE_UPPER_LEFT_X    420// 10
#define TITLE_UPPER_LEFT_Y      40//5
#define TITLE_WIDTH           100//300
#define TILE_HEIGHT            50//28

static INT32  g_TouchPressX;
static INT32  g_TouchPressY;
static INT32  g_PanelOffset;
static INT32  g_MenuMoved;
static INT32  g_TotalItemCount;
static INT32  g_PageItemIndex[MAX_SUPPORTED_PAGE][ITEMS_PER_PAGE];      // Store the enabled item index
static INT32  g_PageCurrent;

//static TM_MENU* g_pTouchItemMenu = 0;

VControl* MenuCommonItem_PrevGroup[ITEMS_PER_PAGE]=
{
    &MenuCommonItem_BTN0Ctrl,
    &MenuCommonItem_BTN1Ctrl,
    &MenuCommonItem_BTN2Ctrl,
    &MenuCommonItem_BTN3Ctrl
};

VControl* MenuCommonItem_CurrGroup[ITEMS_PER_PAGE]=
{
    &MenuCommonItem_BTN4Ctrl,
    &MenuCommonItem_BTN5Ctrl,
    &MenuCommonItem_BTN6Ctrl,
    &MenuCommonItem_BTN7Ctrl
};

VControl* MenuCommonItem_NextGroup[ITEMS_PER_PAGE]=
{
    &MenuCommonItem_BTN8Ctrl,
    &MenuCommonItem_BTN9Ctrl,
    &MenuCommonItem_BTN10Ctrl,
    &MenuCommonItem_BTN11Ctrl
};

VControl* MenuCommonItem_Indicator[MAX_SUPPORTED_PAGE]=
{
    &MenuCommonItem_Point0Ctrl,
    &MenuCommonItem_Point1Ctrl,
    &MenuCommonItem_Point2Ctrl,
    &MenuCommonItem_Point3Ctrl,
    &MenuCommonItem_Point4Ctrl,
};
#endif
//---------------------MenuCommonItemCtrl Prototype Declaration  -----------------------
#if (1)//defined(_KEY_METHOD_4KEY_)
#define MENU_KEY_PRESS_MASK        (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#else
#define MENU_KEY_PRESS_MASK        (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_LEFT|FLGKEY_RIGHT)
#endif
//---------------------MenuCommonItemCtrl Public API  ----------------------------------

//---------------------MenuCommonItemCtrl Private API  ---------------------------------
static TM_MENU *g_pItemMenu = 0;

static void MenuCommonItem_SetCurrentMenu(TM_MENU *pMenu)
{
	g_pItemMenu = pMenu;
}
static TM_MENU *MenuCommonItem_GetCurrentMenu(void)
{
	return g_pItemMenu;
}
#if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
static INT32 MenuCommonItem_UpdateIndex(TM_MENU* pMenu)
{
    INT32 i = 0, index = 0, *pIdx;
    TM_PAGE* pPage;

    pIdx = (INT32*)g_PageItemIndex;

    // Initialize all components of g_PageItemIndex to -1. -1 means no valid item.
    for(i = 0; i < MAX_SUPPORTED_PAGE * ITEMS_PER_PAGE; i ++) {
        pIdx[i] = -1;
    }

    i = 0;
    pPage = &pMenu->pPages[0];

    // Scan all the items and store the enabled items to g_PageItemIndex
    while (index < pPage->Count) {
        if(((&pPage->pItems[index])->Status & TM_ITEM_STATUS_MASK) == TM_ITEM_ENABLE) {
            pIdx[i] = index;
            i++;
            if (i >= MAX_SUPPORTED_PAGE * ITEMS_PER_PAGE) {
                break;
            }
        }
        index ++;
    }
    // The return value means total active items.
    return i;
}

static INT32 MenuCommonItem_FindDispPage(INT32 CurrentPage, UINT32 action)
{
    INT32 index;

    index = CurrentPage;

    // Protection, it mean no valid items in g_PageItemIndex.
    if (g_PageItemIndex[index][0] == -1)
        return index;

    // Find previous valid page
    if (action == SEARCH_PREV_PAGE) {
        do {
            if (index) {
                index --;
            } else {
                index = MAX_SUPPORTED_PAGE - 1;
            }
        } while (g_PageItemIndex[index][0] == -1);
    } else if (action == SEARCH_NEXT_PAGE) {// Find next valid page
        do {
        	index = (index + 1) % MAX_SUPPORTED_PAGE;
        } while (g_PageItemIndex[index][0] == -1);
    }
    return index;
}
#endif
static void MenuCommonItem_UpdateContent(TM_MENU *pMenu)
{
    #if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    INT32       i, index;

    pPage = &pMenu->pPages[pMenu->SelPage];

    // Protection, it mean no valid items in g_PageItemIndex.
    if (g_PageItemIndex[g_PageCurrent][0] ==  -1)
        return;

    // Update current display page
    for (i = 0; i < ITEMS_PER_PAGE; i ++) {
        if (g_PageItemIndex[g_PageCurrent][i] != -1) {
            pItem= &pPage->pItems[g_PageItemIndex[g_PageCurrent][i]];
            UxButton_SetItemData(MenuCommonItem_CurrGroup[i], 0, BTNITM_STRID, pItem->TextId);
            UxButton_SetItemData(MenuCommonItem_CurrGroup[i], 0, BTNITM_ICONID, pItem->IconId);
            UxCtrl_SetShow(MenuCommonItem_CurrGroup[i], TRUE);
        } else {
            UxCtrl_SetShow(MenuCommonItem_CurrGroup[i], FALSE);
        }
    }

    // Update prev display page
    index = MenuCommonItem_FindDispPage(g_PageCurrent, SEARCH_PREV_PAGE);

    for (i = 0; i < ITEMS_PER_PAGE; i ++) {
        if (g_PageItemIndex[index][i] != -1) {
            pItem= &pPage->pItems[g_PageItemIndex[index][i]];
            UxButton_SetItemData(MenuCommonItem_PrevGroup[i], 0, BTNITM_STRID, pItem->TextId);
            UxButton_SetItemData(MenuCommonItem_PrevGroup[i], 0, BTNITM_ICONID, pItem->IconId);
            UxCtrl_SetShow(MenuCommonItem_PrevGroup[i], TRUE);
        } else {
            UxCtrl_SetShow(MenuCommonItem_PrevGroup[i], FALSE);
        }
    }

    // Update next display page
    index = MenuCommonItem_FindDispPage(g_PageCurrent, SEARCH_NEXT_PAGE);

    for (i = 0; i < ITEMS_PER_PAGE; i ++) {
        if (g_PageItemIndex[index][i] != -1) {
            pItem= &pPage->pItems[g_PageItemIndex[index][i]];
            UxButton_SetItemData(MenuCommonItem_NextGroup[i], 0, BTNITM_STRID, pItem->TextId);
            UxButton_SetItemData(MenuCommonItem_NextGroup[i], 0, BTNITM_ICONID, pItem->IconId);
            UxCtrl_SetShow(MenuCommonItem_NextGroup[i], TRUE);
        } else {
            UxCtrl_SetShow(MenuCommonItem_NextGroup[i], FALSE);
        }
    }

    // Update title
    UxMenu_SetItemData(&MenuCommonItem_TitleCtrl, 0, MNUITM_STRID,  pPage->TextId);

    #else
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	UINT32      i;
	UINT16      startIndex = 0;
	UINT16      itemIndex = 0;

	pPage = &pMenu->pPages[pMenu->SelPage];
	pItem = &pPage->pItems[pPage->SelItem];
	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];

	if (pItem->Count) {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, TRUE);
		if (pOption->TextId & STRID_USER_START) {
			UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
		} else {
			UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);
		}
	} else if (pItem->ItemId == IDM_COMMON_MENU) {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, TRUE);
		UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  STRID_SETUP);
	} else {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, FALSE);
	}

	if (pItem->TextId & STRID_USER_START) {
		UxMenu_SetItemData(&MenuCommonItem_TitleCtrl, 0, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pItem->TextId)));
	} else {
		UxMenu_SetItemData(&MenuCommonItem_TitleCtrl, 0, MNUITM_STRID,  pItem->TextId);
	}
	//find startIndex
	TM_FindStartIndex(pMenu, PAGE, &startIndex);

	//draw item form startIndex
	itemIndex = startIndex;
	for (i = 0; i < PAGE; i++) {
		//check item if disable
		TM_CheckItemStatus(pMenu, &itemIndex, TRUE);
		if ((itemIndex == pPage->Count) && (i < PAGE)) {
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STATUS, STATUS_DISABLE);
		} else {
			pItem = &pPage->pItems[itemIndex];
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STATUS, STATUS_ENABLE);
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STRID,  pItem->TextId);
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_ICONID, pItem->IconId);
			itemIndex++;
		}
	}
    #endif
}
static void MenuCommonItem_UpdatePosition(void)
{
	ISIZE str_size;
	Ux_RECT MenuRect, NewRect;
	UINT32 strId = UxMenu_GetItemData(&MenuCommonItem_TitleCtrl, CURITEM_INDEX, MNUITM_STRID);

	//avoid other tmp UI change font table
	GxGfx_SetTextStroke((const FONT *)gDemoKit_Font, FONTSTYLE_NORMAL, SCALE_1X);

	if (strId & TEXT_POINTER) {
		strId = (strId) & ~TEXT_POINTER;
		GxGfx_TextPrint(0, 0, 0, "%s", strId);
	} else {
		GxGfx_Text(0, 0, 0, GxGfx_GetStringID(strId));
	}

	str_size = GxGfx_GetTextLastSize();
	UxCtrl_GetPos(&MenuCommonItem_TitleCtrl, &MenuRect);
	UxCtrl_GetPos(&MenuCommonItem_StatusCtrl, &NewRect);
	NewRect.x1 = MenuRect.x1 + str_size.w + 5;
	UxCtrl_SetPos(&MenuCommonItem_StatusCtrl, NewRect);
}
#if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
// Keep the title at same position even menu is sliding
void MenuCommonItem_DrawTitle(void)
{
    static Ux_RECT rect;
    static BOOL First_Open=TRUE;
    if(First_Open) {
        First_Open=FALSE;
        UxCtrl_GetPos(&MenuCommonItem_ItemSelectCtrl, &rect);
    }
    //rect.x1 = TITLE_UPPER_LEFT_X - g_PanelOffset;
    //rect.y1 = TITLE_UPPER_LEFT_Y;
    rect.x2 = rect.x1 + TITLE_WIDTH;
    rect.y2 = rect.y1 + TILE_HEIGHT;

    // UxCtrl_SetPos(&MenuCommonItem_TitleCtrl, rect);
    UxCtrl_SetPos(&MenuCommonItem_ItemSelectCtrl, rect);
    //UxCtrl_SetShow(&MenuCommonItem_ItemSelectCtrl, TRUE);
}

// Keep the indicator at same position even menu is sliding
void MenuCommonItem_DrawPoint(void)
{
    INT32 TotalPage;
    INT32 i;
    Ux_RECT rect;
    static BOOL First_Open=TRUE;
    static INT32 Rect_Size=0;
    if(First_Open) {
        First_Open=FALSE;
        UxCtrl_GetPos(MenuCommonItem_Indicator[0],&rect);
        Rect_Size=rect.x1-DISPLAY_OSD_W;
    }

    INT32 TopLeftX[MAX_SUPPORTED_PAGE][MAX_SUPPORTED_PAGE] = {
        //{{157,  -1,  -1,  -1,  -1},
        #if 0
        { -1,  -1,  -1,  -1,  -1},         // Do not show indicator if only one page
        {147, 167,  -1,  -1,  -1},
        {137, 157, 177,  -1,  -1},
        {127, 147, 167, 187,  -1},
        {117, 137, 157, 177, 197}
        #endif /* 0 */
        { -1,  -1,  -1,  -1,  -1},         // Do not show indicator if only one page
        { 30,  50,  -1,  -1,  -1},
        { 20,  40,  60,  -1,  -1},
        { 10,  30,  50,  70,  -1},
        {  0,  20,  40,  60,  80}
    };
    INT32 TopLeftY = 280;//220;
    INT32 IndicatorSize = 6;

    // Calculate how many indicator will be showed
    TotalPage = g_TotalItemCount / ITEMS_PER_PAGE;
    if (g_TotalItemCount % ITEMS_PER_PAGE) {
        TotalPage ++;
    }

    // The first indicator is highlighted, others are gray. So according to g_PageCurrent, swap the corresponding coordinate.
    i = TopLeftX[TotalPage - 1][g_PageCurrent];
    TopLeftX[TotalPage - 1][g_PageCurrent] = TopLeftX[TotalPage - 1][0];
    TopLeftX[TotalPage - 1][0] = i;
	
    // Set the position of each indicator and show status
    for (i = 0; i < MAX_SUPPORTED_PAGE; i ++) {
        if (TopLeftX[TotalPage - 1][i] == -1) {
            UxCtrl_SetShow(MenuCommonItem_Indicator[i], FALSE);
        } else {
            rect.x1 = TopLeftX[TotalPage - 1][i]+Rect_Size - g_PanelOffset;
            rect.y1 = TopLeftY;
            rect.x2 = rect.x1 + IndicatorSize;
            rect.y2 = rect.y1 + IndicatorSize;
            UxCtrl_SetPos(MenuCommonItem_Indicator[i], rect);
            UxCtrl_SetShow(MenuCommonItem_Indicator[i], TRUE);
        }
    }
}

static INT32 MenuCommonItem_SelectItem(TM_MENU* pMenu)
{
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;

    pPage = &pMenu->pPages[pMenu->SelPage];
    pItem = &pPage->pItems[pPage->SelItem];

    if (pItem->Count != 0 && pItem->SysFlag != 0) {
        Ux_OpenWindow(&MenuCommonOptionCtrl, 1, pMenu);
    } else if (pItem->ItemId == IDM_VERSION) {
        Ux_OpenWindow(&MenuCommonOptionCtrl, 1, pMenu);
    } else if (pItem->pOptions != 0)  {                 // custom process
        pMenu->Status = TMS_ON_CUSTOM;
        TM_ITEM_CALLBACK(pItem, TMM_CONFIRM_OPTION,pItem->ItemId);              // execute custom pPage flow
    }
    return NVTEVT_CONSUME;
}
static INT32 MenuCommonItem_SelectItem_Update(TM_MENU* pMenu1)
{
    TM_MENU*    pMenu;
    //TM_PAGE*    pPage;
    //TM_ITEM*    pItem;
    //TM_OPTION*  pOption;
    //TM_ITEM*    pModeItem;
    //INT32      curMode =0;


    // Step 1: Parsing target menu items
    MenuCommonItem_SetCurrentMenu(pMenu1);
    pMenu = MenuCommonItem_GetCurrentMenu();
    pMenu->Status = TMS_ON_OPTION;
    pMenu->SelPage = 0;
    g_PageCurrent = 0;
    g_TotalItemCount = MenuCommonItem_UpdateIndex(pMenu);

    // Step 2: Update content
    MenuCommonItem_UpdateContent(pMenu);
    // Step 3: Update position, always use 2nd display window to show active area.
    //      |--------------------------------|
    //      |   prev   |   curr   |   next   |
    //      |   page   |   page   |   page   |
    //      |--------------------------------|
    //                 |<-------->|
    //      slide right  display    slide left
    //
    #if 1
    Ux_RECT rect;
    rect.x1 = (-1) * DISPLAY_OSD_W;
    rect.y1 = 0;
    rect.x2 = rect.x1 + 3 * DISPLAY_OSD_W - 1;
    rect.y2 = DISPLAY_OSD_H - 1;
    g_PanelOffset = rect.x1;
    #endif /* 0 */
    g_MenuMoved = FALSE;
    #if 0
    static BOOL First_Open=TRUE;
    if(First_Open)
    {
        First_Open=FALSE;
        UxCtrl_GetPos((VControl *)&MenuCommonItemCtrl,(Ux_RECT*)&Menu_Item_rect);
    }
    UxCtrl_SetPos((VControl *)&MenuCommonItemCtrl, Menu_Item_rect);
    #endif /* 0 */
    UxCtrl_SetPos((VControl *)&MenuCommonItemCtrl, rect);
    // Step 4: Open window
    // Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
#endif
//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_List)
CTRL_LIST_ITEM(MenuCommonItem_Title)
CTRL_LIST_ITEM(MenuCommonItem_Status)
//CTRL_LIST_ITEM(MenuCommItem_Panel)
CTRL_LIST_ITEM(MenuCommonItem_ItemSelect)
CTRL_LIST_ITEM(MenuCommonItem_Point0)
CTRL_LIST_ITEM(MenuCommonItem_Point1)
CTRL_LIST_ITEM(MenuCommonItem_Point2)
CTRL_LIST_ITEM(MenuCommonItem_Point3)
CTRL_LIST_ITEM(MenuCommonItem_Point4)
CTRL_LIST_ITEM(MenuCommonItem_BTN0)
CTRL_LIST_ITEM(MenuCommonItem_BTN1)
CTRL_LIST_ITEM(MenuCommonItem_BTN2)
CTRL_LIST_ITEM(MenuCommonItem_BTN3)
CTRL_LIST_ITEM(MenuCommonItem_BTN4)
CTRL_LIST_ITEM(MenuCommonItem_BTN5)
CTRL_LIST_ITEM(MenuCommonItem_BTN6)
CTRL_LIST_ITEM(MenuCommonItem_BTN7)
CTRL_LIST_ITEM(MenuCommonItem_BTN8)
CTRL_LIST_ITEM(MenuCommonItem_BTN9)
CTRL_LIST_ITEM(MenuCommonItem_BTN10)
CTRL_LIST_ITEM(MenuCommonItem_BTN11)
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnTouchPanelSlideUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnTouchPanelSlideDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnRedraw(VControl *, UINT32, UINT32 *);
//INT32 MenuCommonItem_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, MenuCommonItem_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, MenuCommonItem_OnChildClose)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, MenuCommonItem_OnStorageChange)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonItem_OnTouchPanelMove)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_SLIDE_UP,MenuCommonItem_OnTouchPanelSlideUp)
EVENT_ITEM(NVTEVT_SLIDE_DOWN,MenuCommonItem_OnTouchPanelSlideDown)
EVENT_ITEM(NVTEVT_REDRAW,MenuCommonItem_OnRedraw)
//EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_OnTouchPanelClick)
EVENT_END


INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	TM_MENU    *pMenu;
	TM_PAGE    *pPage;
	//TM_ITEM    *pItem;
	//TM_OPTION  *pOption;
	//TM_ITEM    *pModeItem;
#if (PHOTO_MODE==ENABLE)
	//INT32      curMode = 0;
#endif
	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);
	
	#if 0
#if(WIFI_FUNC==ENABLE)
	if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_OK && UI_GetData(FL_NetWorkMode) == NET_STATION_MODE) {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_ON);
	} else {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_OFF);
	}
#else
        SysSetFlag(FL_COMMON_CLOUD, CLOUD_OFF);
#endif

	if (System_GetEnableSensor() == (SENSOR_1 | SENSOR_2)) {
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_ENABLE);
#if (PHOTO_MODE==ENABLE)
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_ENABLE);
#endif
#if (_BOARD_DRAM_SIZE_ == 0x04000000)
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1280x720P30, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_848x480P30, TM_OPTION_ENABLE);
#else
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_ENABLE);
#endif
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P80, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60, TM_OPTION_DISABLE);
	} else {
#if (SENSOR_CAPS_COUNT > 1)
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_DISABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_DISABLE);
#endif
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_DISABLE);
		//#NT#2016/08/12#Hideo Lin -begin
		//#NT#For small size clone movie
#if (SMALL_CLONE_MOVIE == DISABLE)
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P80, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60, TM_OPTION_DISABLE);
#endif
		//#NT#2016/08/12#Hideo Lin -end
	}

	MenuCommonItem_SetCurrentMenu(&gCommonMenu);
	pMenu = MenuCommonItem_GetCurrentMenu();

	pMenu->Status = TMS_ON_ITEM;
	pMenu->SelPage = 0;         // reset page to 0

	pPage = &pMenu->pPages[pMenu->SelPage];
	pPage->SelItem = 0;           // reset item to 0
	//check item if disable
	TM_CheckItemStatus(pMenu, &pPage->SelItem, TRUE);

	pItem = &pPage->pItems[pPage->SelItem];
	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];

	UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);
	UxList_SetData(&MenuCommonItem_ListCtrl, LST_CURITM, 0);
#if (PHOTO_MODE==ENABLE)
	curMode = System_GetState(SYS_STATE_CURRMODE);
	if (curMode == PRIMARY_MODE_PHOTO) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_CAPTURE_M;
		pModeItem->TextId = STRID_CAP_MODE;
	} else if (curMode == PRIMARY_MODE_MOVIE) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_VIDEO_M;
		pModeItem->TextId = STRID_MOVIE;
#if (PLAY_MODE == ENABLE)
	} else if (curMode == PRIMARY_MODE_PLAYBACK) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_PLAYBACK_M;
		pModeItem->TextId = STRID_PLAYBACK;
#endif
	}
#else
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_VIDEO_M;
		pModeItem->TextId = STRID_MOVIE;

#endif
	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();

	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_PRESS_MASK);
	Input_SetKeySoundMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	#endif

 #if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
    if(paramNum == 1) {
        g_pMenu=(TM_MENU*)paramArray[0];
        MenuCommonItem_SelectItem_Update((TM_MENU*)paramArray[0]);
        UxMenu_SetData(&MenuCommonItem_ItemSelectCtrl,MNU_CURITM,0);
    } else {
        MenuCommonItem_SelectItem_Update(&gMovieMenu);
        UxMenu_SetData(&MenuCommonItem_ItemSelectCtrl,MNU_CURITM,0);
    }

    if(g_pMenu==&gMovieMenu) {
        pMenu=&gMovieMenu;
        pPage = &pMenu->pPages[pMenu->SelPage];
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STRID,  pPage->TextId);
        //UxList_SetItemData(&MenuCommonItem_ItemSelectCtrl, i, LSTITM_ICONID, pItem->IconId);
    } else if(g_pMenu==&gPlaybackMenu) {
        pMenu=&gPlaybackMenu;
        pPage = &pMenu->pPages[pMenu->SelPage];
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STRID,  pPage->TextId);
        //UxList_SetItemData(&MenuCommonItem_ItemSelectCtrl, i, LSTITM_ICONID, pItem->IconId);
    #if (PHOTO_MODE == ENABLE)
	} else if(g_pMenu==&gPhotoMenu) {
        pMenu=&gPlaybackMenu;
        pPage = &pMenu->pPages[pMenu->SelPage];
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STRID,  pPage->TextId);
        //UxList_SetItemData(&MenuCommonItem_ItemSelectCtrl, i, LSTITM_ICONID, pItem->IconId);
	#endif
    } else {
        pMenu=&gMovieMenu;
        pPage = &pMenu->pPages[pMenu->SelPage];
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
        UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 0, MNUITM_STRID,  pPage->TextId);
        //UxList_SetItemData(&MenuCommonItem_ItemSelectCtrl, i, LSTITM_ICONID, pItem->IconId);
    }


    UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 1, MNUITM_STATUS, STATUS_ENABLE);
    UxMenu_SetItemData(&MenuCommonItem_ItemSelectCtrl, 1, MNUITM_STRID,  STRID_RETURN);
  #endif
	
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);

	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);

	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_DEFAULT);
#if (MOVIE_MODE==ENABLE)
	//#NT#2016/08/19#Lincy Lin#[0106935] -begin
	//#NT# Support change WDR, SHDR, RSC setting will change mode after exit menu
	BOOL bReOpenMovie = FlowMovie_CheckReOpenItem();
	BOOL bReOpenPhoto = 0;
#if (PHOTO_MODE==ENABLE)
	bReOpenPhoto = FlowPhoto_CheckReOpenItem();
#endif
	if(bReOpenMovie)
		exam_msg("RESTART_MODE_YES\r\n");
	else
		exam_msg("RESTART_MODE_NO\r\n");

	if (bReOpenMovie || bReOpenPhoto)
		//#NT#2016/08/19#Lincy Lin -end
	{
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu = MenuCommonItem_GetCurrentMenu();
	//UINT32      uiItem ,uiOption;

	pMenu->Status = TMS_ON_ITEM;
	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);

	if (paramNum >= 2) {
		//uiItem = paramArray[0];
		//uiOption = paramArray[1];
	}
	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);

	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}
#if 1//defined(YQCONFIG_TOUCH_FUNCTION_SUPPORT)
INT32 MenuCommonItem_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

    // Store press position
    g_TouchPressX = paramArray[0];
    g_TouchPressY = paramArray[1];
    g_MenuMoved = FALSE;

    return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

    INT32 uiPosX;
    //INT32 uiPosY;
    Ux_RECT rect;

    // If items more than 1 page, then support slide move function
    if (g_TotalItemCount > ITEMS_PER_PAGE) {
        uiPosX = paramArray[0];
        //uiPosY = paramArray[1];
        g_MenuMoved = TRUE;

        UxCtrl_GetPos((VControl *)&MenuCommonItemCtrl, &rect);
        rect.x1 = (-1) * DISPLAY_OSD_W + uiPosX - g_TouchPressX;
        rect.x2 = rect.x1 + 3 * DISPLAY_OSD_W - 1;
        //rect.x1 = rect.x1 + uiPosX - g_TouchPressX;
        // rect.x2 = rect.x2 + uiPosX - g_TouchPressX;
        g_PanelOffset = rect.x1;
        UxCtrl_SetPos((VControl *)&MenuCommonItemCtrl, rect);
        UxCtrl_SetDirty(&MenuCommonItemCtrl, TRUE);
        Ux_RedrawAllWind();
        // Flush repeat NVTEVT_MOVE in event queue
        Ux_FlushEventByRange(NVTEVT_MOVE, NVTEVT_MOVE);		// Use GxTouch_SetCtrl(GXTCH_MOVE_REPEAT_RATE, 3) to reduce move event
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU* pMenu;
    TM_PAGE* pPage;
    INT32 uiPosX;
    //INT32 uiPosY;
    Ux_RECT rect;

    uiPosX = paramArray[0];
    //uiPosY = paramArray[1];
    pMenu = MenuCommonItem_GetCurrentMenu();
    pPage = &pMenu->pPages[pMenu->SelPage];
	
    // Unlock MenuCommonModeCtrl otherwise the window cannot receive touch event anymore.
    UxCtrl_SetLock (pCtrl, FALSE);

    // If slide left more than 1/4 DISPLAY_OSD_W, change to previous page
    //if ((g_TouchPressX - uiPosX) > (DISPLAY_OSD_W/4))
    if ((g_TouchPressX - uiPosX) > (80))
    {
        g_PageCurrent = MenuCommonItem_FindDispPage(g_PageCurrent, SEARCH_NEXT_PAGE);
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][0];
        MenuCommonItem_UpdateContent(MenuCommonItem_GetCurrentMenu());
    }
    // If slide right more than 1/4 DISPLAY_OSD_W, change to next page
    // else if ((uiPosX - g_TouchPressX) > (DISPLAY_OSD_W/4))
    else if ((uiPosX - g_TouchPressX) > (80))
    {
        g_PageCurrent = MenuCommonItem_FindDispPage(g_PageCurrent, SEARCH_PREV_PAGE);
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][0];
        MenuCommonItem_UpdateContent(MenuCommonItem_GetCurrentMenu());
    }
    // Reset display position to 2nd display window.
    rect.x1 = (-1) * DISPLAY_OSD_W;
    rect.y1 = 0;
    rect.x2 = rect.x1 + 3 * DISPLAY_OSD_W - 1;
    rect.y2 = DISPLAY_OSD_H - 1;
    g_PanelOffset = rect.x1;
    //g_MenuMoved = FALSE;          // Cannot clean this flag otherwise CLICK event will refer to wrong status.
    // UxCtrl_SetPos((VControl *)&MenuCommonItemCtrl, Menu_Item_rect);
    UxCtrl_SetPos((VControl *)&MenuCommonItemCtrl, rect);
    UxCtrl_SetDirty(&MenuCommonItemCtrl, TRUE);
    Ux_RedrawAllWind();
    //Ux_Redraw();
    Ux_FlushEventByRange(NVTEVT_MOVE, NVTEVT_MOVE);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnTouchPanelSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow (pCtrl, 0);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnTouchPanelSlideDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow (pCtrl, 0);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    MenuCommonItem_DrawTitle();
    MenuCommonItem_DrawPoint();

    Ux_DefaultEvent(pCtrl,NVTEVT_REDRAW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

#if 0
INT32 MenuCommonItem_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiPosX;
    INT32 uiPosY;
    Ux_RECT rect;

    uiPosX = paramArray[0];
    uiPosY = paramArray[1];

    UxCtrl_GetPos(&MenuCommonItem_ItemSelectCtrl, &rect);

    if((uiPosX>=(g_PanelOffset+rect.x1))&&(uiPosX<=(g_PanelOffset+rect.x2))\
            &&(uiPosY>=rect.y1)&&(uiPosY<=rect.y2)\
      )
    {
        // extern INT32 MenuCommonItem_ItemSelect_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
        // MenuCommonItem_ItemSelect_OnTouchPanelClick(&MenuCommonItem_ItemSelectCtrl,paramNum,paramArray);
    }
    return NVTEVT_CONSUME;
}
#endif /* 0 */

#endif
//----------------------MenuCommonItem_ListCtrl Event---------------------------
INT32 MenuCommonItem_List_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeySelect(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeyExit(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_List)
EVENT_ITEM(NVTEVT_KEY_NEXT, MenuCommonItem_List_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_PREV, MenuCommonItem_List_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_SELECT, MenuCommonItem_List_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, MenuCommonItem_List_OnKeyExit)
EVENT_END

INT32 MenuCommonItem_List_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;

	if (paramNum == 1) {
		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			pMenu = MenuCommonItem_GetCurrentMenu();
			pPage = &pMenu->pPages[pMenu->SelPage];
			pPage->SelItem++;
			//check item if disable
			TM_CheckItemStatus(pMenu, &pPage->SelItem, TRUE);
			if (pPage->SelItem == pPage->Count) {
				// Close current UI Window now
				Ux_CloseWindow(&MenuCommonItemCtrl, 0);
			} else {
				MenuCommonItem_UpdateContent(pMenu);
				MenuCommonItem_UpdatePosition();
				Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);
			}
		}
	}
	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_List_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;

	if (paramNum == 1) {
		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			pMenu = MenuCommonItem_GetCurrentMenu();
			pPage = &pMenu->pPages[pMenu->SelPage];
			if (pPage->SelItem == 0) {
				// Close current UI Window now
				Ux_CloseWindow(&MenuCommonItemCtrl, 0);
			} else {
				pPage->SelItem--;
				//check item if disable
				TM_CheckItemStatus(pMenu, &pPage->SelItem, FALSE);
				if (pPage->SelItem == pPage->Count) {
					// Close current UI Window now
					Ux_CloseWindow(&MenuCommonItemCtrl, 0);
				} else {
					MenuCommonItem_UpdateContent(pMenu);
					MenuCommonItem_UpdatePosition();
					Ux_SendEvent(pCtrl, NVTEVT_PREVIOUS_ITEM, 0);
				}
			}
		}
	}
	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_List_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	TM_MENU    *pNextMenu;
	UINT32      SelOption = 0 ;

	if (paramNum == 1) {
		pMenu = MenuCommonItem_GetCurrentMenu();
		pPage = &pMenu->pPages[pMenu->SelPage];
		pItem = &pPage->pItems[pPage->SelItem];

		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			if (pItem->Count != 0 && pItem->SysFlag != 0 && pItem->ItemId != IDM_COMMON_CLOUD) {
				SelOption = SysGetFlag(pItem->SysFlag);

				SelOption++;
				if (SelOption >= pItem->Count) {
					SelOption = 0;
				}

				SysSetFlag(pItem->SysFlag, SelOption);

				// toggle icon's string
				pOption = &pItem->pOptions[SelOption];
				UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);

				TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, SelOption));
			} else {
				if (pItem->SysFlag == FL_COMMON_MODE) {
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gModeMenu);
				} else if (pItem->SysFlag == FL_COMMON_MENU) {
#if (PHOTO_MODE == ENABLE)
					// Enter 2nd level menu and pop up current mode's menu lists
					if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO) {
						pNextMenu = &gPhotoMenu;
#if (PLAY_MODE == ENABLE)
					} else if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
						pNextMenu = &gPlaybackMenu;
#endif
					} else {
						pNextMenu = &gMovieMenu;
					}
#else
                        pNextMenu = &gMovieMenu;
#endif
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, (UINT32)pNextMenu);
				} else if (pItem->SysFlag == FL_COMMON_SETUP) {
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gSetupMenu);
				} else if (pItem->SysFlag == FL_COMMON_EXT_SETUP) {
				    #if _TODO
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gExtSetupMenu);
                    #endif
				} else {
					MenuCommonItemErrMsg("not supp %d\r\n", pItem->SysFlag);
				}
			}
		}
	}

	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_List_OnKeyExit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0);
	return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Title)
EVENT_END

//----------------------MenuCommonItem_StatusCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Status)
EVENT_END

//---------------------MenuCommItem_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommItem_Panel)
CTRL_LIST_ITEM(MenuCommonItem_Left)
CTRL_LIST_ITEM(MenuCommonItem_Right)
CTRL_LIST_ITEM(MenuCommonItem_LeftIcon)
CTRL_LIST_ITEM(MenuCommonItem_RightIcon)
CTRL_LIST_END

//----------------------MenuCommItem_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommItem_Panel)
EVENT_END

//----------------------MenuCommonItem_LeftCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Left)
EVENT_END

//----------------------MenuCommonItem_RightCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Right)
EVENT_END

//----------------------MenuCommonItem_LeftIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_LeftIcon)
EVENT_END

//----------------------MenuCommonItem_RightIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_RightIcon)
EVENT_END

//----------------------MenuCommonItem_ItemSelectCtrl Event---------------------------
INT32 MenuCommonItem_ItemSelect_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_ItemSelect_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_ItemSelect_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_ItemSelect)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_ItemSelect_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_ItemSelect_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_ItemSelect_OnTouchPanelClick)
EVENT_END
INT32 MenuCommonItem_ItemSelect_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_MenuMoved = FALSE;
    Ux_DefaultEvent(pCtrl, NVTEVT_PRESS, paramNum, paramArray);
    return NVTEVT_PASS;
}

INT32 MenuCommonItem_ItemSelect_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
    return NVTEVT_PASS;
}
//#NT#2017/04/24#KCHong -end

INT32 MenuCommonItem_ItemSelect_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //TM_MENU*    pMenu;
    //TM_PAGE*    pPage;

    //INT32 uiPosX;
    //INT32 uiPosY;
    INT32 CurrItem;
    //INT32 TatalItem;
    //INT32 ItemOffset;

    //INT32 PageItem;
    //INT32 Style;
    //INT32 Action;

    if(!g_MenuMoved)
    {
        //uiPosX = paramArray[0];
        //uiPosY = paramArray[1];

        CurrItem=UxMenu_GetData(pCtrl,MNU_CURITM);
        //TatalItem=UxMenu_GetData(pCtrl,MNU_TOTITM);
        //PageItem=UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        //Style=UxMenu_GetData(pCtrl,MNU_STYLE);
        //Action=UxMenu_GetData(pCtrl,MNU_ACTION);

        // pMenu = MenuCommonItem_GetCurrentMenu();
        // pPage = &pMenu->pPages[pMenu->SelPage];
        //pPage->SelItem = g_PageItemIndex[g_PageCurrent][3];
        //MenuCommonItem_SelectItem(pMenu);
        if(CurrItem==1) {
            Ux_CloseWindow(&MenuCommonItemCtrl,0);
        } else {
            if(g_pMenu==&gPlaybackMenu) {
                MenuCommonItem_SelectItem_Update(&gPlaybackMenu);
            } else {
                MenuCommonItem_SelectItem_Update(&gMovieMenu);
            }
        }
    }
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonItem_Point0Ctrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_Point0)
CTRL_LIST_END

//----------------------MenuCommonItem_Point0Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Point0)
EVENT_END

//---------------------MenuCommonItem_Point1Ctrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_Point1)
CTRL_LIST_END

//----------------------MenuCommonItem_Point1Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Point1)
EVENT_END

//---------------------MenuCommonItem_Point2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_Point2)
CTRL_LIST_END

//----------------------MenuCommonItem_Point2Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Point2)
EVENT_END

//---------------------MenuCommonItem_Point3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_Point3)
CTRL_LIST_END

//----------------------MenuCommonItem_Point3Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Point3)
EVENT_END

//---------------------MenuCommonItem_Point4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem_Point4)
CTRL_LIST_END

//----------------------MenuCommonItem_Point4Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Point4)
EVENT_END

//----------------------MenuCommonItem_BTN0Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN0)
EVENT_END

//----------------------MenuCommonItem_BTN1Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN1)
EVENT_END

//----------------------MenuCommonItem_BTN2Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN2)
EVENT_END

//----------------------MenuCommonItem_BTN3Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN3)
EVENT_END

//----------------------MenuCommonItem_BTN4Ctrl Event---------------------------
INT32 MenuCommonItem_BTN4_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN4_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN4_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN4_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_BTN4)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_BTN4_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_BTN4_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_BTN4_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonItem_BTN4_OnTouchPanelMove)
EVENT_END

INT32 MenuCommonItem_BTN4_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_MenuMoved = FALSE;
    Ux_DefaultEvent(pCtrl, NVTEVT_PRESS, paramNum, paramArray);
    return NVTEVT_PASS;
}

INT32 MenuCommonItem_BTN4_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
    return NVTEVT_PASS;
}
//#NT#2017/04/24#KCHong -end

INT32 MenuCommonItem_BTN4_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;

    if(!g_MenuMoved)
    {
        pMenu = MenuCommonItem_GetCurrentMenu();
        pPage = &pMenu->pPages[pMenu->SelPage];
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][0];
        MenuCommonItem_SelectItem(pMenu);
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_BTN4_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // If items more than 1 page, then support slide move function
    if (g_TotalItemCount > ITEMS_PER_PAGE)
    {
        // If button is locked, release itself and set MenuCommonModeCtrl as locked VControl (then only MenuCommonModeCtrl can receive event)
        if (UxCtrl_GetLock() == pCtrl)
        {
            Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
            UxCtrl_SetLock (&MenuCommonItemCtrl, TRUE);
            Ux_SendEvent(&MenuCommonItemCtrl, NVTEVT_MOVE, 2, (paramArray[0] + g_PanelOffset), paramArray[1]);
        }
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_BTN5Ctrl Event---------------------------
INT32 MenuCommonItem_BTN5_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN5_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN5_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN5_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_BTN5)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_BTN5_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_BTN5_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_BTN5_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonItem_BTN5_OnTouchPanelMove)
EVENT_END

INT32 MenuCommonItem_BTN5_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_MenuMoved = FALSE;
    Ux_DefaultEvent(pCtrl, NVTEVT_PRESS, paramNum, paramArray);
    return NVTEVT_PASS;
}

INT32 MenuCommonItem_BTN5_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
    return NVTEVT_PASS;
}
//#NT#2017/04/24#KCHong -end

INT32 MenuCommonItem_BTN5_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;

    if(!g_MenuMoved)
    {
        pMenu = MenuCommonItem_GetCurrentMenu();
        pPage = &pMenu->pPages[pMenu->SelPage];
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][1];
        MenuCommonItem_SelectItem(pMenu);
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_BTN5_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
// If items more than 1 page, then support slide move function
    if (g_TotalItemCount > ITEMS_PER_PAGE)
    {
        // If button is locked, release itself and set MenuCommonModeCtrl as locked VControl (then only MenuCommonModeCtrl can receive event)
        if (UxCtrl_GetLock() == pCtrl)
        {
            Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
            UxCtrl_SetLock (&MenuCommonItemCtrl, TRUE);
            Ux_SendEvent(&MenuCommonItemCtrl, NVTEVT_MOVE, 2, (paramArray[0] + g_PanelOffset), paramArray[1]);
        }
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_BTN6Ctrl Event---------------------------
INT32 MenuCommonItem_BTN6_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN6_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN6_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN6_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_BTN6)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_BTN6_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_BTN6_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_BTN6_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonItem_BTN6_OnTouchPanelMove)
EVENT_END

INT32 MenuCommonItem_BTN6_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_MenuMoved = FALSE;
    Ux_DefaultEvent(pCtrl, NVTEVT_PRESS, paramNum, paramArray);
    return NVTEVT_PASS;
}

INT32 MenuCommonItem_BTN6_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
    return NVTEVT_PASS;
}
//#NT#2017/04/24#KCHong -end

INT32 MenuCommonItem_BTN6_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;

    if(!g_MenuMoved)
    {
        pMenu = MenuCommonItem_GetCurrentMenu();
        pPage = &pMenu->pPages[pMenu->SelPage];
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][2];
        MenuCommonItem_SelectItem(pMenu);
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_BTN6_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // If items more than 1 page, then support slide move function
    if (g_TotalItemCount > ITEMS_PER_PAGE)
    {
        // If button is locked, release itself and set MenuCommonModeCtrl as locked VControl (then only MenuCommonModeCtrl can receive event)
        if (UxCtrl_GetLock() == pCtrl)
        {
            Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
            UxCtrl_SetLock (&MenuCommonItemCtrl, TRUE);
            Ux_SendEvent(&MenuCommonItemCtrl, NVTEVT_MOVE, 2, (paramArray[0] + g_PanelOffset), paramArray[1]);
        }
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_BTN7Ctrl Event---------------------------
INT32 MenuCommonItem_BTN7_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN7_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN7_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_BTN7_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_BTN7)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonItem_BTN7_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,MenuCommonItem_BTN7_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonItem_BTN7_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_MOVE,MenuCommonItem_BTN7_OnTouchPanelMove)
EVENT_END

INT32 MenuCommonItem_BTN7_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_MenuMoved = FALSE;
    Ux_DefaultEvent(pCtrl, NVTEVT_PRESS, paramNum, paramArray);
    return NVTEVT_PASS;
}

INT32 MenuCommonItem_BTN7_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
    return NVTEVT_PASS;
}
//#NT#2017/04/24#KCHong -end

INT32 MenuCommonItem_BTN7_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu;
    TM_PAGE*    pPage;

    if(!g_MenuMoved)
    {
        pMenu = MenuCommonItem_GetCurrentMenu();
        pPage = &pMenu->pPages[pMenu->SelPage];
        pPage->SelItem = g_PageItemIndex[g_PageCurrent][3];
        MenuCommonItem_SelectItem(pMenu);
    }
    return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_BTN7_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

    // If items more than 1 page, then support slide move function
    if (g_TotalItemCount > ITEMS_PER_PAGE)
    {
        // If button is locked, release itself and set MenuCommonModeCtrl as locked VControl (then only MenuCommonModeCtrl can receive event)
        if (UxCtrl_GetLock() == pCtrl)
        {
            Ux_DefaultEvent(pCtrl, NVTEVT_RELEASE, paramNum, paramArray);
            UxCtrl_SetLock (&MenuCommonItemCtrl, TRUE);
            Ux_SendEvent(&MenuCommonItemCtrl, NVTEVT_MOVE, 2, (paramArray[0] + g_PanelOffset), paramArray[1]);
        }
    }
    return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_BTN8Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN8)
EVENT_END

//----------------------MenuCommonItem_BTN9Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN9)
EVENT_END

//----------------------MenuCommonItem_BTN10Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN10)
EVENT_END

//----------------------MenuCommonItem_BTN11Ctrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_BTN11)
EVENT_END

