/*//////////////////////////////////////////////////////////////////////////////

 ---------- Document Info ---------------

        Author : Anonymous
       Created : 20:42:59, May 19 2009
 Last modified : 15:18:17, Mar 22 2013
   Making tool : UI Designer Studio
   File format : C language header file

 ----------- Object Info ----------------

         Class : IMAGE_TABLE
          Name : DemoKit_Image

*///////////////////////////////////////////////////////////////////////////////

#ifndef _DEMOKIT_IMAGE_H_
#define _DEMOKIT_IMAGE_H_

// IMAGE_TABLE
extern const
unsigned char gDemoKit_Image[];

// IMAGE ID
#define _86X66NORMAL                             0x0000
#define _100X80EMBOSS                            0x0001
#define _100X80PUSH                              0x0002
#define _100X80RELEASE                           0x0003
#define ICON__EMPTY                              0x0004
#define ICON_ACT_PUSH_BTN                        0x0005
#define ICON_ACT_RELEASE_BTN                     0x0006
#define ICON_ADAS_CAL                            0x0007
#define ICON_ADAS_CAL_M                          0x0008
#define ICON_ADAS_OFF                            0x0009
#define ICON_ADAS_OFF_M                          0x000A
#define ICON_ADAS_ON                             0x000B
#define ICON_ADAS_ON_M                           0x000C
#define ICON_AE_SETUP_M                          0x000D
#define ICON_AP_MACHINE_OFF                      0x000E
#define ICON_AP_MACHINE_ON                       0x000F
#define ICON_AUDIO_NORMAL                        0x0010
#define ICON_AUDIO_OFF                           0x0011
#define ICON_AUDIO_OFF_NORMAL                    0x0012
#define ICON_AUDIO_OFF_PRESS                     0x0013
#define ICON_AUDIO_ON                            0x0014
#define ICON_AUDIO_PRESS                         0x0015
#define ICON_AUDIO_REC_OFF                       0x0016
#define ICON_AUDIO_REC_OFF_M                     0x0017
#define ICON_AUDIO_REC_ON                        0x0018
#define ICON_AUDIO_REC_ON_M                      0x0019
#define ICON_AUDIO_REC_ON_MM                     0x001A
#define ICON_AUDIO_SETUP                         0x001B
#define ICON_AUDIO_SETUP_M                       0x001C
#define ICON_AUTOSHUTDOWN                        0x001D
#define ICON_AUTOSHUTDOWN_3MIN                   0x001E
#define ICON_AUTOSHUTDOWN_5MIN                   0x001F
#define ICON_AUTOSHUTDOWN_10MIN                  0x0020
#define ICON_AUTOSHUTDOWN_M                      0x0021
#define ICON_AUTOSHUTDOWN_OFF                    0x0022
#define ICON_AWB_SETUP_M                         0x0023
#define ICON_BACK_NORMAL                         0x0024
#define ICON_BACK_PRESS                          0x0025
#define ICON_BACK_SETUP_NORMAL                   0x0026
#define ICON_BACK_SETUP_PRESS                    0x0027
#define ICON_BACKLIGHT                           0x0028
#define ICON_BACKLIGHT_HIGH                      0x0029
#define ICON_BACKLIGHT_LOW                       0x002A
#define ICON_BACKLIGHT_M                         0x002B
#define ICON_BACKLIGHT_MID                       0x002C
#define ICON_BACKLIGHT_OFF                       0x002D
#define ICON_BATTERY_CHARGE                      0x002E
#define ICON_BATTERY_EMPTY                       0x002F
#define ICON_BATTERY_FULL                        0x0030
#define ICON_BATTERY_LOW                         0x0031
#define ICON_BATTERY_MED                         0x0032
#define ICON_BATTERY_TYPE                        0x0033
#define ICON_BATTERY_ZERO                        0x0034
#define ICON_BEEPSOUND_SETUP_M                   0x0035
#define ICON_BEHIND_OFF                          0x0036
#define ICON_BEHIND_ON                           0x0037
#define ICON_BLUETOOTH_OFF                       0x0038
#define ICON_BLUETOOTH_ON                        0x0039
#define ICON_BSD_OFF                             0x003A
#define ICON_BSD_OFF_M                           0x003B
#define ICON_BSD_ON                              0x003C
#define ICON_BSD_ON_M                            0x003D
#define ICON_BTN_EMBOSS                          0x003E
#define ICON_BTN_EMBOSS1                         0x003F
#define ICON_BUST                                0x0040
#define ICON_BUST_3SHOT                          0x0041
#define ICON_BUST_CONTINUE                       0x0042
#define ICON_BUST_M                              0x0043
#define ICON_BUST_OFF                            0x0044
#define ICON_CAM_PTZ_OFF                         0x0045
#define ICON_CAM_PTZ_ON                          0x0046
#define ICON_CAM_PTZ_ON_M                        0x0047
#define ICON_CANCEL                              0x0048
#define ICON_CANCEL_M                            0x0049
#define ICON_CAPMODE_SETUP_M                     0x004A
#define ICON_CAPTURE_NORMAL                      0x004B
#define ICON_CAPTURE_PRESS                       0x004C
#define ICON_CARNUM_SETUP                        0x004D
#define ICON_CARNUM_SETUP_M                      0x004E
#define ICON_CLOUD_CONNECTED                     0x004F
#define ICON_CLOUD_CONNECTED_M                   0x0050
#define ICON_CLOUD_CONNECTING                    0x0051
#define ICON_CLOUD_CONNECTING_M                  0x0052
#define ICON_CLOUD_DOWNLOAD1                     0x0053
#define ICON_CLOUD_DOWNLOAD2                     0x0054
#define ICON_CLOUD_FAIL                          0x0055
#define ICON_CLOUD_OFF                           0x0056
#define ICON_CLOUD_OFF_M                         0x0057
#define ICON_CLOUD_ON                            0x0058
#define ICON_CLOUD_ON_M                          0x0059
#define ICON_CLOUD_UPLOAD1                       0x005A
#define ICON_CLOUD_UPLOAD2                       0x005B
#define ICON_COLOR                               0x005C
#define ICON_COLOR_SETUP_M                       0x005D
#define ICON_COPY_FROM_CARD                      0x005E
#define ICON_CYCLIC_REC                          0x005F
#define ICON_CYCLIC_REC_1MIN                     0x0060
#define ICON_CYCLIC_REC_2MIN                     0x0061
#define ICON_CYCLIC_REC_2MIN_M                   0x0062
#define ICON_CYCLIC_REC_3MIN                     0x0063
#define ICON_CYCLIC_REC_3MIN_M                   0x0064
#define ICON_CYCLIC_REC_5MIN                     0x0065
#define ICON_CYCLIC_REC_5MIN_M                   0x0066
#define ICON_CYCLIC_REC_10MIN                    0x0067
#define ICON_CYCLIC_REC_15MIN                    0x0068
#define ICON_CYCLIC_REC_M                        0x0069
#define ICON_CYCLIC_REC_OFF                      0x006A
#define ICON_DAOCHE                              0x006B
#define ICON_DAOCHE_FAIL                         0x006C
#define ICON_DATE_PRINT                          0x006D
#define ICON_DATE_PRINT_M                        0x006E
#define ICON_DATE_PRINT_PRESS                    0x006F
#define ICON_DATE_PRINT_PREV                     0x0070
#define ICON_DATE_STAMPING                       0x0071
#define ICON_DATE_TIME                           0x0072
#define ICON_DATESTAMP_SETUP_M                   0x0073
#define ICON_DATETIME_SETUP                      0x0074
#define ICON_DATETIME_SETUP_M                    0x0075
#define ICON_DDD_OFF                             0x0076
#define ICON_DDD_OFF_M                           0x0077
#define ICON_DDD_ON                              0x0078
#define ICON_DDD_ON_M                            0x0079
#define ICON_DEFAULT                             0x007A
#define ICON_DEFAULT_M                           0x007B
#define ICON_DELETE                              0x007C
#define ICON_DELETE_ALL                          0x007D
#define ICON_DELETE_CURRENT                      0x007E
#define ICON_DELETE_M                            0x007F
#define ICON_DELETE_NORMAL                       0x0080
#define ICON_DELETE_PRESS                        0x0081
#define ICON_DIR_DOWN                            0x0082
#define ICON_DIR_LEFT                            0x0083
#define ICON_DIR_RIGHT                           0x0084
#define ICON_DIR_UP                              0x0085
#define ICON_DISPLAY_CHANGE                      0x0086
#define ICON_DOWN_SETUP_NORMAL                   0x0087
#define ICON_DOWN_SETUP_PRESS                    0x0088
#define ICON_DPOF                                0x0089
#define ICON_DUALCAM_BEHIND                      0x008A
#define ICON_DUALCAM_BOTH                        0x008B
#define ICON_DUALCAM_BOTH_M                      0x008C
#define ICON_DUALCAM_FRONT                       0x008D
#define ICON_EV                                  0x008E
#define ICON_EV_M                                0x008F
#define ICON_EV_M0P3                             0x0090
#define ICON_EV_M0P6                             0x0091
#define ICON_EV_M1P0                             0x0092
#define ICON_EV_M1P0_M                           0x0093
#define ICON_EV_M1P3                             0x0094
#define ICON_EV_M1P6                             0x0095
#define ICON_EV_M2P0                             0x0096
#define ICON_EV_M2P0_M                           0x0097
#define ICON_EV_M3P0                             0x0098
#define ICON_EV_M3P0_M                           0x0099
#define ICON_EV_P0P0                             0x009A
#define ICON_EV_P0P0_M                           0x009B
#define ICON_EV_P0P3                             0x009C
#define ICON_EV_P0P6                             0x009D
#define ICON_EV_P1P0                             0x009E
#define ICON_EV_P1P0_M                           0x009F
#define ICON_EV_P1P3                             0x00A0
#define ICON_EV_P1P6                             0x00A1
#define ICON_EV_P2P0                             0x00A2
#define ICON_EV_P2P0_M                           0x00A3
#define ICON_EV_P3P0                             0x00A4
#define ICON_EV_P3P0_M                           0x00A5
#define ICON_FACE_OFF                            0x00A6
#define ICON_FACE_ON                             0x00A7
#define ICON_FACE_ON_M                           0x00A8
#define ICON_FATIGUE                             0x00A9
#define ICON_FATIGUE_1H                          0x00AA
#define ICON_FATIGUE_1H_M                        0x00AB
#define ICON_FATIGUE_2H                          0x00AC
#define ICON_FATIGUE_2H_M                        0x00AD
#define ICON_FATIGUE_3H                          0x00AE
#define ICON_FATIGUE_3H_M                        0x00AF
#define ICON_FATIGUE_4H                          0x00B0
#define ICON_FATIGUE_4H_M                        0x00B1
#define ICON_FATIGUE_DRIVING                     0x00B2
#define ICON_FATIGUE_DRIVING_MENU                0x00B3
#define ICON_FATIGUE_M                           0x00B4
#define ICON_FATIGUE_SETUP_M                     0x00B5
#define ICON_FB_LEFT                             0x00B6
#define ICON_FB_LEFT_ORI                         0x00B7
#define ICON_FCW_ALERT                           0x00B8
#define ICON_FCW_FAR_ALERT                       0x00B9
#define ICON_FCW_NEAR_ALERT                      0x00BA
#define ICON_FCW_OFF                             0x00BB
#define ICON_FCW_OFF_M                           0x00BC
#define ICON_FCW_ON                              0x00BD
#define ICON_FCW_ON_M                            0x00BE
#define ICON_FCW_SETUP_M                         0x00BF
#define ICON_FF_RIGHT                            0x00C0
#define ICON_FF_RIGHT_ORI                        0x00C1
#define ICON_FILE_PHOTO                          0x00C2
#define ICON_FILE_PHOTO_1                        0x00C3
#define ICON_FILE_PHOTO_2                        0x00C4
#define ICON_FILE_PHOTO_3                        0x00C5
#define ICON_FILE_PHOTO_4                        0x00C6
#define ICON_FILE_PHOTO_5                        0x00C7
#define ICON_FILE_PHOTO_6                        0x00C8
#define ICON_FILE_PHOTO_7                        0x00C9
#define ICON_FILE_PHOTO_M                        0x00CA
#define ICON_FILE_VIDEO                          0x00CB
#define ICON_FILE_VIDEO_0                        0x00CC
#define ICON_FILE_VIDEO_1                        0x00CD
#define ICON_FILE_VIDEO_2                        0x00CE
#define ICON_FILE_VIDEO_3                        0x00CF
#define ICON_FILE_VIDEO_4                        0x00D0
#define ICON_FILE_VIDEO_5                        0x00D1
#define ICON_FILE_VIDEO_6                        0x00D2
#define ICON_FILE_VIDEO_7                        0x00D3
#define ICON_FILE_VIDEO_M                        0x00D4
#define ICON_FIRMWARE_UPDATE                     0x00D5
#define ICON_FIRMWARE_UPDATE_M                   0x00D6
#define ICON_FLASH_AUTO                          0x00D7
#define ICON_FLASH_OFF                           0x00D8
#define ICON_FLASH_ON                            0x00D9
#define ICON_FLASH_ON_M                          0x00DA
#define ICON_FLASH_REC                           0x00DB
#define ICON_FLASH_REC_M                         0x00DC
#define ICON_FLASH_RED_EYE                       0x00DD
#define ICON_FLICK_50HZ                          0x00DE
#define ICON_FLICK_60HZ                          0x00DF
#define ICON_FORMAT                              0x00E0
#define ICON_FORMAT_M                            0x00E1
#define ICON_FORMATSD_SETUP_M                    0x00E2
#define ICON_FRAME_SETUP_M_NORMAL                0x00E3
#define ICON_FRAME_SETUP_M_PRESS                 0x00E4
#define ICON_FREQ_SETUP_M                        0x00E5
#define ICON_G_SENSOR                            0x00E6
#define ICON_G_SENSOR_HIGH                       0x00E7
#define ICON_G_SENSOR_LOW                        0x00E8
#define ICON_G_SENSOR_M                          0x00E9
#define ICON_G_SENSOR_MID                        0x00EA
#define ICON_G_SENSOR_OFF                        0x00EB
#define ICON_GOLF_REC                            0x00EC
#define ICON_GOLF_REC_M                          0x00ED
#define ICON_GPS_DIRECTION                       0x00EE
#define ICON_GPS_LEVEL0                          0x00EF
#define ICON_GPS_LEVEL1                          0x00F0
#define ICON_GPS_LEVEL2                          0x00F1
#define ICON_GPS_LEVEL3                          0x00F2
#define ICON_GPS_NS                              0x00F3
#define ICON_GPS_OFF                             0x00F4
#define ICON_GPS_OK                              0x00F5
#define ICON_GPS_ON                              0x00F6
#define ICON_GPS_ON_M                            0x00F7
#define ICON_GPS_SERCH                           0x00F8
#define ICON_GPS_SETUP_M                         0x00F9
#define ICON_GPS_STAMP                           0x00FA
#define ICON_GSENSOR                             0x00FB
#define ICON_GSENSOR_H_M                         0x00FC
#define ICON_GSENSOR_HIGH                        0x00FD
#define ICON_GSENSOR_L_M                         0x00FE
#define ICON_GSENSOR_LOW                         0x00FF
#define ICON_GSENSOR_M                           0x0100
#define ICON_GSENSOR_M_M                         0x0101
#define ICON_GSENSOR_MID                         0x0102
#define ICON_GSENSOR_OFF                         0x0103
#define ICON_GSENSOR_SENSITIVITY                 0x0104
#define ICON_GSENSOR_SETUP                       0x0105
#define ICON_GSENSOR_SETUP_M                     0x0106
#define ICON_HDR                                 0x0107
#define ICON_HDR_M                               0x0108
#define ICON_HDR_OFF                             0x0109
#define ICON_HELP                                0x010A
#define ICON_HELP_M                              0x010B
#define ICON_HINT_BAR                            0x010C
#define ICON_HOME_NORMAL                         0x010D
#define ICON_HOME_PRESS                          0x010E
#define ICON_HZ                                  0x010F
#define ICON_HZ_50                               0x0110
#define ICON_HZ_60                               0x0111
#define ICON_HZ_M                                0x0112
#define ICON_INFO                                0x0113
#define ICON_INFO_M                              0x0114
#define ICON_INTERNAL_FLASH                      0x0115
#define ICON_INTERNAL_FLASH_M                    0x0116
#define ICON_IRCUT_AUTO                          0x0117
#define ICON_IRCUT_OFF                           0x0118
#define ICON_IRCUT_ON                            0x0119
#define ICON_IRCUT_ON_M                          0x011A
#define ICON_ISO                                 0x011B
#define ICON_ISO_100                             0x011C
#define ICON_ISO_100_M                           0x011D
#define ICON_ISO_200                             0x011E
#define ICON_ISO_200_M                           0x011F
#define ICON_ISO_400                             0x0120
#define ICON_ISO_400_M                           0x0121
#define ICON_ISO_800                             0x0122
#define ICON_ISO_1600                            0x0123
#define ICON_ISO_AUTO                            0x0124
#define ICON_ISO_AUTO_M                          0x0125
#define ICON_ISO_M                               0x0126
#define ICON_ISO_SETUP_M                         0x0127
#define ICON_LANDSCAPE                           0x0128
#define ICON_LANGUAGE                            0x0129
#define ICON_LANGUAGE_M                          0x012A
#define ICON_LANGUAGE_SETUP_M                    0x012B
#define ICON_LDWS_ALERT                          0x012C
#define ICON_LDWS_LEFT_ALERT                     0x012D
#define ICON_LDWS_OFF                            0x012E
#define ICON_LDWS_OFF_M                          0x012F
#define ICON_LDWS_ON                             0x0130
#define ICON_LDWS_ON_M                           0x0131
#define ICON_LDWS_RIGHT_ALERT                    0x0132
#define ICON_LDWS_SETUP_M                        0x0133
#define ICON_LEFT_NORMAL                         0x0134
#define ICON_LEFT_PRESS                          0x0135
#define ICON_LEFT_SETUP_NORMAL                   0x0136
#define ICON_LEFT_SETUP_PRESS                    0x0137
#define ICON_LIGHT_1                             0x0138
#define ICON_LIGHT_2                             0x0139
#define ICON_LIGHT_3                             0x013A
#define ICON_LIGHT_4                             0x013B
#define ICON_LIGHT_5                             0x013C
#define ICON_LIGHT_6                             0x013D
#define ICON_LIGHT_7                             0x013E
#define ICON_LIGHT_8                             0x013F
#define ICON_LIGHT_9                             0x0140
#define ICON_LIGHT_10                            0x0141
#define ICON_LINE_H_80                           0x0142
#define ICON_LINE_H_107                          0x0143
#define ICON_LINE_H_200                          0x0144
#define ICON_LINE_H_240                          0x0145
#define ICON_LINE_V_444                          0x0146
#define ICON_LINE_V_640                          0x0147
#define ICON_LOCAL_STATION__OFF                  0x0148
#define ICON_LOCAL_STATION__ON                   0x0149
#define ICON_LOCK                                0x014A
#define ICON_LOCK_ALL                            0x014B
#define ICON_LOCK_ALL_M                          0x014C
#define ICON_LOCK_CURRENT                        0x014D
#define ICON_LOCK_CURRENT_M                      0x014E
#define ICON_LOCK_LOC                            0x014F
#define ICON_LOCK_LOCK                           0x0150
#define ICON_LOCK_LOCK_M                         0x0151
#define ICON_LOCK_M                              0x0152
#define ICON_LOCK_NORMAL                         0x0153
#define ICON_LOCK_OFF                            0x0154
#define ICON_LOCK_ON                             0x0155
#define ICON_LOCK_ON_M                           0x0156
#define ICON_LOCK_PRESS                          0x0157
#define ICON_LOCK_UNLOCK                         0x0158
#define ICON_LOCK_UNLOCK_M                       0x0159
#define ICON_LOCK_UNLOKC_ALL                     0x015A
#define ICON_LOCK_UNLOKC_ALL_M                   0x015B
#define ICON_LOGO                                0x015C
#define ICON_LOOPRECORD_SETUP_M                  0x015D
#define ICON_LPR_OFF                             0x015E
#define ICON_LPR_OFF_M                           0x015F
#define ICON_LPR_ON                              0x0160
#define ICON_LPR_ON_M                            0x0161
#define ICON_MENU_DUAL_REC                       0x0162
#define ICON_MENU_FLASH_REC                      0x0163
#define ICON_MENU_GPS                            0x0164
#define ICON_MENU_HDR                            0x0165
#define ICON_MENU_MODECHANG                      0x0166
#define ICON_MENU_MODECHANG_M                    0x0167
#define ICON_MENU_PLAYBACK_OFF                   0x0168
#define ICON_MENU_PLAYBACK_ON                    0x0169
#define ICON_MENU_PRINT_OFF                      0x016A
#define ICON_MENU_PRINT_OFF2                     0x016B
#define ICON_MENU_RETURN                         0x016C
#define ICON_MENU_RETURN_M                       0x016D
#define ICON_MENU_SETUP_OFF                      0x016E
#define ICON_MENU_SETUP_ON                       0x016F
#define ICON_MENU_SETUP_ON_M                     0x0170
#define ICON_MENU_STILL_OFF                      0x0171
#define ICON_MENU_STILL_ON                       0x0172
#define ICON_MENU_UNDERBAR                       0x0173
#define ICON_MENU_VIDEO_OFF                      0x0174
#define ICON_MENU_VIDEO_ON                       0x0175
#define ICON_MENU_WDR                            0x0176
#define ICON_MENU_WDR_M                          0x0177
#define ICON_MENU_WDR_OFF                        0x0178
#define ICON_METERING                            0x0179
#define ICON_METERING_M                          0x017A
#define ICON_MODE                                0x017B
#define ICON_MODE_CAPTURE                        0x017C
#define ICON_MODE_CAPTURE_M                      0x017D
#define ICON_MODE_CAPTURE_MM                     0x017E
#define ICON_MODE_MOVIE                          0x017F
#define ICON_MODE_PHOTO                          0x0180
#define ICON_MODE_PLAY                           0x0181
#define ICON_MODE_PLAYBACK                       0x0182
#define ICON_MODE_PLAYBACK_M                     0x0183
#define ICON_MODE_VIDEO                          0x0184
#define ICON_MODE_VIDEO_M                        0x0185
#define ICON_MODE_VIDEO_MM                       0x0186
#define ICON_MOTION_DET                          0x0187
#define ICON_MOTION_DET_MENU                     0x0188
#define ICON_MOTION_DET_OFF                      0x0189
#define ICON_MOTION_DET_ON                       0x018A
#define ICON_MOTION_DET_ON_M                     0x018B
#define ICON_MOTION_ON_M                         0x018C
#define ICON_MOTION_SETUP_M                      0x018D
#define ICON_MOVIE_NORMAL                        0x018E
#define ICON_MOVIE_PRESS                         0x018F
#define ICON_MOVIE_SETUP_NORMAL                  0x0190
#define ICON_MOVIE_SETUP_PRESS                   0x0191
#define ICON_MOVIE_START_REC                     0x0192
#define ICON_MOVIESIZE_SETUP_M                   0x0193
#define ICON_NO                                  0x0194
#define ICON_NO_M                                0x0195
#define ICON_OK                                  0x0196
#define ICON_OK_M                                0x0197
#define ICON_OK_M_2                              0x0198
#define ICON_OK_PAUSE                            0x0199
#define ICON_OK_PLAY                             0x019A
#define ICON_OK2                                 0x019B
#define ICON_PAGE_CHOOSE_SETUP                   0x019C
#define ICON_PAGE_SETUP                          0x019D
#define ICON_PARKING                             0x019E
#define ICON_PARKING_ALL                         0x019F
#define ICON_PARKING_B                           0x01A0
#define ICON_PARKING_DAY                         0x01A1
#define ICON_PARKING_GSENTRIGGER                 0x01A2
#define ICON_PARKING_GSENTRIGGER_M               0x01A3
#define ICON_PARKING_H                           0x01A4
#define ICON_PARKING_MODE                        0x01A5
#define ICON_PARKING_MODE_OFF                    0x01A6
#define ICON_PARKING_SETUP                       0x01A7
#define ICON_PARKING_SETUP_M                     0x01A8
#define ICON_PARKING_TIMELAPSE                   0x01A9
#define ICON_PARKING_TIMELAPSE_M                 0x01AA
#define ICON_PARKINGGSENSOR_SETUP_M              0x01AB
#define ICON_PAUSE_NORMAL                        0x01AC
#define ICON_PAUSE_PRESS                         0x01AD
#define ICON_PB_DOWN                             0x01AE
#define ICON_PB_NEXT_PAGE                        0x01AF
#define ICON_PB_RETURN_PRE                       0x01B0
#define ICON_PB_RETURN_REL                       0x01B1
#define ICON_PB_UP                               0x01B2
#define ICON_PD_OFF                              0x01B3
#define ICON_PD_OFF_M                            0x01B4
#define ICON_PD_ON                               0x01B5
#define ICON_PD_ON_M                             0x01B6
#define ICON_PHOTO_NORMAL                        0x01B7
#define ICON_PHOTO_PRESS                         0x01B8
#define ICON_PHOTO_SETUP_NORMAL                  0x01B9
#define ICON_PHOTO_SETUP_PRESS                   0x01BA
#define ICON_PHOTOSIZE_SETUP_M                   0x01BB
#define ICON_PICTBRIDGE_S                        0x01BC
#define ICON_PIM_OFF                             0x01BD
#define ICON_PIM_OFF_M                           0x01BE
#define ICON_PIM_ON                              0x01BF
#define ICON_PIM_ON_M                            0x01C0
#define ICON_PIPREVIEW                           0x01C1
#define ICON_PLAY_BACKWARD                       0x01C2
#define ICON_PLAY_BACKWARD_PRESS                 0x01C3
#define ICON_PLAY_DELETE                         0x01C4
#define ICON_PLAY_DELETE_PRESS                   0x01C5
#define ICON_PLAY_FORWARD                        0x01C6
#define ICON_PLAY_FORWARD_PRESS                  0x01C7
#define ICON_PLAY_LOCK                           0x01C8
#define ICON_PLAY_LOCK_NOR                       0x01C9
#define ICON_PLAY_LOCK_PRESS                     0x01CA
#define ICON_PLAY_NEXT                           0x01CB
#define ICON_PLAY_NEXT_PRESS                     0x01CC
#define ICON_PLAY_NORMAL                         0x01CD
#define ICON_PLAY_PAUSE                          0x01CE
#define ICON_PLAY_PAUSE_PRESS                    0x01CF
#define ICON_PLAY_PLAY                           0x01D0
#define ICON_PLAY_PLAY_PRESS                     0x01D1
#define ICON_PLAY_PRESS                          0x01D2
#define ICON_PLAY_PREV                           0x01D3
#define ICON_PLAY_PREV_PRESS                     0x01D4
#define ICON_PLAY_STEP                           0x01D5
#define ICON_PLAY_STOP                           0x01D6
#define ICON_PLAY_STOP_PRESS                     0x01D7
#define ICON_PLAY_STOP_PREV                      0x01D8
#define ICON_PLAY_TRANSPARENT                    0x01D9
#define ICON_PLAY_UNLOCK                         0x01DA
#define ICON_PLAY_VIDOE                          0x01DB
#define ICON_PLAYBACK_NORMAL                     0x01DC
#define ICON_PLAYBACK_PRESS                      0x01DD
#define ICON_PLAYBACK_SETUP_NORMAL               0x01DE
#define ICON_PLAYBACK_SETUP_PRESS                0x01DF
#define ICON_POWER_OFF                           0x01E0
#define ICON_POWER_OFF_M                         0x01E1
#define ICON_PRINT                               0x01E2
#define ICON_PROTECT                             0x01E3
#define ICON_PROTECT_M                           0x01E4
#define ICON_QUALITY                             0x01E5
#define ICON_QUALITY_BASIC                       0x01E6
#define ICON_QUALITY_BASIC_M                     0x01E7
#define ICON_QUALITY_FINE                        0x01E8
#define ICON_QUALITY_FINE_M                      0x01E9
#define ICON_QUALITY_M                           0x01EA
#define ICON_QUALITY_NORMAL                      0x01EB
#define ICON_QUALITY_NORMAL_M                    0x01EC
#define ICON_QUALITY_SETUP_M                     0x01ED
#define ICON_QUICK_REVIEW                        0x01EE
#define ICON_QUICK_REVIEW_M                      0x01EF
#define ICON_REC_ELIPPSE                         0x01F0
#define ICON_REC_ELLIPSE                         0x01F1
#define ICON_REC_RECOVERY                        0x01F2
#define ICON_REC_START                           0x01F3
#define ICON_REC_STOP                            0x01F4
#define ICON_REC_TRANSPAENT                      0x01F5
#define ICON_RESOLUTION                          0x01F6
#define ICON_RESOLUTION_M                        0x01F7
#define ICON_RESTORE_SETUP_M                     0x01F8
#define ICON_RIGHT_NORMAL                        0x01F9
#define ICON_RIGHT_PRESS                         0x01FA
#define ICON_RIGHT_SETUP_NORMAL                  0x01FB
#define ICON_RIGHT_SETUP_PRESS                   0x01FC
#define ICON_ROTATE                              0x01FD
#define ICON_RSC_OFF                             0x01FE
#define ICON_RSC_ON                              0x01FF
#define ICON_RSC_ON_M                            0x0200
#define ICON_SCENE_MODE                          0x0201
#define ICON_SCENE_MODE_AUTO                     0x0202
#define ICON_SCENE_MODE_LANDSCPE                 0x0203
#define ICON_SCENE_MODE_M                        0x0204
#define ICON_SCENE_MODE_PORTRIAL                 0x0205
#define ICON_SCREENSAVE_SETUP_M                  0x0206
#define ICON_SCREENSAVER                         0x0207
#define ICON_SCREENSAVER_2MIN                    0x0208
#define ICON_SCREENSAVER_3MIN                    0x0209
#define ICON_SCREENSAVER_5MIN                    0x020A
#define ICON_SCREENSAVER_10MIN                   0x020B
#define ICON_SCREENSAVER_10S                     0x020C
#define ICON_SCREENSAVER_30S                     0x020D
#define ICON_SCREENSAVER_M                       0x020E
#define ICON_SCREENSAVER_OFF                     0x020F
#define ICON_SD_CARD                             0x0210
#define ICON_SD_CARD_M                           0x0211
#define ICON_SD_LOCK                             0x0212
#define ICON_SD_LOCK_M                           0x0213
#define ICON_SEL_BAR                             0x0214
#define ICON_SEL_BAR_BEGIN                       0x0215
#define ICON_SEL_BAR_DATE                        0x0216
#define ICON_SEL_BAR_END                         0x0217
#define ICON_SEL_BAR_ITEM                        0x0218
#define ICON_SEL_BAR_MED                         0x0219
#define ICON_SEL_BAR_YEAR                        0x021A
#define ICON_SELFTIMER                           0x021B
#define ICON_SELFTIMER_2SEC                      0x021C
#define ICON_SELFTIMER_5SEC                      0x021D
#define ICON_SELFTIMER_10SEC                     0x021E
#define ICON_SELFTIMER_M                         0x021F
#define ICON_SELFTIMER_OFF                       0x0220
#define ICON_SENSOR_ROTATE_SETUP_M               0x0221
#define ICON_SEQUENCE_NO                         0x0222
#define ICON_SETUP_MODE                          0x0223
#define ICON_SETUP_MODE_CHOOSE                   0x0224
#define ICON_SETUP_NORMAL                        0x0225
#define ICON_SETUP_PRESS                         0x0226
#define ICON_SETUP_SETUP_NORMAL                  0x0227
#define ICON_SETUP_SETUP_PRESS                   0x0228
#define ICON_SHAKE_OFF                           0x0229
#define ICON_SHAKE_OFF_M                         0x022A
#define ICON_SHAKE_ON                            0x022B
#define ICON_SHAKE_ON_M                          0x022C
#define ICON_SHAKE_ON_MM                         0x022D
#define ICON_SHAKE_SETUP_M                       0x022E
#define ICON_SHARPNESS                           0x022F
#define ICON_SHARPNESS_HIGH                      0x0230
#define ICON_SHARPNESS_LOW                       0x0231
#define ICON_SHARPNESS_M                         0x0232
#define ICON_SHARPNESS_MED                       0x0233
#define ICON_SHARPNESS_SETUP_M                   0x0234
#define ICON_SIGNAL_0STEP                        0x0235
#define ICON_SIGNAL_0STEP_M                      0x0236
#define ICON_SIGNAL_1STEP                        0x0237
#define ICON_SIGNAL_1STEP_M                      0x0238
#define ICON_SIGNAL_2STEP                        0x0239
#define ICON_SIGNAL_2STEP_M                      0x023A
#define ICON_SIGNAL_3STEP                        0x023B
#define ICON_SIGNAL_3STEP_M                      0x023C
#define ICON_SIGNAL_4STEP                        0x023D
#define ICON_SIGNAL_4STEP_M                      0x023E
#define ICON_SIGNAL_5STEP                        0x023F
#define ICON_SIGNAL_5STEP_M                      0x0240
#define ICON_SLIDE_SHOW                          0x0241
#define ICON_SLIDESHOW                           0x0242
#define ICON_SLIDESHOW_2SEC                      0x0243
#define ICON_SLIDESHOW_5SEC                      0x0244
#define ICON_SLIDESHOW_8SEC                      0x0245
#define ICON_SLIDESHOW_M                         0x0246
#define ICON_SLIDESHOW_OFF                       0x0247
#define ICON_SMILE                               0x0248
#define ICON_SMILE_M                             0x0249
#define ICON_SNAPE_SHOT                          0x024A
#define ICON_SNG_ALERT                           0x024B
#define ICON_SNG_OFF                             0x024C
#define ICON_SNG_OFF_M                           0x024D
#define ICON_SNG_ON                              0x024E
#define ICON_SNG_ON_M                            0x024F
#define ICON_SOUND_REC_OFF                       0x0250
#define ICON_SOUND_REC_ON                        0x0251
#define ICON_SOUND_REC_ON_M                      0x0252
#define ICON_SPEAKER                             0x0253
#define ICON_SPEEDSTAMP_SETUP                    0x0254
#define ICON_SPEEDSTAMP_SETUP_M                  0x0255
#define ICON_SPEEDUNIT_SETUP_M                   0x0256
#define ICON_SPEEDUNITS_SETUP                    0x0257
#define ICON_STOP_NORMAL                         0x0258
#define ICON_STOP_PRESS                          0x0259
#define ICON_SWITCH_CAM                          0x025A
#define ICON_SYS_CAL                             0x025B
#define ICON_SYS_CAL_M                           0x025C
#define ICON_TAB_DOWN                            0x025D
#define ICON_TAB_DOWN_PRESSED                    0x025E
#define ICON_TAB_LEFT                            0x025F
#define ICON_TAB_RIGHT                           0x0260
#define ICON_TAB_UP                              0x0261
#define ICON_TAB_UP_PRESSED                      0x0262
#define ICON_TIME_LAPSE_OFF                      0x0263
#define ICON_TIME_LAPSE_ON                       0x0264
#define ICON_TIME_LAPSE_ON_M                     0x0265
#define ICON_TIME_ZONE                           0x0266
#define ICON_TIMELAPSE_REC                       0x0267
#define ICON_TIMELAPSE_REC_1D                    0x0268
#define ICON_TIMELAPSE_REC_1H                    0x0269
#define ICON_TIMELAPSE_REC_1M                    0x026A
#define ICON_TIMELAPSE_REC_1S                    0x026B
#define ICON_TIMELAPSE_REC_1S_M                  0x026C
#define ICON_TIMELAPSE_REC_2H                    0x026D
#define ICON_TIMELAPSE_REC_2S_M                  0x026E
#define ICON_TIMELAPSE_REC_3H                    0x026F
#define ICON_TIMELAPSE_REC_5M                    0x0270
#define ICON_TIMELAPSE_REC_5S                    0x0271
#define ICON_TIMELAPSE_REC_5S_M                  0x0272
#define ICON_TIMELAPSE_REC_10M                   0x0273
#define ICON_TIMELAPSE_REC_10S                   0x0274
#define ICON_TIMELAPSE_REC_10S_M                 0x0275
#define ICON_TIMELAPSE_REC_30M                   0x0276
#define ICON_TIMELAPSE_REC_30S                   0x0277
#define ICON_TIMELAPSE_REC_OFF                   0x0278
#define ICON_TIMELAPSE_REC_STATUS                0x0279
#define ICON_TIMELASPE_SETUP_M                   0x027A
#define ICON_TIMEZONE_SETUP_M                    0x027B
#define ICON_TITLE_BAR                           0x027C
#define ICON_TITLE_WIFI_BAR                      0x027D
#define ICON_TOUCH_CAPTURE                       0x027E
#define ICON_TOUCH_DISPLAY_CHANGE                0x027F
#define ICON_TOUCH_HOME                          0x0280
#define ICON_TOUCH_LOCK_FILE                     0x0281
#define ICON_TOUCH_MODE                          0x0282
#define ICON_TOUCH_PLAYBAK                       0x0283
#define ICON_TOUCH_REC                           0x0284
#define ICON_TOUCH_REC_AUDIO                     0x0285
#define ICON_TOUCH_SETUP                         0x0286
#define ICON_TOUCH_SNAPE_SHOT                    0x0287
#define ICON_TOUCH_STOP                          0x0288
#define ICON_TOUCH_SWITCH_CAM                    0x0289
#define ICON_TSR_OFF                             0x028A
#define ICON_TSR_OFF_M                           0x028B
#define ICON_TSR_ON                              0x028C
#define ICON_TSR_ON_M                            0x028D
#define ICON_TV_MODE                             0x028E
#define ICON_TV_MODE_M                           0x028F
#define ICON_TV_MODE_OUT                         0x0290
#define ICON_TV_NTSC                             0x0291
#define ICON_TV_PAL                              0x0292
#define ICON_U_STOP_ORI                          0x0293
#define ICON_UNLOCK                              0x0294
#define ICON_UP_SETUP_NORMAL                     0x0295
#define ICON_UP_SETUP_PRESS                      0x0296
#define ICON_URGENT_PROTECT_AUTO                 0x0297
#define ICON_URGENT_PROTECT_AUTO_M               0x0298
#define ICON_URGENT_PROTECT_MANUAL               0x0299
#define ICON_URGENT_PROTECT_MANUAL_M             0x029A
#define ICON_USB_MSDC                            0x029B
#define ICON_USB_OFF                             0x029C
#define ICON_USB_ON                              0x029D
#define ICON_USB_ON_M                            0x029E
#define ICON_USB_UVC                             0x029F
#define ICON_VERSION                             0x02A0
#define ICON_VERSION_M                           0x02A1
#define ICON_VERSION_SETUP_M                     0x02A2
#define ICON_VIDEO_FLIP_OFF                      0x02A3
#define ICON_VIDEO_FLIP_ON                       0x02A4
#define ICON_VIDEO_FLIP_ON_M                     0x02A5
#define ICON_VOICE                               0x02A6
#define ICON_VOICE_M                             0x02A7
#define ICON_VOICE_MUTE                          0x02A8
#define ICON_VOICE_MUTE_A                        0x02A9
#define ICON_VOL_0                               0x02AA
#define ICON_VOL_1                               0x02AB
#define ICON_VOL_02                              0x02AC
#define ICON_VOL_2                               0x02AD
#define ICON_VOL_3                               0x02AE
#define ICON_VOL_4                               0x02AF
#define ICON_VOL_5                               0x02B0
#define ICON_VOL_6                               0x02B1
#define ICON_VOL_7                               0x02B2
#define ICON_VOL_8                               0x02B3
#define ICON_VOL_12                              0x02B4
#define ICON_VOL_22                              0x02B5
#define ICON_VOL_32                              0x02B6
#define ICON_VOL_42                              0x02B7
#define ICON_VOL_52                              0x02B8
#define ICON_VOL_62                              0x02B9
#define ICON_VOL_72                              0x02BA
#define ICON_VOL_82                              0x02BB
#define ICON_VOLUME                              0x02BC
#define ICON_WB                                  0x02BD
#define ICON_WB_AUTO                             0x02BE
#define ICON_WB_AUTO_M                           0x02BF
#define ICON_WB_CLOUDY                           0x02C0
#define ICON_WB_CLOUDY_M                         0x02C1
#define ICON_WB_DAYLIGHT                         0x02C2
#define ICON_WB_DAYLIGHT_M                       0x02C3
#define ICON_WB_FLUORESCENT                      0x02C4
#define ICON_WB_FLUORESCENT_M                    0x02C5
#define ICON_WB_M                                0x02C6
#define ICON_WB_TUNGSTEN                         0x02C7
#define ICON_WB_TUNGSTEN_M                       0x02C8
#define ICON_WDR                                 0x02C9
#define ICON_WDR_M                               0x02CA
#define ICON_WDR_OFF                             0x02CB
#define ICON_WDR_OFF_OLD                         0x02CC
#define ICON_WDR_OLD                             0x02CD
#define ICON_WDR_SETUP_M                         0x02CE
#define ICON_WEB_SITE_OFF                        0x02CF
#define ICON_WEB_SITE_ON                         0x02D0
#define ICON_WIFI                                0x02D1
#define ICON_WIFI_CLOSE                          0x02D2
#define ICON_WIFI_CONNECT                        0x02D3
#define ICON_WIFI_CONNECT2                       0x02D4
#define ICON_WIFI_CONNECTED                      0x02D5
#define ICON_WIFI_CONNECTING_ON                  0x02D6
#define ICON_WIFI_CONNECTING1                    0x02D7
#define ICON_WIFI_CONNECTING2                    0x02D8
#define ICON_WIFI_CONNECTING3                    0x02D9
#define ICON_WIFI_DOT_CONNECTING_OFF             0x02DA
#define ICON_WIFI_DOT_CONNECTING_ON              0x02DB
#define ICON_WIFI_FAIL                           0x02DC
#define ICON_WIFI_OFF                            0x02DD
#define ICON_WIFI_OFF_M                          0x02DE
#define ICON_WIFI_ON                             0x02DF
#define ICON_WIFI_ON_M                           0x02E0
#define ICON_WIFI_ON_ON                          0x02E1
#define ICON_WIFI_OPEN                           0x02E2
#define ICON_WIFI_SETUP_M                        0x02E3
#define ICON_WIFI_SIGNAL_0                       0x02E4
#define ICON_WIFI_SIGNAL_1                       0x02E5
#define ICON_WIFI_SIGNAL_2                       0x02E6
#define ICON_WIFI_SIGNAL_3                       0x02E7
#define ICON_WIFI_SIGNAL_4                       0x02E8
#define ICON_YES                                 0x02E9
#define ICON_YES_M                               0x02EA
#define _28X28NORMAL                             0x02EB

#endif //_DEMOKIT_IMAGE_H_
