#!/bin/sh
# System Daemon Run
echo "nvtapp" > /proc/nvt_info/bootts
# mmc hot plug
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s
inetd
crond
echo "nvtapp" > /proc/nvt_info/bootts

# for ISP tool
#echo "run isp_demon"
#/usr/bin/isp_demon

# disable childless pll
echo d > /proc/nvt_info/nvt_clk/clk_childless

#echo 8 8 8 8 > /proc/sys/kernel/printk
echo 0 > /proc/sys/kernel/printk
ulimit -c unlimited
modprobe drvdump
cardv &