#include "UIFlowLVGL/UIFlowWifiLinkOK/UIFlowWifiLinkOK.h"
#include "UIFlowLVGL/UIFlowLVGL.h"

#include "Resource/Plugin/lvgl_plugin.h"
/**********************
 *       WIDGETS
 **********************/

/**********************
 *  STATIC VARIABLES
 **********************/
lv_obj_t* button_select_msg_scr_uiflowwifilinkok;
lv_obj_t* label_select_msg_scr_uiflowwifilinkok;
lv_obj_t* container_1_scr_uiflowwifilinkok;
lv_obj_t* label_2_scr_uiflowwifilinkok;
lv_obj_t* label_mac_scr_uiflowwifilinkok;
lv_obj_t* label_wifista_scr_uiflowwifilinkok;
lv_obj_t* label_1_scr_uiflowwifilinkok;

lv_obj_t* UIFlowWifiLinkOK_create(){
	lv_obj_t *parent = lv_plugin_scr_create();
	lv_obj_set_event_cb(parent, UIFlowWifiLinkOKEventCallback);

	lv_color_t color = {0};
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23);
	_lv_obj_set_style_local_color(parent,0,LV_STYLE_BG_COLOR, color);

	if(color.full== LV_COLOR_TRANSP.full){
		_lv_obj_set_style_local_opa(parent,0,LV_STYLE_BG_OPA,0);
	}


	static lv_style_t button_select_msg_s0;
	lv_style_init(&button_select_msg_s0);
	lv_style_set_radius(&button_select_msg_s0,LV_STATE_DEFAULT,10);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&button_select_msg_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_select_msg_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_select_msg_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x80, 0x50, 0x50, 0x50) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_bg_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd2, 0x30, 0x30, 0x30) ; lv_style_set_border_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_outline_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_value_color(&button_select_msg_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_select_msg = lv_btn_create(parent, NULL);
	lv_obj_set_hidden(button_select_msg, false);
	lv_obj_set_click(button_select_msg, true);
	lv_obj_set_drag(button_select_msg, false);
	lv_obj_set_pos(button_select_msg, 30, 161);
	lv_obj_set_size(button_select_msg, 270, 35);
	lv_btn_set_checkable(button_select_msg, false);
	lv_btn_set_fit(button_select_msg, LV_FIT_NONE);
	lv_obj_add_style(button_select_msg, 0, &button_select_msg_s0);

	button_select_msg_scr_uiflowwifilinkok = button_select_msg;
	lv_obj_set_event_cb(button_select_msg_scr_uiflowwifilinkok, btn_sel_event_callback);


	static lv_style_t label_select_msg_s0;
	lv_style_init(&label_select_msg_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_select_msg_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc5, 0xff, 0xb4, 0x00) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x9c, 0x88, 0x88, 0x88) ; lv_style_set_text_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_select_msg_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_select_msg = lv_label_create(button_select_msg, NULL);
	lv_obj_set_hidden(label_select_msg, false);
	lv_obj_set_click(label_select_msg, false);
	lv_obj_set_drag(label_select_msg, false);
	lv_plugin_label_allocate_ext_attr(label_select_msg);
	lv_label_set_text(label_select_msg,"Press Select to Disconnect");
	lv_plugin_label_allocate_ext_attr(label_select_msg);
	lv_plugin_label_set_font_type(label_select_msg, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_select_msg, 28, 8);
	lv_obj_set_size(label_select_msg, 214, 19);
	lv_obj_add_style(label_select_msg, 0, &label_select_msg_s0);

	label_select_msg_scr_uiflowwifilinkok = label_select_msg;


	static lv_style_t container_1_s0;
	lv_style_init(&container_1_s0);
	lv_style_set_radius(&container_1_s0,LV_STATE_DEFAULT,10);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&container_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd0, 0x23, 0x23, 0x23) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *container_1 = lv_cont_create(parent, NULL);
	lv_obj_set_hidden(container_1, false);
	lv_obj_set_click(container_1, true);
	lv_obj_set_drag(container_1, false);
	lv_obj_set_pos(container_1, 30, 50);
	lv_obj_set_size(container_1, 271, 100);
	lv_obj_add_style(container_1, 0, &container_1_s0);

	container_1_scr_uiflowwifilinkok = container_1;


	static lv_style_t label_2_s0;
	lv_style_init(&label_2_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_2_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_2 = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_2, false);
	lv_obj_set_click(label_2, false);
	lv_obj_set_drag(label_2, false);
	lv_plugin_label_allocate_ext_attr(label_2);
	lv_label_set_text(label_2,"MAC");
	lv_plugin_label_allocate_ext_attr(label_2);
	lv_plugin_label_set_font_type(label_2, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_2, 15, 18);
	lv_obj_set_size(label_2, 37, 19);
	lv_obj_add_style(label_2, 0, &label_2_s0);

	label_2_scr_uiflowwifilinkok = label_2;


	static lv_style_t label_mac_s0;
	lv_style_init(&label_mac_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_mac_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_mac_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_mac_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_mac_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_mac_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_mac_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_mac_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_mac = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_mac, false);
	lv_obj_set_click(label_mac, false);
	lv_obj_set_drag(label_mac, false);
	lv_plugin_label_allocate_ext_attr(label_mac);
	lv_label_set_text(label_mac,"00:00:00:00:00:00 ");
	lv_plugin_label_allocate_ext_attr(label_mac);
	lv_plugin_label_set_font_type(label_mac, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_mac, 92, 18);
	lv_obj_set_size(label_mac, 137, 19);
	lv_obj_add_style(label_mac, 0, &label_mac_s0);

	label_mac_scr_uiflowwifilinkok = label_mac;


	static lv_style_t label_wifista_s0;
	lv_style_init(&label_wifista_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_wifista_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xf8, 0xfd, 0xfd, 0xfd) ; lv_style_set_text_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_wifista_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_wifista = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_wifista, false);
	lv_obj_set_click(label_wifista, false);
	lv_obj_set_drag(label_wifista, false);
	lv_plugin_label_allocate_ext_attr(label_wifista);
	lv_label_set_text(label_wifista,"wifi connected");
	lv_plugin_label_allocate_ext_attr(label_wifista);
	lv_plugin_label_set_font_type(label_wifista, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_wifista, 92, 65);
	lv_obj_set_size(label_wifista, 123, 19);
	lv_obj_add_style(label_wifista, 0, &label_wifista_s0);

	label_wifista_scr_uiflowwifilinkok = label_wifista;


	static lv_style_t label_1_s0;
	lv_style_init(&label_1_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_1_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xc4, 0xff, 0xa8, 0x00) ; lv_style_set_text_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_1 = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_1, false);
	lv_obj_set_click(label_1, false);
	lv_obj_set_drag(label_1, false);
	lv_plugin_label_allocate_ext_attr(label_1);
	lv_label_set_text(label_1,"Status");
	lv_plugin_label_allocate_ext_attr(label_1);
	lv_plugin_label_set_font_type(label_1, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_obj_set_pos(label_1, 15, 65);
	lv_obj_set_size(label_1, 52, 19);
	lv_obj_add_style(label_1, 0, &label_1_s0);

	label_1_scr_uiflowwifilinkok = label_1;


	return parent;
}
