#!/bin/sh

# System Driver Init
#modprobe ehci-hcd
#modprobe xhci_plat_hcd
#modprobe nvt_status
#modprobe nvt_pstore
#insmod /lib/modules/4.1.0/extra/crypto/cryptodev-linux/cryptodev.ko

insmod /lib/modules/4.1.0/vos/kwrap/kwrap.ko
insmod /lib/modules/$KERVER/hdal/comm/nvtmem/nvtmem.ko
insmod /lib/modules/4.1.0/hdal/kdrv_builtin/kdrv_builtin.ko
#insmod /lib/modules/4.1.0/hdal/comm/frammap/frammap.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_rpc/kdrv_rpc.ko
#insmod /lib/modules/4.1.0/extra/msdcnvt/msdcnvt/msdcnvt.ko

#insmod /lib/modules/4.1.0/hdal/comm/pwm/nvt_pwm.ko
insmod /lib/modules/4.1.0/hdal/comm/drv_sys/nvt_drv_sys.ko
insmod /lib/modules/4.1.0/hdal/comm/kdrv_log/kdrv_log.ko
insmod /lib/modules/4.1.0/hdal/comm/ddr_arb/ddr_arb.ko
# isf framework
insmod /lib/modules/4.1.0/hdal/kflow_common/nvtmpp/nvtmpp.ko
insmod /lib/modules/4.1.0/hdal/kflow_common/isf_flow/kflow_isf.ko

# videosprite
insmod /lib/modules/4.1.0/hdal/kdrv_gfx2d/kdrv_grph/kdrv_grph.ko
insmod /lib/modules/4.1.0/hdal/kdrv_gfx2d/kdrv_ise/kdrv_ise.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoout/ide/nvt_ide.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_videoout/dsi/nvt_dsi.ko

insmod /lib/modules/4.1.0/hdal/comm/sif/nvt_sif.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoout/display_obj/kdrv_videoout.ko
insmod /lib/modules/4.1.0/hdal/display_panel/nvt_dispdev_panel.ko
#insmod /lib/modules/4.1.0/hdal/display_panel/disp_ifpa_lcd1_wm08001_sn75lvds83b/nvt_dispdev_panel_wm08001_sn75lvds83b.ko
insmod /lib/modules/4.1.0/hdal/display_panel/disp_if8b_lcd1_pw35p00_hx8238d/disp_if8b_lcd1_pw35p00.ko
#insmod /lib/modules/4.1.0/hdal/display_panel/disp_if8b_lcd1_aucn01/disp_if8b_lcd1_aucn01.ko
#insmod /lib/modules/4.1.0/hdal/display_panel/disp_ifdsi_lcd1_nt35510/nvt_dispdev_panel_nt35510.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_gfx2d/kdrv_rotation/kdrv_rotation.ko
#insmod /lib/modules/4.1.0/extra/imgtrans/gximage/nvt_gximage.ko
#insmod /lib/modules/4.1.0/hdal/kflow_common/gximage/nvt_gximage.ko
#insmod /lib/modules/4.1.0/extra/stream/videosprite/nvt_videosprite.ko
#insmod /lib/modules/4.1.0/hdal/kflow_gfx/videosprite/nvt_videosprite.ko

# isf vdoipp
insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_dce/kdrv_dce.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_ife/kdrv_ife.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_ife2/kdrv_ife2.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_ipe/kdrv_ipe.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_ime/kdrv_ime.ko
insmod /lib/modules/4.1.0/hdal/kflow_videoprocess/ctl/kflow_ctl_ipp.ko
insmod /lib/modules/4.1.0/hdal/kflow_common/gximage/nvt_gximage.ko
insmod /lib/modules/4.1.0/hdal/kflow_gfx/videosprite/nvt_videosprite.ko
insmod /lib/modules/4.1.0/hdal/kflow_videoprocess/unit/kflow_videoproc.ko

#SDE
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_sde/kdrv_sde.ko

# gfx
insmod /lib/modules/4.1.0/hdal/kdrv_gfx2d/kdrv_affine/affine_neon/kdrv_afn_neon.ko
insmod /lib/modules/4.1.0/hdal/kdrv_gfx2d/kdrv_affine/kdrv_afn.ko
insmod /lib/modules/4.1.0/hdal/kflow_gfx/nvt_gfx.ko

# isf vdoin
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/ssenif/senphy/nvt_senphy.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/ssenif/csi/nvt_csi.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/ssenif/lvds/nvt_lvds.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/ssenif/vx1/nvt_vx1.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/ssenif/hal/nvt_ssenif.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/kdrv_sie/kdrv_sie.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocapture/kdrv_tge/kdrv_tge.ko
insmod /lib/modules/4.1.0/hdal/kflow_videocapture/ctl_sen/ctl_sen.ko
insmod /lib/modules/4.1.0/hdal/kflow_videocapture/ctl_sie/kflow_ctl_sie.ko
insmod /lib/modules/4.1.0/hdal/kflow_videocapture/unit/kflow_videocap.ko

# ipp test
#insmod /lib/modules/4.1.0/hdal/kdrv_videoprocess/kdrv_ipp_sim/kdrv_ipp_sim.ko
# isf vdoout
insmod /lib/modules/4.1.0/hdal/kflow_videoout/unit/kflow_videoout.ko

# nvt_jpg
#insmod /lib/modules/4.1.0/extra/vcodec/jpeg/nvt_jpg.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_videocodec/jpeg/kdrv_jpg.ko

# nvt_h26x
#insmod /lib/modules/4.1.0/extra/vcodec/h26x/nvt_h26x.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videocodec/kdrv_h26x.ko
insmod /lib/modules/4.1.0/hdal/nvt_vencrc/nvt_vencrc.ko

# isf vdoenc
insmod /lib/modules/4.1.0/hdal/kflow_videoenc/unit/kflow_videoenc.ko

# isf vdodec
insmod /lib/modules/4.1.0/hdal/kflow_videodec/unit/kflow_videodec.ko

# audio
insmod /lib/modules/4.1.0/hdal/kdrv_audioio/audio_common/nvt_audio.ko
insmod /lib/modules/4.1.0/hdal/kdrv_audioio/kdrv_audio/nvt_kdrv_audio.ko
#insmod /lib/modules/4.1.0/hdal/kflow_audiocapture/unit/kflow_audiocap.ko
#insmod /lib/modules/4.1.0/hdal/kflow_audioout/unit/kflow_audioout.ko

# isf audenc
#insmod /lib/modules/4.1.0/hdal/kflow_audioenc/unit/kflow_audioenc.ko

# isf auddec
#insmod /lib/modules/4.1.0/hdal/kflow_audiodec/unit/kflow_audiodec.ko

# iq, 3a
#insmod /lib/modules/4.1.0/hdal/isp/nvt_isp.ko
#insmod /lib/modules/4.1.0/hdal/ae/nvt_ae.ko
#insmod /lib/modules/4.1.0/hdal/awb/nvt_awb.ko
#insmod /lib/modules/4.1.0/hdal/af/nvt_af.ko
#insmod /lib/modules/4.1.0/hdal/dr/nvt_dr.ko
#insmod /lib/modules/4.1.0/hdal/iq/nvt_iq.ko

# iq, 3a sample
#insmod /lib/modules/4.1.0/hdal/samples/sample_nvt_ae.ko
#insmod /lib/modules/4.1.0/hdal/samples/sample_nvt_af.ko
#insmod /lib/modules/4.1.0/hdal/samples/sample_nvt_awb.ko
#insmod /lib/modules/4.1.0/hdal/samples/sample_nvt_iq.ko

# motor & sensor
modprobe nvt_sen_f37 sen_cfg_path=/mnt/app/sensor/sen_f37.cfg
modprobe nvt_sen_imx290 sen_cfg_path=/mnt/app/sensor/sen_imx290.cfg
modprobe nvt_sen_imx317 sen_cfg_path=/mnt/app/sensor/sen_imx317.cfg
modprobe nvt_sen_imx415 sen_cfg_path=/mnt/app/sensor/sen_imx415.cfg
modprobe nvt_sen_os02k10 sen_cfg_path=/mnt/app/sensor/sen_os02k10.cfg
modprobe nvt_sen_os05a10 sen_cfg_path=/mnt/app/sensor/sen_os05a10.cfg

#modprobe nvt_sen_ar0237ir sen_cfg_path=/mnt/app/sensor/sen_ar0237.cfg
#modprobe nvt_sen_imx307 sen_cfg_path=/mnt/app/sensor/sen_imx307.cfg
#modprobe nvt_sen_imx307_slave sen_cfg_path=/mnt/app/sensor/sen_imx307_slave.cfg
#modprobe nvt_sen_ov2718 sen_cfg_path=/mnt/app/sensor/sen_ov2718.cfg
#modprobe nvt_sen_sc4210 sen_cfg_path=/mnt/app/sensor/sen_sc4210.cfg
#modprobe nvt_sen_nvp6124b.ko sen_cfg_path=/mnt/app/sensor/sen_nvp6124b.cfg

# dsp
#insmod /lib/modules/4.1.0/hdal/kflow_rpc/nvt_ipc.ko
#insmod /lib/modules/4.1.0/hdal/dsp/nvt_dsp.ko

#cv
#insmod /lib/modules/4.1.0/hdal/kdrv_ive/kdrv_ive.ko
#insmod /lib/modules/4.1.0/hdal/kdrv_sde/kdrv_sde.ko
insmod /lib/modules/4.1.0/hdal/kdrv_md/kdrv_md.ko

#ai
#insmod /lib/modules/4.1.0/hdal/kdrv_ai/kdrv_ai.ko

#fb
#insmod /lib/modules/4.1.0/kernel/drivers/video/fbdev/core/fb.ko
insmod /lib/modules/4.1.0/kernel/drivers/video/fbdev/core/cfbcopyarea.ko
insmod /lib/modules/4.1.0/kernel/drivers/video/fbdev/core/cfbfillrect.ko
insmod /lib/modules/4.1.0/kernel/drivers/video/fbdev/core/cfbimgblt.ko
insmod /lib/modules/4.1.0/hdal/kdrv_videoout/fbdev/nvt_fb.ko
