//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFILIVESTREAM_H
#define UIMENUWNDWIFILIVESTREAM_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiLivestreamCtrl;//Panel type 

extern VControl UIMenuWndWiFiLivestream_StaticICN_WiFiCtrl;//Static type 

extern VControl UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiLivestream_StatusTXT_Livestream_STRID_NULL_,
UIMenuWndWiFiLivestream_StatusTXT_Livestream_MAX
}UIMenuWndWiFiLivestream_StatusTXT_Livestream_Setting;

extern VControl UIMenuWndWiFiLivestream_Tab_ExitCtrl;//Tab type 

typedef enum
{
UIMenuWndWiFiLivestream_Tab_Exit_Button_LivestreamExit,
UIMenuWndWiFiLivestream_Tab_Exit_MAX
}UIMenuWndWiFiLivestream_Tab_Exit_Setting;

extern VControl Button_LivestreamExitCtrl;//Button type 

//---------------------UIMenuWndWiFiLivestreamCtrl User Export---------------------------
#endif
