//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiLivestreamRes.c"
#include "UIMenuWndWiFiLivestream.h"
#include "PrjInc.h"
#include "UIApp/Network/UIAppNetwork.h"

#define __MODULE__          UIMENUWIFILIVESTREAM
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>
///////////////////////////////////////////////////////////////////////////////

//global variables
static BOOL       g_bLivestream = FALSE;
static UINT32     g_u32Link2ApTimer = 0;
static UINT32     g_u32Livestream1SectimerID = NULL_TIMER;


//---------------------UIMenuWndWiFiLivestreamCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiLivestreamCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiLivestream)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_StaticICN_WiFi)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_StatusTXT_Livestream)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_Tab_Exit)
CTRL_LIST_END

//----------------------UIMenuWndWiFiLivestreamCtrl Event---------------------------
INT32 UIMenuWndWiFiLivestream_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
INT32 UIMenuWndWiFiLivestream_Deauthorized(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
EVENT_BEGIN(UIMenuWndWiFiLivestream)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiLivestream_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiLivestream_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndWiFiLivestream_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIMenuWndWiFiLivestream_OnBattery)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndWiFiLivestream_OnTimer)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK, UIMenuWndWiFiLivestream_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED, UIMenuWndWiFiLivestream_Deauthorized)
EVENT_END

INT32 UIMenuWndWiFiLivestream_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UxState_SetItemData(&UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl, 0, STATE_ITEM_STRID,  Txt_Pointer(UIRes_GetUserString(STRID_CONNECT_TO_HOTSPOT)));

	UI_SetData(FL_NetWorkMode, NET_STATION_MODE);
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_START, 0);

	if (g_u32Livestream1SectimerID == NULL_TIMER) {
		//g_u32Livestream1SectimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE); //Reserved. Don't enable this timer.
	}

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	g_bLivestream = FALSE;
	g_u32Link2ApTimer = 0;
	if (g_u32Livestream1SectimerID != NULL_TIMER) {
		GxTimer_StopTimer(&g_u32Livestream1SectimerID);
	}

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;

	uiEvent = paramNum ? paramArray[0] : 0;

	switch (uiEvent) {
	case NVTEVT_1SEC_TIMER:
		g_u32Link2ApTimer++;
		DBG_DUMP("^G%s: g_u32Link2ApTimer = %d\r\n", __func__, g_u32Link2ApTimer);
		if (g_u32Link2ApTimer == 15){
			if (g_bLivestream == FALSE){
				//should close network application,then stop wifi
				Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_STOP, 0);

				//reconnect to hotspot
				Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_START, 0);
			}
			g_u32Link2ApTimer = 0;
		}
		break;
	}

    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (g_bLivestream == FALSE){
		UxState_SetItemData(&UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl, 0, STATE_ITEM_STRID,  Txt_Pointer(UIRes_GetUserString(STRID_LIVESTREAM)));
		Ux_PostEvent(NVTEVT_EXE_MOVIE_STRM_START,0);
		Ux_PostEvent(NVTEVT_EXE_WIFI_LIVESTREAM, 0);
		g_bLivestream = TRUE;

		if (g_u32Livestream1SectimerID != NULL_TIMER) {
			GxTimer_StopTimer(&g_u32Livestream1SectimerID);
			g_u32Link2ApTimer = 0;
		}
	}

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_Deauthorized(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (g_bLivestream){
		g_bLivestream = FALSE;

		UxState_SetItemData(&UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl, 0, STATE_ITEM_STRID,  Txt_Pointer(UIRes_GetUserString(STRID_HOTSPOT_IS_BROKEN)));
		Ux_Redraw();
		//should close network application,then stop wifi
		Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_WIFI_STOP, 0);

		UI_SetData(FL_NetWorkMode, NET_AP_MODE); //set to AP mode
		Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_MODE, 0); //Default to AP SSID & Password

		Ux_PostEvent(NVTEVT_EXE_MOVIE_STRM_STOP,0);
		Ux_CloseWindow(&MenuCommonItemCtrl, 0);
	}

	return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiLivestream_StaticICN_WiFiCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiLivestream_StaticICN_WiFi)
EVENT_END

//----------------------UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiLivestream_StatusTXT_Livestream)
EVENT_END

//----------------------UIMenuWndWiFiLivestream_Tab_ExitCtrl Event---------------------------
INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter1(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiLivestream_Tab_Exit)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndWiFiLivestream_Tab_Exit_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_SHUTTER1,UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter1)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiKeyAct;

	uiKeyAct = paramArray[0];
	switch (uiKeyAct) {
	case NVTEVT_KEY_PRESS:
		if (g_bLivestream){
			g_bLivestream = FALSE;

			//should close network application,then stop wifi
			Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_WIFI_STOP, 0);
		    UI_SetData(FL_NetWorkMode, NET_AP_MODE); //set to AP mode
		    Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_MODE, 0); //Default to AP SSID & Password
			Ux_PostEvent(NVTEVT_EXE_MOVIE_STRM_STOP,0);

			Ux_CloseWindow(&MenuCommonItemCtrl, 0);

		}else{ //waiting to connecto to hotspot and terminating it within 30 seconds

			//should close network application,then stop wifi
			Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_WIFI_STOP, 0);

			UI_SetData(FL_NetWorkMode, NET_AP_MODE); //set to AP mode
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_MODE, 0); //Default to AP SSID & Password

			Ux_CloseWindow(&MenuCommonItemCtrl, 0);
		}
		break;
	}

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter1(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_Tab_Exit_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------Button_LivestreamExitCtrl Event---------------------------
EVENT_BEGIN(Button_LivestreamExit)
EVENT_END

