#!/bin/sh
GROUP_KO=ON
KERVER=`cat /proc/version | awk -F'version ' '{print $2}' | awk -F' ' '{print $1}'`
# System Driver Init
#modprobe ehci-hcd
#modprobe xhci_plat_hcd
#modprobe nvt_status
#modprobe nvt_pstore
insmod /lib/modules/$KERVER/extra/crypto/cryptodev-linux/cryptodev.ko

insmod /lib/modules/$KERVER/vos/kwrap/kwrap.ko
insmod /lib/modules/$KERVER/hdal/comm/nvtmem/nvtmem.ko
insmod /lib/modules/$KERVER/hdal/kdrv_builtin/kdrv_builtin.ko

if [ "$GROUP_KO" == "ON" ]; then
insmod /lib/modules/$KERVER/hdal/comm/kdrv_comm.ko
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_gfx2d.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/kdrv_videocapture.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_videoprocess.ko
insmod /lib/modules/$KERVER/hdal/kflow_common/kflow_common.ko
insmod /lib/modules/$KERVER/hdal/kflow_gfx/videosprite/nvt_videosprite.ko
insmod /lib/modules/$KERVER/hdal/kflow_videocapture/kflow_videocapture.ko
insmod /lib/modules/$KERVER/hdal/kflow_videoprocess/kflow_videoprocess.ko
else
# kdrv_comm
#insmod /lib/modules/$KERVER/hdal/comm/frammap/frammap.ko
#insmod /lib/modules/$KERVER/extra/msdcnvt/msdcnvt/msdcnvt.ko
#insmod /lib/modules/$KERVER/hdal/comm/pwm/nvt_pwm.ko
insmod /lib/modules/$KERVER/hdal/comm/drv_sys/nvt_drv_sys.ko
insmod /lib/modules/$KERVER/hdal/comm/ddr_arb/ddr_arb.ko
insmod /lib/modules/$KERVER/hdal/comm/kdrv_log/kdrv_log.ko
insmod /lib/modules/$KERVER/hdal/comm/sif/nvt_sif.ko
# kdrv_gfx2d
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_grph/kdrv_grph.ko
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_ise/kdrv_ise.ko
# kdrv_videocapture
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/ssenif/senphy/nvt_senphy.ko
# kdrv_videocatpure for sensor interface selection
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/ssenif/hal/nvt_ssenif.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/ssenif/csi/nvt_csi.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/ssenif/lvds/nvt_lvds.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/kdrv_sie/kdrv_sie.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/kdrv_tge/kdrv_tge.ko
# kdrv_videoprocess
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_dce/kdrv_dce.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_ife/kdrv_ife.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_ife2/kdrv_ife2.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_ipe/kdrv_ipe.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_ime/kdrv_ime.ko
# kflow_common
insmod /lib/modules/$KERVER/hdal/kflow_common/nvtmpp/nvtmpp.ko
insmod /lib/modules/$KERVER/hdal/kflow_common/isf_flow/kflow_isf.ko
insmod /lib/modules/$KERVER/hdal/kflow_common/gximage/nvt_gximage.ko
# kflow_gfx
insmod /lib/modules/$KERVER/hdal/kflow_gfx/videosprite/nvt_videosprite.ko
# kflow_videocapture
insmod /lib/modules/$KERVER/hdal/kflow_videocapture/ctl_sen/ctl_sen.ko
insmod /lib/modules/$KERVER/hdal/kflow_videocapture/ctl_sie/kflow_ctl_sie.ko
insmod /lib/modules/$KERVER/hdal/kflow_videocapture/unit/kflow_videocap.ko
#kflow_videoprocess
insmod /lib/modules/$KERVER/hdal/kflow_videoprocess/ctl/kflow_ctl_ipp.ko
insmod /lib/modules/$KERVER/hdal/kflow_videoprocess/unit/kflow_videoproc.ko
fi

# rpc
#insmod /lib/modules/$KERVER/hdal/kdrv_rpc/kdrv_rpc.ko

#SDE
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_sde/kdrv_sde.ko

#VPE
if [ ${NVT_CHIP_ID} == "CHIP_NA51084" ]; then
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_vpe/kdrv_vpe.ko
fi

# kdrv_gfx2d
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_affine/affine_neon/kdrv_afn_neon.ko
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_affine/kdrv_afn.ko
insmod /lib/modules/$KERVER/hdal/kflow_gfx/nvt_gfx.ko

# kdrv_vdoout
insmod /lib/modules/$KERVER/hdal/kdrv_videoout/ide/nvt_ide.ko
#insmod /lib/modules/$KERVER/hdal/kdrv_videoout/mi/nvt_mi.ko
#insmod /lib/modules/$KERVER/hdal/kdrv_videoout/dsi/nvt_dsi.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoout/display_obj/kdrv_videoout.ko

# kflow_videoout
if [ ${NVT_CHIP_ID} == "CHIP_NA51084" ]; then
modprobe nvt_gyro_spi.ko
insmod /lib/modules/$KERVER/hdal/gyro_comm/gyro_comm.ko
insmod /lib/modules/$KERVER/hdal/gyro_icm42607/nvt_gyro_icm42607.ko
fi
insmod /lib/modules/$KERVER/hdal/kflow_videoout/unit/kflow_videoout.ko

# panel device
insmod /lib/modules/$KERVER/hdal/display_panel/nvt_dispdev_panel.ko
case "${LCD1}" in
    disp_off)
        ;;
    disp_if8b_lcd1_pw35p00)
        insmod /lib/modules/$KERVER/hdal/display_panel/${LCD1}_hx8238d/$LCD1.ko
        ;;
    *)
        if [[ $(echo $LCD1 | grep -c 'ifdsi') == "1" ]]; then
            insmod /lib/modules/$KERVER/hdal/kdrv_videoout/dsi/nvt_dsi.ko
        fi
        insmod /lib/modules/$KERVER/hdal/display_panel/${LCD1}/${LCD1}.ko
        ;;
esac

#insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_rotation/kdrv_rotation.ko
#insmod /lib/modules/$KERVER/hdal/kflow_gfx/videosprite/nvt_videosprite.ko

# ipp test
#insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_ipp_sim/kdrv_ipp_sim.ko

# nvt_jpg
#insmod /lib/modules/$KERVER/extra/vcodec/jpeg/nvt_jpg.ko
#insmod /lib/modules/$KERVER/hdal/kdrv_videocodec/jpeg/kdrv_jpg.ko

# nvt_h26x
#insmod /lib/modules/$KERVER/extra/vcodec/h26x/nvt_h26x.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocodec/kdrv_h26x.ko
insmod /lib/modules/$KERVER/hdal/nvt_vencrc/nvt_vencrc.ko

# isf vdoenc
insmod /lib/modules/$KERVER/hdal/kflow_videoenc/unit/kflow_videoenc.ko

# isf vdodec
insmod /lib/modules/$KERVER/hdal/kflow_videodec/unit/kflow_videodec.ko

# audio
insmod /lib/modules/$KERVER/hdal/kdrv_audioio/audio_common/nvt_audio.ko
insmod /lib/modules/$KERVER/hdal/kdrv_audioio/kdrv_audio/nvt_kdrv_audio.ko
insmod /lib/modules/$KERVER/hdal/kdrv_audioio/audlib_aac/nvt_audlib_aac.ko
insmod /lib/modules/$KERVER/hdal/kflow_audiocapture/unit/kflow_audiocap.ko
insmod /lib/modules/$KERVER/hdal/kflow_audioout/unit/kflow_audioout.ko

# isf audenc
insmod /lib/modules/$KERVER/hdal/kflow_audioenc/unit/kflow_audioenc.ko

# isf auddec
insmod /lib/modules/$KERVER/hdal/kflow_audiodec/unit/kflow_audiodec.ko

# iq, 3a
if [ ${NVT_CHIP_ID} == "CHIP_NA51084" ]; then
echo "isp_id_list: 0x1B, ae_id_list: 0x1B, awb_id_list: 0x1B, iq_id_list 0x1B"
insmod /lib/modules/$KERVER/hdal/isp/nvt_isp.ko isp_id_list=0x1B
insmod /lib/modules/$KERVER/hdal/awb/nvt_awb.ko awb_id_list=0x1B
insmod /lib/modules/$KERVER/hdal/iq/nvt_iq.ko iq_id_list=0x1B
insmod /lib/modules/$KERVER/hdal/ae/nvt_ae.ko ae_id_list=0x1B
else
echo "isp_id_list: 0x3, ae_id_list: 0x3, awb_id_list: 0x3, iq_id_list 0x3"
insmod /lib/modules/$KERVER/hdal/isp/nvt_isp.ko
insmod /lib/modules/$KERVER/hdal/awb/nvt_awb.ko
insmod /lib/modules/$KERVER/hdal/iq/nvt_iq.ko
insmod /lib/modules/$KERVER/hdal/ae/nvt_ae.ko
fi
#insmod /lib/modules/$KERVER/hdal/af/nvt_af.ko
#insmod /lib/modules/$KERVER/hdal/dr/nvt_dr.ko
insmod /lib/modules/$KERVER/hdal/vpe/nvt_vpe.ko
insmod /lib/modules/$KERVER/hdal/sde/nvt_sde.ko

# iq, 3a sample
#insmod /lib/modules/$KERVER/hdal/samples/sample_nvt_ae.ko
#insmod /lib/modules/$KERVER/hdal/samples/sample_nvt_af.ko
#insmod /lib/modules/$KERVER/hdal/samples/sample_nvt_awb.ko
#insmod /lib/modules/$KERVER/hdal/samples/sample_nvt_iq.ko

# motor & sensor
if [ "${SENSOR1}" != "sen_off" ]; then
    if [ "${SENSOR1_CFG}" != "sen_off" ]; then
    insmod /lib/modules/$KERVER/hdal/${SENSOR1}/nvt_${SENSOR1}.ko sen_cfg_path=/mnt/app/sensor/${SENSOR1_CFG}.cfg
    else
        insmod /lib/modules/$KERVER/hdal/${SENSOR1}/nvt_${SENSOR1}.ko
    fi
fi
if [ "${SENSOR2}" != "sen_off" ] && [ "${SENSOR1}" != "${SENSOR2}" ]; then
    if [ "${SENSOR2_CFG}" != "sen_off" ]; then
    insmod /lib/modules/$KERVER/hdal/${SENSOR2}/nvt_${SENSOR2}.ko sen_cfg_path=/mnt/app/sensor/${SENSOR2_CFG}.cfg
    else
        insmod /lib/modules/$KERVER/hdal/${SENSOR2}/nvt_${SENSOR2}.ko
    fi
fi

# dsp
#insmod /lib/modules/$KERVER/hdal/kflow_rpc/nvt_ipc.ko
#insmod /lib/modules/$KERVER/hdal/dsp/nvt_dsp.ko

#cv
insmod /lib/modules/$KERVER/hdal/kdrv_ive/kdrv_ive.ko
#insmod /lib/modules/$KERVER/hdal/kdrv_sde/kdrv_sde.ko
insmod /lib/modules/$KERVER/hdal/kdrv_md/kdrv_md.ko
insmod /lib/modules/$KERVER/hdal/kdrv_dis/kdrv_dis.ko

#ai
insmod /lib/modules/$KERVER/hdal/kdrv_ai/kdrv_ai.ko
#insmod /lib/modules/$KERVER/hdal/net_flow_sample/netflowsample.ko

#fb
#insmod /lib/modules/$KERVER/kernel/drivers/video/fbdev/core/fb.ko
insmod /lib/modules/$KERVER/kernel/drivers/video/fbdev/core/cfbcopyarea.ko
insmod /lib/modules/$KERVER/kernel/drivers/video/fbdev/core/cfbfillrect.ko
insmod /lib/modules/$KERVER/kernel/drivers/video/fbdev/core/cfbimgblt.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoout/fbdev/nvt_fb.ko

#eis
if [ ${NVT_CHIP_ID} == "CHIP_NA51084" ]; then
insmod /lib/modules/$KERVER/hdal/eis/nvt_eis.ko
fi

#usb
if [ ${NVT_CHIP_ID} == "CHIP_NA51084" ]; then
    insmod /lib/modules/$KERVER/hdal/comm/usb2dev8/nvt_usb2dev8.ko
else
    insmod /lib/modules/$KERVER/hdal/comm/usb2dev/nvt_usb2dev.ko
fi

#iio & adc (for keyscan)
insmod /lib/modules/$KERVER/kernel/drivers/iio/industrialio.ko
#insmod /lib/modules/$KERVER/kernel/drivers/iio/industrialio-configfs.ko
insmod /lib/modules/$KERVER/kernel/drivers/iio/adc/nvt_adc.ko

#tse
if [ "${TSE}" == "enable" ]; then
    insmod /lib/modules/$KERVER/hdal/comm/tse/nvt_tse.ko
fi