# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 Novateck, Inc
#
obj-$(CONFIG_TARGET_NA51055) += nvt-na51055/ide/ide2.o nvt-na51055/ide/ide2_int.o nvt-na51055/ide/ide2_osd.o nvt-na51055/ide/ide2_video.o nvt-na51055/ide/idec_cmd.o nvt-na51055/ide/idec.o nvt-na51055/ide/ide_platform.o nvt-na51055/dsi/dsi.o nvt-na51055/dsi/dsi_int.o nvt-na51055/dsi/dsi_platform.o display_obj/disp1.o display_obj/display.o display_obj/display_obj_platform.o display_obj/kdrv_vdoout.o
obj-$(CONFIG_TARGET_NA51090_A64) += nvt-na51090/lcd310/lcd310.o nvt-na51090/lcd210/lcd210.o nvt-na51090/hdmi/dispdev_hdmi_if.o nvt-na51090/hdmi/hdmitx.o  nvt-na51090/hdmi/hdmitx_cec.o nvt-na51090/hdmi/hdmitx_ddc.o nvt-na51090/hdmi/hdmitx_edid.o nvt-na51090/hdmi/hdmitx_port.o


